// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/relay-protocol/*.{params,result}.json — regenerate with:
//   go run ./cmd/generate-rest
//
// One Go type per RELAY WS method's params (<Method>Params) and ack result
// (<Method>Result), from the canonical switchblade wire schemas. Object schemas
// with properties become structs (json wire-key tags, optional fields -> *T);
// empty-object / non-object schemas become map[string]any aliases. STATIC-ONLY:
// at runtime each payload is a plain map; this layer just types the shapes.

package relay

type CallingAiHoldParams struct {
	Async   *bool   `json:"async,omitempty"`
	CallId  string  `json:"call_id,omitempty"`
	NodeId  string  `json:"node_id,omitempty"`
	Prompt  *string `json:"prompt,omitempty"`
	Swml    *bool   `json:"swml,omitempty"`
	Timeout *string `json:"timeout,omitempty"`
}

type CallingAiMessageParams struct {
	Async       *bool          `json:"async,omitempty"`
	CallId      string         `json:"call_id,omitempty"`
	GlobalData  map[string]any `json:"global_data,omitempty"`
	MessageText *string        `json:"message_text,omitempty"`
	NodeId      string         `json:"node_id,omitempty"`
	Reset       map[string]any `json:"reset,omitempty"`
	Role        *string        `json:"role,omitempty"`
	Swml        *bool          `json:"swml,omitempty"`
}

type CallingAiUnholdParams struct {
	Async  *bool   `json:"async,omitempty"`
	CallId string  `json:"call_id,omitempty"`
	NodeId string  `json:"node_id,omitempty"`
	Prompt *string `json:"prompt,omitempty"`
	Swml   *bool   `json:"swml,omitempty"`
}

type CallingAmazonBedrockParams struct {
	SWAIG         map[string]any `json:"SWAIG,omitempty"`
	Async         *bool          `json:"async,omitempty"`
	CallId        string         `json:"call_id,omitempty"`
	GlobalData    map[string]any `json:"global_data,omitempty"`
	NodeId        string         `json:"node_id,omitempty"`
	Params        map[string]any `json:"params,omitempty"`
	PostPrompt    map[string]any `json:"post_prompt,omitempty"`
	PostPromptUrl *string        `json:"post_prompt_url,omitempty"`
	Prompt        map[string]any `json:"prompt,omitempty"`
	Swml          *bool          `json:"swml,omitempty"`
}

type CallingAnswerParams struct {
	CallId      string `json:"call_id,omitempty"`
	MaxDuration *int   `json:"max_duration,omitempty"`
	NodeId      string `json:"node_id,omitempty"`
}

type CallingBeginParams struct {
	Device      map[string]any `json:"device,omitempty"`
	MaxDuration *int           `json:"max_duration,omitempty"`
	NodeId      *string        `json:"node_id,omitempty"`
	Region      *string        `json:"region,omitempty"`
	Tag         *string        `json:"tag,omitempty"`
}

type CallingBindDigitParams struct {
	BindMethod  string         `json:"bind_method,omitempty"`
	CallId      string         `json:"call_id,omitempty"`
	Digits      string         `json:"digits,omitempty"`
	MaxTriggers *int           `json:"max_triggers,omitempty"`
	NodeId      string         `json:"node_id,omitempty"`
	Params      map[string]any `json:"params,omitempty"`
	Realm       *string        `json:"realm,omitempty"`
	Swml        *bool          `json:"swml,omitempty"`
}

type CallingCallParams map[string]any

type CallingClearDigitBindingsParams struct {
	CallId string  `json:"call_id,omitempty"`
	NodeId string  `json:"node_id,omitempty"`
	Realm  *string `json:"realm,omitempty"`
	Swml   *bool   `json:"swml,omitempty"`
}

type CallingCollectParams struct {
	CallId           string         `json:"call_id,omitempty"`
	Continue_        *bool          `json:"continue,omitempty"`
	Continuous       *bool          `json:"continuous,omitempty"`
	ControlId        string         `json:"control_id,omitempty"`
	Digits           map[string]any `json:"digits,omitempty"`
	InitialTimeout   *float64       `json:"initial_timeout,omitempty"`
	NodeId           string         `json:"node_id,omitempty"`
	PartialResults   *bool          `json:"partial_results,omitempty"`
	SendStartOfInput *bool          `json:"send_start_of_input,omitempty"`
	Speech           map[string]any `json:"speech,omitempty"`
	StartInputTimers *bool          `json:"start_input_timers,omitempty"`
}

type CallingCollectStartInputTimersParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingCollectStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingConnectParams struct {
	CallId            string             `json:"call_id,omitempty"`
	Devices           [][]map[string]any `json:"devices,omitempty"`
	MaxDuration       *int               `json:"max_duration,omitempty"`
	MaxPricePerMinute *float64           `json:"max_price_per_minute,omitempty"`
	NodeId            string             `json:"node_id,omitempty"`
	Ringback          []map[string]any   `json:"ringback,omitempty"`
	Tag               *string            `json:"tag,omitempty"`
}

type CallingDenoiseParams struct {
	CallId string `json:"call_id,omitempty"`
	NodeId string `json:"node_id,omitempty"`
}

type CallingDenoiseStopParams struct {
	CallId string `json:"call_id,omitempty"`
	NodeId string `json:"node_id,omitempty"`
}

type CallingDetectParams struct {
	CallId    string         `json:"call_id,omitempty"`
	ControlId string         `json:"control_id,omitempty"`
	Detect    map[string]any `json:"detect,omitempty"`
	NodeId    string         `json:"node_id,omitempty"`
	Timeout   *float64       `json:"timeout,omitempty"`
}

type CallingDetectStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingDialParams struct {
	Devices           [][]map[string]any `json:"devices,omitempty"`
	MaxPricePerMinute *float64           `json:"max_price_per_minute,omitempty"`
	NodeId            *string            `json:"node_id,omitempty"`
	Region            *string            `json:"region,omitempty"`
	Tag               *string            `json:"tag,omitempty"`
}

type CallingDisconnectParams struct {
	CallId string `json:"call_id,omitempty"`
	NodeId string `json:"node_id,omitempty"`
}

type CallingEchoParams struct {
	CallId    string   `json:"call_id,omitempty"`
	NodeId    string   `json:"node_id,omitempty"`
	StatusUrl *string  `json:"status_url,omitempty"`
	Swml      *bool    `json:"swml,omitempty"`
	Timeout   *float64 `json:"timeout,omitempty"`
}

type CallingEndParams struct {
	CallId string  `json:"call_id,omitempty"`
	NodeId string  `json:"node_id,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

type CallingJoinConferenceParams struct {
	Acl                              *string        `json:"acl,omitempty"`
	Beep                             *string        `json:"beep,omitempty"`
	CallId                           string         `json:"call_id,omitempty"`
	Coach                            *string        `json:"coach,omitempty"`
	EndOnExit                        *bool          `json:"end_on_exit,omitempty"`
	MaxParticipants                  *int           `json:"max_participants,omitempty"`
	Muted                            *bool          `json:"muted,omitempty"`
	Name                             string         `json:"name,omitempty"`
	NodeId                           string         `json:"node_id,omitempty"`
	Record                           *string        `json:"record,omitempty"`
	RecordingStatusCallback          *string        `json:"recording_status_callback,omitempty"`
	RecordingStatusCallbackEvent     *string        `json:"recording_status_callback_event,omitempty"`
	RecordingStatusCallbackEventType *string        `json:"recording_status_callback_event_type,omitempty"`
	RecordingStatusCallbackMethod    *string        `json:"recording_status_callback_method,omitempty"`
	Region                           *string        `json:"region,omitempty"`
	StartOnEnter                     *bool          `json:"start_on_enter,omitempty"`
	StatusCallback                   *string        `json:"status_callback,omitempty"`
	StatusCallbackEvent              *string        `json:"status_callback_event,omitempty"`
	StatusCallbackEventType          *string        `json:"status_callback_event_type,omitempty"`
	StatusCallbackMethod             *string        `json:"status_callback_method,omitempty"`
	Stream                           map[string]any `json:"stream,omitempty"`
	Swml                             *bool          `json:"swml,omitempty"`
	Trim                             *string        `json:"trim,omitempty"`
	WaitUrl                          *string        `json:"wait_url,omitempty"`
}

type CallingJoinRoomParams struct {
	CallId           string  `json:"call_id,omitempty"`
	HagridJsonApiUrl *string `json:"hagrid_json_api_url,omitempty"`
	HagridNodeId     *string `json:"hagrid_node_id,omitempty"`
	Name             string  `json:"name,omitempty"`
	NodeId           string  `json:"node_id,omitempty"`
	StatusUrl        *string `json:"status_url,omitempty"`
	Swml             *bool   `json:"swml,omitempty"`
}

type CallingLeaveConferenceParams struct {
	Async        *bool  `json:"async,omitempty"`
	CallId       string `json:"call_id,omitempty"`
	ConferenceId string `json:"conference_id,omitempty"`
	NodeId       string `json:"node_id,omitempty"`
}

type CallingLeaveRoomParams struct {
	Async  *bool  `json:"async,omitempty"`
	CallId string `json:"call_id,omitempty"`
	NodeId string `json:"node_id,omitempty"`
}

type CallingLiveTranscribeParams struct {
	Action map[string]any `json:"action,omitempty"`
	Async  *bool          `json:"async,omitempty"`
	CallId string         `json:"call_id,omitempty"`
	NodeId string         `json:"node_id,omitempty"`
	Swml   *bool          `json:"swml,omitempty"`
}

type CallingLiveTranslateParams struct {
	Action    map[string]any `json:"action,omitempty"`
	Async     *bool          `json:"async,omitempty"`
	CallId    string         `json:"call_id,omitempty"`
	NodeId    string         `json:"node_id,omitempty"`
	StatusUrl *string        `json:"status_url,omitempty"`
	Swml      *bool          `json:"swml,omitempty"`
}

type CallingPassParams struct {
	CallId string `json:"call_id,omitempty"`
	NodeId string `json:"node_id,omitempty"`
}

type CallingPayParams struct {
	BankAccountType     map[string]any   `json:"bank_account_type,omitempty"`
	CallId              string           `json:"call_id,omitempty"`
	ChargeAmount        *string          `json:"charge_amount,omitempty"`
	ControlId           string           `json:"control_id,omitempty"`
	Currency            *string          `json:"currency,omitempty"`
	Description         *string          `json:"description,omitempty"`
	Input               map[string]any   `json:"input,omitempty"`
	Language            *string          `json:"language,omitempty"`
	MaxAttempts         *string          `json:"max_attempts,omitempty"`
	MinPostalCodeLength *string          `json:"min_postal_code_length,omitempty"`
	NodeId              string           `json:"node_id,omitempty"`
	Parameters          []map[string]any `json:"parameters,omitempty"`
	PaymentConnectorUrl string           `json:"payment_connector_url,omitempty"`
	PaymentMethod       map[string]any   `json:"payment_method,omitempty"`
	PostalCode          *string          `json:"postal_code,omitempty"`
	Prompts             []map[string]any `json:"prompts,omitempty"`
	SecurityCode        *string          `json:"security_code,omitempty"`
	StatusUrl           *string          `json:"status_url,omitempty"`
	Timeout             *string          `json:"timeout,omitempty"`
	TokenType           map[string]any   `json:"token_type,omitempty"`
	ValidCardTypes      *string          `json:"valid_card_types,omitempty"`
	Voice               *string          `json:"voice,omitempty"`
}

type CallingPayStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingPlayParams struct {
	CallId    string           `json:"call_id,omitempty"`
	ControlId string           `json:"control_id,omitempty"`
	NodeId    string           `json:"node_id,omitempty"`
	Play      []map[string]any `json:"play,omitempty"`
	Volume    *float64         `json:"volume,omitempty"`
}

type CallingPlayPauseParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingPlayResumeParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingPlayStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingPlayVolumeParams struct {
	CallId    string  `json:"call_id,omitempty"`
	ControlId string  `json:"control_id,omitempty"`
	NodeId    string  `json:"node_id,omitempty"`
	Volume    float64 `json:"volume,omitempty"`
}

type CallingPlayAndCollectParams struct {
	CallId    string           `json:"call_id,omitempty"`
	Collect   map[string]any   `json:"collect,omitempty"`
	ControlId string           `json:"control_id,omitempty"`
	NodeId    string           `json:"node_id,omitempty"`
	Play      []map[string]any `json:"play,omitempty"`
	Volume    *float64         `json:"volume,omitempty"`
}

type CallingPlayAndCollectStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingPlayAndCollectVolumeParams struct {
	CallId    string  `json:"call_id,omitempty"`
	ControlId string  `json:"control_id,omitempty"`
	NodeId    string  `json:"node_id,omitempty"`
	Volume    float64 `json:"volume,omitempty"`
}

type CallingQueueEnterParams struct {
	CallId    string  `json:"call_id,omitempty"`
	ControlId string  `json:"control_id,omitempty"`
	NodeId    string  `json:"node_id,omitempty"`
	QueueName string  `json:"queue_name,omitempty"`
	StatusUrl *string `json:"status_url,omitempty"`
	WaitUrl   *string `json:"wait_url,omitempty"`
}

type CallingQueueLeaveParams struct {
	CallId    string  `json:"call_id,omitempty"`
	ControlId string  `json:"control_id,omitempty"`
	NodeId    string  `json:"node_id,omitempty"`
	QueueId   *string `json:"queue_id,omitempty"`
	QueueName string  `json:"queue_name,omitempty"`
	StatusUrl *string `json:"status_url,omitempty"`
}

type CallingReceiveParams struct {
	Context  *string  `json:"context,omitempty"`
	Contexts []string `json:"contexts,omitempty"`
}

type CallingReceiveFaxParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingReceiveFaxStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingRecordParams struct {
	CallId    string         `json:"call_id,omitempty"`
	ControlId string         `json:"control_id,omitempty"`
	NodeId    string         `json:"node_id,omitempty"`
	Record    map[string]any `json:"record,omitempty"`
}

type CallingRecordPauseParams struct {
	Behavior  *string `json:"behavior,omitempty"`
	CallId    string  `json:"call_id,omitempty"`
	ControlId string  `json:"control_id,omitempty"`
	NodeId    string  `json:"node_id,omitempty"`
}

type CallingRecordResumeParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingRecordStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingReferParams struct {
	CallId string         `json:"call_id,omitempty"`
	Device map[string]any `json:"device,omitempty"`
	NodeId string         `json:"node_id,omitempty"`
}

type CallingSendDigitsParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	Digits    string `json:"digits,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingSendFaxParams struct {
	CallId     string  `json:"call_id,omitempty"`
	ControlId  string  `json:"control_id,omitempty"`
	Document   string  `json:"document,omitempty"`
	HeaderInfo *string `json:"header_info,omitempty"`
	Identity   *string `json:"identity,omitempty"`
	NodeId     string  `json:"node_id,omitempty"`
}

type CallingSendFaxStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingStreamParams struct {
	Async                    *bool          `json:"async,omitempty"`
	AuthorizationBearerToken *string        `json:"authorization_bearer_token,omitempty"`
	CallId                   string         `json:"call_id,omitempty"`
	Codec                    *string        `json:"codec,omitempty"`
	ControlId                string         `json:"control_id,omitempty"`
	CustomParameters         map[string]any `json:"custom_parameters,omitempty"`
	Name                     *string        `json:"name,omitempty"`
	NodeId                   string         `json:"node_id,omitempty"`
	StatusUrl                *string        `json:"status_url,omitempty"`
	StatusUrlMethod          *string        `json:"status_url_method,omitempty"`
	Swml                     *bool          `json:"swml,omitempty"`
	Track                    *string        `json:"track,omitempty"`
	Url                      string         `json:"url,omitempty"`
}

type CallingStreamStopParams struct {
	Async     *bool  `json:"async,omitempty"`
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
	Swml      *bool  `json:"swml,omitempty"`
}

type CallingTapParams struct {
	CallId    string         `json:"call_id,omitempty"`
	ControlId string         `json:"control_id,omitempty"`
	Device    map[string]any `json:"device,omitempty"`
	NodeId    string         `json:"node_id,omitempty"`
	Tap       map[string]any `json:"tap,omitempty"`
}

type CallingTapStopParams struct {
	CallId    string `json:"call_id,omitempty"`
	ControlId string `json:"control_id,omitempty"`
	NodeId    string `json:"node_id,omitempty"`
}

type CallingTransferParams struct {
	CallId string `json:"call_id,omitempty"`
	Dest   string `json:"dest,omitempty"`
	NodeId string `json:"node_id,omitempty"`
}

type CallingUserEventParams struct {
	Async  *bool          `json:"async,omitempty"`
	CallId string         `json:"call_id,omitempty"`
	Event  map[string]any `json:"event,omitempty"`
	NodeId string         `json:"node_id,omitempty"`
	Swml   *bool          `json:"swml,omitempty"`
}

type MessagingSendParams struct {
	Body       *string  `json:"body,omitempty"`
	Context    string   `json:"context,omitempty"`
	FromNumber string   `json:"from_number,omitempty"`
	Media      []string `json:"media,omitempty"`
	Region     *string  `json:"region,omitempty"`
	Tags       []string `json:"tags,omitempty"`
	ToNumber   string   `json:"to_number,omitempty"`
}

type SignalwireConnectParams struct {
	Agent          *string          `json:"agent,omitempty"`
	Authentication map[string]any   `json:"authentication,omitempty"`
	Host           *string          `json:"host,omitempty"`
	Identity       *string          `json:"identity,omitempty"`
	Params         map[string]any   `json:"params,omitempty"`
	Protocols      []map[string]any `json:"protocols,omitempty"`
	Version        map[string]any   `json:"version,omitempty"`
}

type SignalwireDisconnectParams struct {
	Restart *bool `json:"restart,omitempty"`
}

type SignalwireExecuteParams struct {
	Attempted         []string       `json:"attempted,omitempty"`
	Method            string         `json:"method,omitempty"`
	Params            map[string]any `json:"params,omitempty"`
	Protocol          string         `json:"protocol,omitempty"`
	RequesterIdentity *string        `json:"requester_identity,omitempty"`
	RequesterNodeid   *string        `json:"requester_nodeid,omitempty"`
	ResponderIdentity *string        `json:"responder_identity,omitempty"`
	ResponderNodeid   *string        `json:"responder_nodeid,omitempty"`
}

type SignalwirePingParams struct {
	Payload   *string  `json:"payload,omitempty"`
	Timestamp *float64 `json:"timestamp,omitempty"`
}

type SignalwireReauthenticateParams struct {
	Authentication map[string]any `json:"authentication,omitempty"`
	DpopToken      *string        `json:"dpop_token,omitempty"`
}

type CallingAiHoldResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingAiMessageResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingAiUnholdResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingAmazonBedrockResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingAnswerResult struct {
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingBeginResult struct {
	CallId      *string        `json:"call_id,omitempty"`
	Code        string         `json:"code,omitempty"`
	Data        map[string]any `json:"data,omitempty"`
	Message     *string        `json:"message,omitempty"`
	MessageData map[string]any `json:"message_data,omitempty"`
	NodeId      *string        `json:"node_id,omitempty"`
}

type CallingBindDigitResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingCallResult map[string]any

type CallingClearDigitBindingsResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingCollectResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingCollectStartInputTimersResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingCollectStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingConnectResult struct {
	Code        string         `json:"code,omitempty"`
	Data        map[string]any `json:"data,omitempty"`
	Message     *string        `json:"message,omitempty"`
	MessageData map[string]any `json:"message_data,omitempty"`
}

type CallingDenoiseResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingDenoiseStopResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingDetectResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingDetectStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingDialResult struct {
	Code        string         `json:"code,omitempty"`
	Data        map[string]any `json:"data,omitempty"`
	Message     *string        `json:"message,omitempty"`
	MessageData map[string]any `json:"message_data,omitempty"`
}

type CallingDisconnectResult struct {
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingEchoResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingEndResult struct {
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingJoinConferenceResult struct {
	CallId       *string        `json:"call_id,omitempty"`
	Code         string         `json:"code,omitempty"`
	ConferenceId *string        `json:"conference_id,omitempty"`
	Data         map[string]any `json:"data,omitempty"`
	Message      *string        `json:"message,omitempty"`
}

type CallingJoinRoomResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingLeaveConferenceResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingLeaveRoomResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingLiveTranscribeResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingLiveTranslateResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingPassResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingPayResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPayStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPlayPauseResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPlayResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPlayResumeResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPlayStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPlayVolumeResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPlayAndCollectResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPlayAndCollectStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingPlayAndCollectVolumeResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingQueueEnterResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingQueueLeaveResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingReceiveResult struct {
	Code    string  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

type CallingReceiveFaxResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingReceiveFaxStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingRecordPauseResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingRecordResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
	Url       *string        `json:"url,omitempty"`
}

type CallingRecordResumeResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingRecordStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingReferResult struct {
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingSendDigitsResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingSendFaxResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingSendFaxStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingStreamResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingStreamStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingTapResult struct {
	CallId       *string        `json:"call_id,omitempty"`
	Code         string         `json:"code,omitempty"`
	ControlId    *string        `json:"control_id,omitempty"`
	Data         map[string]any `json:"data,omitempty"`
	Message      *string        `json:"message,omitempty"`
	SourceDevice map[string]any `json:"source_device,omitempty"`
}

type CallingTapStopResult struct {
	CallId    *string        `json:"call_id,omitempty"`
	Code      string         `json:"code,omitempty"`
	ControlId *string        `json:"control_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Message   *string        `json:"message,omitempty"`
}

type CallingTransferResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type CallingUserEventResult struct {
	CallId  *string        `json:"call_id,omitempty"`
	Code    string         `json:"code,omitempty"`
	Data    map[string]any `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

type MessagingSendResult struct {
	Code      string  `json:"code,omitempty"`
	Message   *string `json:"message,omitempty"`
	MessageId string  `json:"message_id,omitempty"`
}

type SignalwireConnectResult struct {
	Accesses             []map[string]any `json:"accesses,omitempty"`
	Authorization        map[string]any   `json:"authorization,omitempty"`
	Authorizations       []map[string]any `json:"authorizations,omitempty"`
	Host                 *string          `json:"host,omitempty"`
	IceServers           []map[string]any `json:"ice_servers,omitempty"`
	Identity             *string          `json:"identity,omitempty"`
	MasterNodeid         string           `json:"master_nodeid,omitempty"`
	Nodeid               string           `json:"nodeid,omitempty"`
	Protocol             *string          `json:"protocol,omitempty"`
	Protocols            []map[string]any `json:"protocols,omitempty"`
	ProtocolsUncertified []string         `json:"protocols_uncertified,omitempty"`
	Result               map[string]any   `json:"result,omitempty"`
	SessionRestored      bool             `json:"session_restored,omitempty"`
	Sessionid            string           `json:"sessionid,omitempty"`
	Subscriptions        []map[string]any `json:"subscriptions,omitempty"`
}

type SignalwireDisconnectResult map[string]any

type SignalwireExecuteResult struct {
	RequesterNodeid string         `json:"requester_nodeid,omitempty"`
	ResponderNodeid string         `json:"responder_nodeid,omitempty"`
	Result          map[string]any `json:"result,omitempty"`
}

type SignalwirePingResult struct {
	Payload   *string  `json:"payload,omitempty"`
	Timestamp *float64 `json:"timestamp,omitempty"`
}

type SignalwireReauthenticateResult struct {
	Authentication *string          `json:"authentication,omitempty"`
	Authorization  map[string]any   `json:"authorization,omitempty"`
	IceServers     []map[string]any `json:"ice_servers,omitempty"`
	Result         map[string]any   `json:"result,omitempty"`
}
