package swml

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"regexp"
	"strings"
	"sync"

	"github.com/signalwire/signalwire-go/pkg/logging"
)

var swaigFnNameRe = regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_]*$`)

// ToolHandler is the function signature for a registered SWAIG tool.
// Returns a result that will be JSON-encoded as the SWAIG response.
type ToolHandler func(args map[string]any, rawData map[string]any) any

// ToolDefinition is a SWAIG tool registered on the Service.
type ToolDefinition struct {
	Name        string
	Description string
	Parameters  map[string]any
	Handler     ToolHandler
	Secure      bool
}

// RoutingCallback is a function called on incoming requests to customize responses.
// It receives the request and request body, and returns an optional SWML JSON override.
// If it returns nil, the default document is used.
type RoutingCallback func(r *http.Request, body map[string]any) map[string]any

// Service is the base SWML service that manages documents, HTTP endpoints, and auth.
// It provides auto-vivified verb methods driven by the SWML schema.
type Service struct {
	mu sync.RWMutex

	Name   string
	Route  string
	Host   string
	Port   int
	Logger *logging.Logger

	// Auth
	basicAuthUser     string
	basicAuthPassword string
	// basicAuthAutoGenerated is set to true when the password was neither
	// provided explicitly nor sourced from SWML_BASIC_AUTH_PASSWORD. The
	// constructor logs a warning in that case so external callers know why
	// they are getting HTTP 401.
	basicAuthAutoGenerated bool

	// SWML document
	document *Document

	// Schema for verb validation
	schema *Schema

	// Proxy detection
	proxyURLBase string

	// Routing callbacks
	routingCallbacks map[string]RoutingCallback

	// SWAIG tool registry — lifted from AgentBase so any Service (sidecar,
	// non-agent verb host) can register and dispatch SWAIG functions.
	tools     map[string]*ToolDefinition
	toolOrder []string

	// Server state
	server  *http.Server
	running bool

	// Verb method cache: maps verb name to whether it exists in schema
	verbCache map[string]bool
}

// ServiceOption is a functional option for configuring a Service.
type ServiceOption func(*Service)

// WithName sets the service name.
func WithName(name string) ServiceOption {
	return func(s *Service) { s.Name = name }
}

// WithRoute sets the HTTP route path.
func WithRoute(route string) ServiceOption {
	return func(s *Service) { s.Route = strings.TrimRight(route, "/") }
}

// WithHost sets the HTTP server bind host.
func WithHost(host string) ServiceOption {
	return func(s *Service) { s.Host = host }
}

// WithPort sets the HTTP server port.
func WithPort(port int) ServiceOption {
	return func(s *Service) { s.Port = port }
}

// WithBasicAuth sets explicit basic auth credentials.
func WithBasicAuth(user, password string) ServiceOption {
	return func(s *Service) {
		s.basicAuthUser = user
		s.basicAuthPassword = password
	}
}

// NewService creates a new SWML service with the given options.
func NewService(opts ...ServiceOption) *Service {
	s := &Service{
		Name:             "SWML",
		Route:            "/",
		Host:             "0.0.0.0",
		Port:             3000,
		Logger:           logging.New("swml-service"),
		document:         NewDocument(),
		routingCallbacks: make(map[string]RoutingCallback),
		tools:            make(map[string]*ToolDefinition),
		verbCache:        make(map[string]bool),
	}

	// Apply options
	for _, opt := range opts {
		opt(s)
	}

	// Port from env if not explicitly set
	if envPort := os.Getenv("PORT"); envPort != "" {
		var port int
		if _, err := fmt.Sscanf(envPort, "%d", &port); err == nil {
			s.Port = port
		}
	}

	// Auth from env if not explicitly set
	if s.basicAuthUser == "" {
		s.basicAuthUser = os.Getenv("SWML_BASIC_AUTH_USER")
	}
	if s.basicAuthPassword == "" {
		s.basicAuthPassword = os.Getenv("SWML_BASIC_AUTH_PASSWORD")
	}
	// Auto-generate if still empty
	if s.basicAuthUser == "" {
		s.basicAuthUser = s.Name
	}
	if s.basicAuthPassword == "" {
		s.basicAuthPassword = generatePassword()
		s.basicAuthAutoGenerated = true
		// Warn loudly so external callers (tests, RPC clients, MCP) know
		// why they are getting HTTP 401. This is the silent cause of every
		// external caller failing when .env wasn't loaded.
		s.Logger.Warn(
			"basic_auth_password_autogenerated: username=%q. "+
				"No SWML_BASIC_AUTH_PASSWORD found in environment and no "+
				"password passed via WithBasicAuth. The SDK generated a "+
				"random password that exists only in this process; external "+
				"callers will get HTTP 401 unless they read the value from "+
				"this process's env. To fix, set SWML_BASIC_AUTH_USER and "+
				"SWML_BASIC_AUTH_PASSWORD in your environment, or pass "+
				"swml.WithBasicAuth(user, pass) / agent.WithBasicAuth(...) "+
				"when constructing the service.",
			s.basicAuthUser,
		)
	}

	// Proxy URL from env
	s.proxyURLBase = os.Getenv("SWML_PROXY_URL_BASE")

	// Load schema
	schema, err := GetSchema()
	if err != nil {
		s.Logger.Warn("failed to load SWML schema: %s", err)
	} else {
		s.schema = schema
		s.Logger.Debug("loaded schema with %d verbs", schema.VerbCount())
	}

	return s
}

// generatePassword creates a random password for auto-generated basic auth.
// Panics if the system has no entropy source — never fall back to a weak password.
func generatePassword() string {
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		panic("crypto/rand failed: cannot generate secure password: " + err.Error())
	}
	return hex.EncodeToString(bytes)
}

// GetDocument returns the current SWML document.
func (s *Service) GetDocument() *Document {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.document
}

// ResetDocument resets the SWML document to empty.
func (s *Service) ResetDocument() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.document = NewDocument()
}

// GetBasicAuthCredentials returns the (username, password) for basic auth.
func (s *Service) GetBasicAuthCredentials() (string, string) {
	return s.basicAuthUser, s.basicAuthPassword
}

// --- Schema-driven verb methods ---

// ExecuteVerb adds any SWML verb to the document, validated against the schema.
// This is the core method that all verb convenience methods delegate to.
// For most verbs, config should be a map[string]any of verb parameters.
// For "sleep", config should be an integer (milliseconds).
func (s *Service) ExecuteVerb(verbName string, config any) error {
	if s.schema != nil && !s.schema.IsValidVerb(verbName) {
		return fmt.Errorf("unknown SWML verb: %q", verbName)
	}
	return s.document.AddVerb(verbName, config)
}

// ExecuteVerbToSection adds a SWML verb to a named section.
func (s *Service) ExecuteVerbToSection(section, verbName string, config any) error {
	if s.schema != nil && !s.schema.IsValidVerb(verbName) {
		return fmt.Errorf("unknown SWML verb: %q", verbName)
	}
	return s.document.AddVerbToSection(section, verbName, config)
}

// --- Auto-vivified convenience methods for all 38 SWML verbs ---
// These are generated from the schema verb list. The AI verb is included here
// but AgentBase will override it with its own implementation.

// Answer adds the answer verb to the document.
func (s *Service) Answer(config map[string]any) error {
	return s.ExecuteVerb("answer", filterNilValues(config))
}

// Hangup adds the hangup verb.
func (s *Service) Hangup(config map[string]any) error {
	return s.ExecuteVerb("hangup", filterNilValues(config))
}

// Play adds the play verb.
func (s *Service) Play(config map[string]any) error {
	return s.ExecuteVerb("play", filterNilValues(config))
}

// Record adds the record verb.
func (s *Service) Record(config map[string]any) error {
	return s.ExecuteVerb("record", filterNilValues(config))
}

// RecordCall adds the record_call verb.
func (s *Service) RecordCall(config map[string]any) error {
	return s.ExecuteVerb("record_call", filterNilValues(config))
}

// StopRecordCall adds the stop_record_call verb.
func (s *Service) StopRecordCall(config map[string]any) error {
	return s.ExecuteVerb("stop_record_call", filterNilValues(config))
}

// Sleep adds the sleep verb. Duration is in milliseconds.
func (s *Service) Sleep(duration int) error {
	return s.ExecuteVerb("sleep", duration)
}

// Connect adds the connect verb.
func (s *Service) Connect(config map[string]any) error {
	return s.ExecuteVerb("connect", filterNilValues(config))
}

// SendDigits adds the send_digits verb.
func (s *Service) SendDigits(config map[string]any) error {
	return s.ExecuteVerb("send_digits", filterNilValues(config))
}

// SendSMS adds the send_sms verb.
func (s *Service) SendSMS(config map[string]any) error {
	return s.ExecuteVerb("send_sms", filterNilValues(config))
}

// SendFax adds the send_fax verb.
func (s *Service) SendFax(config map[string]any) error {
	return s.ExecuteVerb("send_fax", filterNilValues(config))
}

// ReceiveFax adds the receive_fax verb.
func (s *Service) ReceiveFax(config map[string]any) error {
	return s.ExecuteVerb("receive_fax", filterNilValues(config))
}

// SIPRefer adds the sip_refer verb.
func (s *Service) SIPRefer(config map[string]any) error {
	return s.ExecuteVerb("sip_refer", filterNilValues(config))
}

// AI adds the ai verb. AgentBase overrides this with its own AI rendering.
func (s *Service) AI(config map[string]any) error {
	return s.ExecuteVerb("ai", filterNilValues(config))
}

// AmazonBedrock adds the amazon_bedrock verb.
func (s *Service) AmazonBedrock(config map[string]any) error {
	return s.ExecuteVerb("amazon_bedrock", filterNilValues(config))
}

// Cond adds the cond verb (conditional logic).
func (s *Service) Cond(config map[string]any) error {
	return s.ExecuteVerb("cond", filterNilValues(config))
}

// Switch adds the switch verb.
func (s *Service) Switch(config map[string]any) error {
	return s.ExecuteVerb("switch", filterNilValues(config))
}

// Execute adds the execute verb (run another SWML section).
func (s *Service) Execute(config map[string]any) error {
	return s.ExecuteVerb("execute", filterNilValues(config))
}

// Return adds the return verb.
func (s *Service) Return(config map[string]any) error {
	return s.ExecuteVerb("return", filterNilValues(config))
}

// Goto adds the goto verb.
func (s *Service) Goto(config map[string]any) error {
	return s.ExecuteVerb("goto", filterNilValues(config))
}

// Label adds the label verb.
func (s *Service) Label(config map[string]any) error {
	return s.ExecuteVerb("label", filterNilValues(config))
}

// Set adds the set verb (set variables).
func (s *Service) Set(config map[string]any) error {
	return s.ExecuteVerb("set", filterNilValues(config))
}

// Unset adds the unset verb.
func (s *Service) Unset(config map[string]any) error {
	return s.ExecuteVerb("unset", filterNilValues(config))
}

// Transfer adds the transfer verb.
func (s *Service) Transfer(config map[string]any) error {
	return s.ExecuteVerb("transfer", filterNilValues(config))
}

// Tap adds the tap verb (media tapping).
func (s *Service) Tap(config map[string]any) error {
	return s.ExecuteVerb("tap", filterNilValues(config))
}

// StopTap adds the stop_tap verb.
func (s *Service) StopTap(config map[string]any) error {
	return s.ExecuteVerb("stop_tap", filterNilValues(config))
}

// Denoise adds the denoise verb.
func (s *Service) Denoise(config map[string]any) error {
	return s.ExecuteVerb("denoise", filterNilValues(config))
}

// StopDenoise adds the stop_denoise verb.
func (s *Service) StopDenoise(config map[string]any) error {
	return s.ExecuteVerb("stop_denoise", filterNilValues(config))
}

// JoinRoom adds the join_room verb.
func (s *Service) JoinRoom(config map[string]any) error {
	return s.ExecuteVerb("join_room", filterNilValues(config))
}

// JoinConference adds the join_conference verb.
func (s *Service) JoinConference(config map[string]any) error {
	return s.ExecuteVerb("join_conference", filterNilValues(config))
}

// Prompt adds the prompt verb.
func (s *Service) Prompt(config map[string]any) error {
	return s.ExecuteVerb("prompt", filterNilValues(config))
}

// EnterQueue adds the enter_queue verb.
func (s *Service) EnterQueue(config map[string]any) error {
	return s.ExecuteVerb("enter_queue", filterNilValues(config))
}

// Request adds the request verb (HTTP request).
func (s *Service) Request(config map[string]any) error {
	return s.ExecuteVerb("request", filterNilValues(config))
}

// Pay adds the pay verb.
func (s *Service) Pay(config map[string]any) error {
	return s.ExecuteVerb("pay", filterNilValues(config))
}

// DetectMachine adds the detect_machine verb.
func (s *Service) DetectMachine(config map[string]any) error {
	return s.ExecuteVerb("detect_machine", filterNilValues(config))
}

// LiveTranscribe adds the live_transcribe verb.
func (s *Service) LiveTranscribe(config map[string]any) error {
	return s.ExecuteVerb("live_transcribe", filterNilValues(config))
}

// LiveTranslate adds the live_translate verb.
func (s *Service) LiveTranslate(config map[string]any) error {
	return s.ExecuteVerb("live_translate", filterNilValues(config))
}

// UserEvent adds the user_event verb.
func (s *Service) UserEvent(config map[string]any) error {
	return s.ExecuteVerb("user_event", filterNilValues(config))
}

// --- HTTP server ---

// GetFullURL returns the full URL for this service including auth.
//
// Base URL resolution order:
//  1. SWML_PROXY_URL_BASE (explicit proxy override — always wins)
//  2. Platform-specific base derived from GetExecutionMode() when running
//     inside a serverless runtime (currently AWS Lambda)
//  3. Local http://host:port base (default server mode)
//
// In every branch the agent's Route is appended to the base. Callers that
// need to serve SWAIG / post_prompt endpoints then append further path
// segments onto the result. This invariant is load-bearing: a Lambda-hosted
// agent at route "/my-agent" must emit SWAIG URLs like
// "https://xxx.lambda-url.us-east-1.on.aws/my-agent/swaig" — NOT
// "https://xxx.lambda-url.us-east-1.on.aws/swaig". See buildWebhookURL in
// pkg/agent/agent.go for the defensive HasSuffix re-check that enforces the
// same property downstream.
func (s *Service) GetFullURL(includeAuth bool) string {
	if s.proxyURLBase != "" {
		base := strings.TrimRight(s.proxyURLBase, "/")
		if includeAuth {
			return insertAuth(base, s.basicAuthUser, s.basicAuthPassword) + s.Route
		}
		return base + s.Route
	}

	if base := platformBaseURL(GetExecutionMode()); base != "" {
		if includeAuth {
			return insertAuth(base, s.basicAuthUser, s.basicAuthPassword) + s.Route
		}
		return base + s.Route
	}

	scheme := "http"
	host := s.Host
	if host == "0.0.0.0" {
		host = "localhost"
	}
	base := fmt.Sprintf("%s://%s:%d", scheme, host, s.Port)
	if includeAuth {
		return insertAuth(base, s.basicAuthUser, s.basicAuthPassword) + s.Route
	}
	return base + s.Route
}

// platformBaseURL returns a serverless-platform-specific base URL (scheme +
// host, no path) for the given execution mode, or the empty string if the
// mode has no platform override. Callers concatenate Route onto the result.
func platformBaseURL(mode ExecutionMode) string {
	switch mode {
	case ModeLambda:
		return lambdaBaseURL()
	default:
		return ""
	}
}

// RegisterRoutingCallback registers a callback for a specific path.
func (s *Service) RegisterRoutingCallback(path string, cb RoutingCallback) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.routingCallbacks[path] = cb
}

// OnRequest generates the SWML response for an incoming request.
// It checks routing callbacks first, then returns the default document.
func (s *Service) OnRequest(requestData map[string]any, callbackPath string) map[string]any {
	s.mu.RLock()
	defer s.mu.RUnlock()

	// Check routing callbacks
	if callbackPath != "" {
		if cb, ok := s.routingCallbacks[callbackPath]; ok {
			result := cb(nil, requestData)
			if result != nil {
				return result
			}
		}
	}

	return s.document.ToMap()
}

// Render returns the SWML document as a JSON string.
func (s *Service) Render() (string, error) {
	return s.document.Render()
}

// RenderPretty returns the SWML document as an indented JSON string.
func (s *Service) RenderPretty() (string, error) {
	return s.document.RenderPretty()
}

// ExtractSIPUsername extracts a SIP username from a request body.
func ExtractSIPUsername(body map[string]any) string {
	// Look in call.to field for SIP URI
	callData, ok := body["call"].(map[string]any)
	if !ok {
		return ""
	}
	to, ok := callData["to"].(string)
	if !ok {
		return ""
	}
	// Parse SIP URI: sip:username@domain
	if strings.HasPrefix(to, "sip:") {
		to = to[4:]
	}
	if idx := strings.Index(to, "@"); idx > 0 {
		return to[:idx]
	}
	return to
}

// --- Helpers ---

// filterNilValues removes nil values from a map, matching Python's behavior
// of skipping None kwargs in verb methods.
func filterNilValues(m map[string]any) map[string]any {
	if m == nil {
		return map[string]any{}
	}
	result := make(map[string]any, len(m))
	for k, v := range m {
		if v != nil {
			result[k] = v
		}
	}
	return result
}

// insertAuth inserts basic auth credentials into a URL.
func insertAuth(baseURL, user, password string) string {
	// Insert user:pass@ after the scheme://
	if idx := strings.Index(baseURL, "://"); idx >= 0 {
		scheme := baseURL[:idx+3]
		rest := baseURL[idx+3:]
		return fmt.Sprintf("%s%s:%s@%s", scheme, user, password, rest)
	}
	return baseURL
}

// Serve starts the HTTP server. This is a blocking call.
func (s *Service) Serve() error {
	mux := s.buildMux()

	s.mu.Lock()
	s.server = &http.Server{
		Addr:    fmt.Sprintf("%s:%d", s.Host, s.Port),
		Handler: mux,
	}
	s.running = true
	s.mu.Unlock()

	s.Logger.Info("serving on %s:%d%s", s.Host, s.Port, s.Route)
	s.Logger.Info("auth user: %s", s.basicAuthUser)

	return s.server.ListenAndServe()
}

// Stop gracefully stops the HTTP server.
func (s *Service) Stop() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.server != nil {
		s.running = false
		return s.server.Close()
	}
	return nil
}

// buildMux creates the HTTP handler with auth middleware and routes.
func (s *Service) buildMux() *http.ServeMux {
	mux := http.NewServeMux()

	// Health endpoints (no auth)
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "healthy"})
	})
	mux.HandleFunc("/ready", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "ready"})
	})

	route := s.Route
	if route == "" {
		route = "/"
	}
	swaigPath := strings.TrimRight(route, "/") + "/swaig"

	// SWAIG endpoint (with auth) — GET returns SWML, POST dispatches a tool.
	mux.HandleFunc(swaigPath, s.withSecurity(s.handleSWAIG))

	// Subclass / additional routes hook (AgentBase wires /post_prompt etc).
	s.RegisterAdditionalRoutes(mux)

	// Main SWML endpoint (with auth)
	mux.HandleFunc(route, s.withSecurity(s.handleSWML))

	return mux
}

// RegisterAdditionalRoutes is an extension hook for subclasses (e.g.
// AgentBase) to mount additional routes (/post_prompt, /mcp). Default no-op.
// Composing types call this from their own buildMux equivalent.
func (s *Service) RegisterAdditionalRoutes(mux *http.ServeMux) {}

// ---------------------------------------------------------------------------
// SWAIG tool registry (lifted from AgentBase)
// ---------------------------------------------------------------------------

// DefineTool registers a SWAIG function the AI can call.
// Tool descriptions and parameter descriptions are LLM-facing prompt
// engineering — see PORTING_GUIDE for guidance.
func (s *Service) DefineTool(td *ToolDefinition) *Service {
	s.mu.Lock()
	defer s.mu.Unlock()
	if td == nil || td.Name == "" {
		return s
	}
	s.tools[td.Name] = td
	if !contains(s.toolOrder, td.Name) {
		s.toolOrder = append(s.toolOrder, td.Name)
	}
	return s
}

// RegisterSwaigFunction registers a raw SWAIG function definition (e.g.
// DataMap tools that have no local handler). The map must contain a
// "function" key giving the tool name.
func (s *Service) RegisterSwaigFunction(funcDef map[string]any) *Service {
	name, ok := funcDef["function"].(string)
	if !ok || name == "" {
		return s
	}
	td := &ToolDefinition{Name: name}
	if desc, ok := funcDef["description"].(string); ok {
		td.Description = desc
	}
	if params, ok := funcDef["parameters"].(map[string]any); ok {
		td.Parameters = params
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.tools[name] = td
	if !contains(s.toolOrder, name) {
		s.toolOrder = append(s.toolOrder, name)
	}
	return s
}

// OnFunctionCall dispatches a function call to the registered handler.
// Default implementation: looks up the tool in the registry and invokes
// its handler. Subclasses (AgentBase) may override at the type level by
// providing their own method (Go method dispatch is static — to override
// in a way that is callable through Service, use the SwaigPreDispatch
// extension hook to substitute a target).
func (s *Service) OnFunctionCall(name string, args, rawData map[string]any) any {
	s.mu.RLock()
	td, ok := s.tools[name]
	s.mu.RUnlock()
	if !ok || td == nil || td.Handler == nil {
		return map[string]any{"response": fmt.Sprintf("Function '%s' not found", name)}
	}
	return td.Handler(args, rawData)
}

// HasTool reports whether a tool with the given name has been registered.
func (s *Service) HasTool(name string) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	_, ok := s.tools[name]
	return ok
}

// ListToolNames returns the registered tool names in insertion order.
func (s *Service) ListToolNames() []string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]string, len(s.toolOrder))
	copy(out, s.toolOrder)
	return out
}

// SwaigPreDispatch is an extension hook invoked between argument parsing
// and function dispatch on POST /swaig. It returns a target Service to
// dispatch on (defaults to s) and an optional short-circuit response.
// Subclasses (AgentBase) override to add session-token validation or
// ephemeral dynamic-config copies.
func (s *Service) SwaigPreDispatch(requestData map[string]any, funcName string) (target *Service, shortCircuit map[string]any) {
	return s, nil
}

// RenderMainSwml is an extension hook invoked for the main route and for
// GET /swaig. Default returns the currently-built document. AgentBase
// overrides to render with prompts + dynamic config.
func (s *Service) RenderMainSwml(r *http.Request) map[string]any {
	return s.document.ToMap()
}

func contains(haystack []string, needle string) bool {
	for _, s := range haystack {
		if s == needle {
			return true
		}
	}
	return false
}

// handleSWAIG handles GET (returns SWML doc) and POST (dispatches a tool).
func (s *Service) handleSWAIG(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodGet {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(s.RenderMainSwml(r))
		return
	}

	// POST: parse body, validate, dispatch.
	r.Body = http.MaxBytesReader(w, r.Body, maxRequestBody)
	var payload map[string]any
	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"error": "Invalid JSON"})
		return
	}
	funcName, _ := payload["function"].(string)
	if funcName == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"error": "Missing function name"})
		return
	}
	if !swaigFnNameRe.MatchString(funcName) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"error": fmt.Sprintf("Invalid function name format: %q", funcName)})
		return
	}

	// Argument extraction: nested {argument:{parsed}} OR flat {arguments}
	args := map[string]any{}
	if argObj, ok := payload["argument"].(map[string]any); ok {
		if parsed, ok := argObj["parsed"].([]any); ok && len(parsed) > 0 {
			if first, ok := parsed[0].(map[string]any); ok {
				args = first
			}
		}
	} else if argMap, ok := payload["arguments"].(map[string]any); ok {
		args = argMap
	}

	target, shortCircuit := s.SwaigPreDispatch(payload, funcName)
	if shortCircuit != nil {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(shortCircuit)
		return
	}
	if target == nil {
		target = s
	}

	result := target.OnFunctionCall(funcName, args, payload)
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

// maxRequestBody is the maximum allowed request body size (1MB).
const maxRequestBody = 1 << 20

// handleSWML serves the SWML document.
func (s *Service) handleSWML(w http.ResponseWriter, r *http.Request) {
	var body map[string]any
	if r.Method == http.MethodPost {
		r.Body = http.MaxBytesReader(w, r.Body, maxRequestBody)
		json.NewDecoder(r.Body).Decode(&body)
	}

	// Skip if this is actually a /swaig request — the swaig handler will
	// claim it. (Go's mux matches longer prefixes first, but if route is
	// "/" and swaig path is "/swaig", the swaig handler wins for /swaig.
	// Defensive guard for nested-route cases.)
	swaigPath := strings.TrimRight(s.Route, "/") + "/swaig"
	if r.URL.Path == swaigPath {
		s.handleSWAIG(w, r)
		return
	}

	// Routing-callback hook keeps its existing semantics; if no callback
	// matched, fall through to the renderable document via the extension
	// point (AgentBase overrides RenderMainSwml).
	doc := s.OnRequest(body, r.URL.Path)
	if doc == nil || (len(doc) == 0) {
		doc = s.RenderMainSwml(r)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(doc)
}

// withSecurity wraps a handler with auth and security headers.
func (s *Service) withSecurity(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// Security headers
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("X-Frame-Options", "DENY")
		w.Header().Set("Cache-Control", "no-store")

		// Basic auth check (timing-safe comparison)
		user, pass, ok := r.BasicAuth()
		userMatch := subtle.ConstantTimeCompare([]byte(user), []byte(s.basicAuthUser)) == 1
		passMatch := subtle.ConstantTimeCompare([]byte(pass), []byte(s.basicAuthPassword)) == 1
		if !ok || !userMatch || !passMatch {
			w.Header().Set("WWW-Authenticate", `Basic realm="SWML Service"`)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}

		next(w, r)
	}
}
