package swml

import (
	"crypto/rand"
	"crypto/subtle"
	"crypto/tls"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"sync"

	"github.com/signalwire/signalwire-go/pkg/logging"
)

// RoutingCallback is a function called on incoming requests to customize responses.
// It receives the request and request body, and returns an optional SWML JSON override.
// If it returns nil, the default document is used.
type RoutingCallback func(r *http.Request, body map[string]any) map[string]any

// VerbHandler is the interface for custom SWML verb handlers.
// Implement this interface and pass instances to RegisterVerbHandler to
// add custom validation or build logic for a verb. This mirrors
// Python's SWMLVerbHandler interface.
type VerbHandler interface {
	// GetVerbName returns the SWML verb name this handler manages.
	GetVerbName() string
	// ValidateConfig validates a verb config map and returns (isValid, errorMessages).
	ValidateConfig(config map[string]any) (bool, []string)
	// BuildConfig constructs a verb config map from keyword-style options.
	BuildConfig(opts map[string]any) map[string]any
}

// SecurityConfig bundles configuration for all supported authentication methods:
// HTTP Basic Auth, Bearer token, and API key. Pass it to WithSecurityConfig to
// configure multiple auth methods in one call.
//
// Fields default to the zero value (disabled). Set only the fields you need.
//
//   - BasicAuthUser / BasicAuthPassword — HTTP Basic Auth credentials.
//   - BearerToken — Expected value of the "Authorization: Bearer <token>" header.
//   - APIKey — Expected API key value.
//   - APIKeyHeader — Header name to read the API key from (default "X-API-Key").
//
// Mirrors Python's SecurityConfig dataclass.
type SecurityConfig struct {
	BasicAuthUser     string
	BasicAuthPassword string
	BearerToken       string
	APIKey            string
	APIKeyHeader      string // defaults to "X-API-Key" when APIKey is set
}

// Service is the base SWML service that manages documents, HTTP endpoints, and auth.
// It provides auto-vivified verb methods driven by the SWML schema.
type Service struct {
	mu sync.RWMutex

	Name   string
	Route  string
	Host   string
	Port   int
	Domain string // Domain for TLS certificates and URL generation (SWML_DOMAIN env var)
	Logger *logging.Logger

	// Auth
	basicAuthUser     string
	basicAuthPassword string
	// basicAuthAutoGenerated is set to true when the password was neither
	// provided explicitly nor sourced from SWML_BASIC_AUTH_PASSWORD. The
	// constructor logs a warning in that case so external callers know why
	// they are getting HTTP 401.
	basicAuthAutoGenerated bool

	// Bearer token authentication (optional; empty = disabled)
	bearerToken string

	// API key authentication (optional; both must be set to enable)
	apiKey       string
	apiKeyHeader string // header name, e.g. "X-API-Key"

	// TLS / SSL
	tlsCertFile string // path to TLS certificate file
	tlsKeyFile  string // path to TLS key file

	// Schema validation
	// schemaValidation controls whether verb schema validation is active.
	// Mirrors Python's schema_validation constructor param and
	// SWML_SKIP_SCHEMA_VALIDATION=1 env var.
	schemaValidation bool
	// schemaPath is an optional override path for the schema JSON file.
	// When empty the embedded schema is used (default). Mirrors Python's
	// schema_path constructor parameter.
	schemaPath string

	// SWML document
	document *Document

	// Schema for verb validation
	schema *Schema

	// Custom verb handlers (name → handler). Checked before schema validation.
	verbHandlers map[string]VerbHandler

	// Proxy detection
	proxyURLBase string

	// Routing callbacks
	routingCallbacks map[string]RoutingCallback

	// Server state
	server  *http.Server
	running bool

	// Verb method cache: maps verb name to whether it exists in schema
	verbCache map[string]bool

	// verbHandlers holds pluggable handlers registered by callers for custom
	// or extended SWML verbs. Keyed by the verb name returned by VerbHandler.GetVerbName().
	verbHandlers map[string]VerbHandler
}

// ServiceOption is a functional option for configuring a Service.
type ServiceOption func(*Service)

// WithName sets the service name.
func WithName(name string) ServiceOption {
	return func(s *Service) { s.Name = name }
}

// WithRoute sets the HTTP route path.
func WithRoute(route string) ServiceOption {
	return func(s *Service) { s.Route = strings.TrimRight(route, "/") }
}

// WithHost sets the HTTP server bind host.
func WithHost(host string) ServiceOption {
	return func(s *Service) { s.Host = host }
}

// WithPort sets the HTTP server port.
func WithPort(port int) ServiceOption {
	return func(s *Service) { s.Port = port }
}

// WithBasicAuth sets explicit basic auth credentials.
func WithBasicAuth(user, password string) ServiceOption {
	return func(s *Service) {
		s.basicAuthUser = user
		s.basicAuthPassword = password
	}
}

// WithBearerToken configures Bearer token authentication. When set, the
// withSecurity middleware accepts requests carrying an
// "Authorization: Bearer <token>" header that matches token in addition to
// (or instead of) Basic Auth.
// Mirrors Python's SecurityConfig.bearer_token field and the AuthHandler
// verify_bearer_token / flask_decorator behaviour.
func WithBearerToken(token string) ServiceOption {
	return func(s *Service) { s.bearerToken = token }
}

// WithAPIKey configures API key authentication. When set, the withSecurity
// middleware accepts requests where the header named by header equals key.
// header is the HTTP header name (e.g. "X-API-Key"); pass an empty string to
// use the default "X-API-Key".
// Mirrors Python's SecurityConfig.api_key / api_key_header fields and the
// AuthHandler verify_api_key / flask_decorator behaviour.
func WithAPIKey(key, header string) ServiceOption {
	return func(s *Service) {
		s.apiKey = key
		if header == "" {
			header = "X-API-Key"
		}
		s.apiKeyHeader = header
	}
}

// WithSecurityConfig applies a SecurityConfig bundle, setting Basic Auth,
// Bearer token, and API key configuration in one call.
// This is the Go equivalent of Python's AuthHandler(security_config=...) pattern:
// it maps each SecurityConfig field to the corresponding WithXxx option.
func WithSecurityConfig(cfg SecurityConfig) ServiceOption {
	return func(s *Service) {
		if cfg.BasicAuthUser != "" {
			s.basicAuthUser = cfg.BasicAuthUser
		}
		if cfg.BasicAuthPassword != "" {
			s.basicAuthPassword = cfg.BasicAuthPassword
		}
		if cfg.BearerToken != "" {
			s.bearerToken = cfg.BearerToken
		}
		if cfg.APIKey != "" {
			s.apiKey = cfg.APIKey
			hdr := cfg.APIKeyHeader
			if hdr == "" {
				hdr = "X-API-Key"
			}
			s.apiKeyHeader = hdr
		}
	}
}

// WithTLS configures TLS for the service. When set, Serve() calls
// ListenAndServeTLS instead of ListenAndServe. Mirrors Python's
// ssl_cert / ssl_key serve() parameters and ssl_enabled property.
func WithTLS(certFile, keyFile string) ServiceOption {
	return func(s *Service) {
		s.tlsCertFile = certFile
		s.tlsKeyFile = keyFile
	}
}

// WithDomain sets the domain name used in URL generation when TLS is enabled.
// Mirrors Python's SecurityConfig.domain / SWML_DOMAIN env var.
func WithDomain(domain string) ServiceOption {
	return func(s *Service) { s.Domain = domain }
}

// WithSchemaPath overrides the schema file path used for verb validation.
// By default the embedded schema.json is used. Pass a custom path when testing
// or when deploying a modified schema alongside your binary.
// Mirrors Python's schema_path constructor parameter.
func WithSchemaPath(path string) ServiceOption {
	return func(s *Service) { s.schemaPath = path }
}

// WithConfigFile sets an optional configuration file path. In the Python
// SDK this loads a YAML/TOML file via SecurityConfig(config_file=...) which
// can supply ssl_enabled, ssl_cert_path, ssl_key_path, domain, and basic_auth.
// In Go the equivalent settings are passed via individual WithXxx options;
// WithConfigFile is retained for API parity and is a no-op in this release.
func WithConfigFile(_ string) ServiceOption {
	return func(_ *Service) {}
}

// WithSchemaValidation enables or disables SWML schema validation.
// Defaults to true (validation on). Set to false, or export
// SWML_SKIP_SCHEMA_VALIDATION=1, to bypass schema checks.
// Mirrors Python's schema_validation constructor parameter.
func WithSchemaValidation(enabled bool) ServiceOption {
	return func(s *Service) { s.schemaValidation = enabled }
}

// NewService creates a new SWML service with the given options.
func NewService(opts ...ServiceOption) *Service {
	s := &Service{
		Name:             "SWML",
		Route:            "/",
		Host:             "0.0.0.0",
		Port:             3000,
		Logger:           logging.New("swml-service"),
		document:         NewDocument(),
		routingCallbacks: make(map[string]RoutingCallback),
		verbCache:        make(map[string]bool),
		verbHandlers:     make(map[string]VerbHandler),
		// Schema validation is on by default (matches Python default True).
		// Can be overridden by WithSchemaValidation(false) or
		// SWML_SKIP_SCHEMA_VALIDATION=1.
		schemaValidation: true,
	}

	// Apply options
	for _, opt := range opts {
		opt(s)
	}

	// Honour SWML_SKIP_SCHEMA_VALIDATION=1 env var (mirrors Python behaviour).
	if os.Getenv("SWML_SKIP_SCHEMA_VALIDATION") == "1" {
		s.schemaValidation = false
	}

	// TLS domain from env (mirrors Python's SWML_DOMAIN / SecurityConfig.domain).
	if s.Domain == "" {
		s.Domain = os.Getenv("SWML_DOMAIN")
	}
	// TLS cert/key from env when not set via WithTLS (mirrors SWML_SSL_CERT_PATH / SWML_SSL_KEY_PATH).
	if s.tlsCertFile == "" {
		s.tlsCertFile = os.Getenv("SWML_SSL_CERT_PATH")
	}
	if s.tlsKeyFile == "" {
		s.tlsKeyFile = os.Getenv("SWML_SSL_KEY_PATH")
	}

	// Port from env if not explicitly set
	if envPort := os.Getenv("PORT"); envPort != "" {
		var port int
		if _, err := fmt.Sscanf(envPort, "%d", &port); err == nil {
			s.Port = port
		}
	}

	// Auth from env if not explicitly set
	if s.basicAuthUser == "" {
		s.basicAuthUser = os.Getenv("SWML_BASIC_AUTH_USER")
	}
	if s.basicAuthPassword == "" {
		s.basicAuthPassword = os.Getenv("SWML_BASIC_AUTH_PASSWORD")
	}
	// Auto-generate if still empty
	if s.basicAuthUser == "" {
		s.basicAuthUser = s.Name
	}
	if s.basicAuthPassword == "" {
		s.basicAuthPassword = generatePassword()
		s.basicAuthAutoGenerated = true
		// Warn loudly so external callers (tests, RPC clients, MCP) know
		// why they are getting HTTP 401. This is the silent cause of every
		// external caller failing when .env wasn't loaded.
		s.Logger.Warn(
			"basic_auth_password_autogenerated: username=%q. "+
				"No SWML_BASIC_AUTH_PASSWORD found in environment and no "+
				"password passed via WithBasicAuth. The SDK generated a "+
				"random password that exists only in this process; external "+
				"callers will get HTTP 401 unless they read the value from "+
				"this process's env. To fix, set SWML_BASIC_AUTH_USER and "+
				"SWML_BASIC_AUTH_PASSWORD in your environment, or pass "+
				"swml.WithBasicAuth(user, pass) / agent.WithBasicAuth(...) "+
				"when constructing the service.",
			s.basicAuthUser,
		)
	}

	// Proxy URL from env
	s.proxyURLBase = os.Getenv("SWML_PROXY_URL_BASE")

	// Load schema — only when validation is enabled.
	if s.schemaValidation {
		var schema *Schema
		var err error
		if s.schemaPath != "" {
			schema, err = LoadSchemaFromFile(s.schemaPath)
		} else {
			schema, err = GetSchema()
		}
		if err != nil {
			s.Logger.Warn("failed to load SWML schema: %s", err)
		} else {
			s.schema = schema
			s.Logger.Debug("loaded schema with %d verbs", schema.VerbCount())
		}
	}

	// Register built-in verb handlers (mirrors Python VerbHandlerRegistry.__init__).
	s.RegisterVerbHandler(NewAIVerbHandler())

	return s
}

// generatePassword creates a random password for auto-generated basic auth.
// Panics if the system has no entropy source — never fall back to a weak password.
func generatePassword() string {
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		panic("crypto/rand failed: cannot generate secure password: " + err.Error())
	}
	return hex.EncodeToString(bytes)
}

// GetDocument returns the current SWML document.
func (s *Service) GetDocument() *Document {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.document
}

// ResetDocument resets the SWML document to empty.
func (s *Service) ResetDocument() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.document = NewDocument()
}

// GetBasicAuthCredentials returns the (username, password) for basic auth.
func (s *Service) GetBasicAuthCredentials() (string, string) {
	return s.basicAuthUser, s.basicAuthPassword
}

// GetBasicAuthCredentialsWithSource returns (username, password, source) where
// source is one of "environment", "explicit", or "auto-generated".
// Mirrors Python's get_basic_auth_credentials(include_source=True) three-tuple return.
func (s *Service) GetBasicAuthCredentialsWithSource() (string, string, string) {
	user := s.basicAuthUser
	pass := s.basicAuthPassword

	envUser := os.Getenv("SWML_BASIC_AUTH_USER")
	envPass := os.Getenv("SWML_BASIC_AUTH_PASSWORD")

	var source string
	switch {
	case s.basicAuthAutoGenerated:
		source = "auto-generated"
	case envUser != "" && envPass != "" && envUser == user && envPass == pass:
		source = "environment"
	default:
		source = "explicit"
	}
	return user, pass, source
}

// VerifyBasicAuth performs a timing-safe comparison of the supplied credentials
// against the service's configured basic auth username and password.
// Returns true when both username and password match.
//
// This exposes the same check that withSecurity applies inside the HTTP
// middleware, making auth testable in isolation without an HTTP round-trip.
// Mirrors Python AuthHandler.verify_basic_auth(credentials) -> bool using
// secrets.compare_digest (equivalent: crypto/subtle.ConstantTimeCompare).
func (s *Service) VerifyBasicAuth(username, password string) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	userMatch := subtle.ConstantTimeCompare([]byte(username), []byte(s.basicAuthUser)) == 1
	passMatch := subtle.ConstantTimeCompare([]byte(password), []byte(s.basicAuthPassword)) == 1
	return userMatch && passMatch
}

// VerifyBearerToken performs a timing-safe comparison of the supplied token
// against the service's configured bearer token.
// Returns false when no bearer token is configured (i.e. WithBearerToken was
// not called).
//
// Callers typically extract the token from the "Authorization: Bearer <token>"
// header before calling this method.
// Mirrors Python AuthHandler.verify_bearer_token(credentials) -> bool.
func (s *Service) VerifyBearerToken(token string) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.bearerToken == "" {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(token), []byte(s.bearerToken)) == 1
}

// VerifyAPIKey performs a timing-safe comparison of the supplied key value
// against the service's configured API key.
// Returns false when no API key is configured (i.e. WithAPIKey was not called).
//
// Callers typically read the key from the header returned by APIKeyHeader().
// Mirrors Python AuthHandler.verify_api_key(api_key: str) -> bool.
func (s *Service) VerifyAPIKey(key string) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.apiKey == "" {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(key), []byte(s.apiKey)) == 1
}

// GetAuthInfo returns a map describing every configured authentication method.
// The map mirrors the Python AuthHandler.get_auth_info() return value:
//
//   - "basic"   → {"enabled": true, "username": "<user>"}
//   - "bearer"  → {"enabled": true, "hint": "Use Authorization: Bearer <token>"}
//   - "api_key" → {"enabled": true, "header": "<hdr>", "hint": "Use <hdr>: <key>"}
//
// Only methods that are actively configured appear in the map. Basic auth is
// always present because the service always has a username/password (either
// explicit or auto-generated).
// Mirrors Python AuthHandler.get_auth_info() -> Dict[str, Any].
func (s *Service) GetAuthInfo() map[string]any {
	s.mu.RLock()
	defer s.mu.RUnlock()

	info := map[string]any{
		"basic": map[string]any{
			"enabled":  true,
			"username": s.basicAuthUser,
		},
	}

	if s.bearerToken != "" {
		info["bearer"] = map[string]any{
			"enabled": true,
			"hint":    "Use Authorization: Bearer <token>",
		}
	}

	if s.apiKey != "" {
		hdr := s.apiKeyHeader
		if hdr == "" {
			hdr = "X-API-Key"
		}
		info["api_key"] = map[string]any{
			"enabled": true,
			"header":  hdr,
			"hint":    "Use " + hdr + ": <key>",
		}
	}

	return info
}

// TLSEnabled reports whether TLS is configured for this service.
// Mirrors Python's ssl_enabled property on SWMLService.
func (s *Service) TLSEnabled() bool {
	return s.tlsCertFile != "" && s.tlsKeyFile != ""
}

// FullValidationEnabled reports whether schema validation is active.
// Returns true when a schema was successfully loaded and schemaValidation
// is on. Mirrors Python's full_validation_enabled property.
func (s *Service) FullValidationEnabled() bool {
	return s.schema != nil
}

// RegisterVerbHandler registers a custom VerbHandler for a specific verb.
// When a verb has a registered handler, its ValidateConfig is called instead
// of (or in addition to) schema validation. Mirrors Python's
// register_verb_handler(handler: SWMLVerbHandler).
func (s *Service) RegisterVerbHandler(handler VerbHandler) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.verbHandlers[handler.GetVerbName()] = handler
}

// AddSection adds a new named section to the SWML document.
// Returns false if the section already exists.
// Delegates to Document.AddSection. Mirrors Python's add_section method
// which was only on the Document in Go but is on SWMLService in Python.
func (s *Service) AddSection(name string) bool {
	return s.document.AddSection(name)
}

// AsRouter returns an http.Handler that serves this service's endpoints.
// Use this to embed the service in a custom HTTP mux or router.
// Mirrors Python's as_router() -> APIRouter method on SWMLService.
func (s *Service) AsRouter() http.Handler {
	return s.buildMux()
}

// ManualSetProxyUrl overrides the proxy URL base used for URL generation.
// Call this at runtime to set or update the proxy URL (e.g. an ngrok URL).
// Mirrors Python's manual_set_proxy_url(proxy_url: str) on SWMLService.
func (s *Service) ManualSetProxyUrl(url string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.proxyURLBase = strings.TrimRight(url, "/")
}

// --- Schema-driven verb methods ---

// ExecuteVerb adds any SWML verb to the document, validated against the schema
// and any registered VerbHandler. This is the core method that all verb
// convenience methods delegate to.
// For most verbs, config should be a map[string]any of verb parameters.
// For "sleep", config should be an integer (milliseconds).
func (s *Service) ExecuteVerb(verbName string, config any) error {
	// Custom handler check first (mirrors Python: verb_registry.has_handler priority).
	s.mu.RLock()
	handler, hasHandler := s.verbHandlers[verbName]
	s.mu.RUnlock()

	if hasHandler {
		if cfgMap, ok := config.(map[string]any); ok {
			if valid, errs := handler.ValidateConfig(cfgMap); !valid {
				return fmt.Errorf("verb %q handler validation failed: %s", verbName, strings.Join(errs, "; "))
			}
		}
	} else if s.schema != nil && !s.schema.IsValidVerb(verbName) {
		return fmt.Errorf("unknown SWML verb: %q", verbName)
	}
	return s.document.AddVerb(verbName, config)
}

// ExecuteVerbToSection adds a SWML verb to a named section.
func (s *Service) ExecuteVerbToSection(section, verbName string, config any) error {
	// Custom handler check first.
	s.mu.RLock()
	handler, hasHandler := s.verbHandlers[verbName]
	s.mu.RUnlock()

	if hasHandler {
		if cfgMap, ok := config.(map[string]any); ok {
			if valid, errs := handler.ValidateConfig(cfgMap); !valid {
				return fmt.Errorf("verb %q handler validation failed: %s", verbName, strings.Join(errs, "; "))
			}
		}
	} else if s.schema != nil && !s.schema.IsValidVerb(verbName) {
		return fmt.Errorf("unknown SWML verb: %q", verbName)
	}
	return s.document.AddVerbToSection(section, verbName, config)
}

// --- Auto-vivified convenience methods for all 38 SWML verbs ---
// These are generated from the schema verb list. The AI verb is included here
// but AgentBase will override it with its own implementation.

// Answer adds the answer verb to the document.
// maxDuration sets the maximum call duration in seconds (optional).
// codecs sets a comma-separated list of allowed codecs (optional).
// Mirrors Python SWMLBuilder.answer(max_duration, codecs).
func (s *Service) Answer(maxDuration *int, codecs *string) error {
	cfg := map[string]any{}
	if maxDuration != nil {
		cfg["max_duration"] = *maxDuration
	}
	if codecs != nil {
		cfg["codecs"] = *codecs
	}
	return s.ExecuteVerb("answer", cfg)
}

// Hangup adds the hangup verb.
// reason is an optional reason string for the hangup.
// Mirrors Python SWMLBuilder.hangup(reason).
func (s *Service) Hangup(reason *string) error {
	cfg := map[string]any{}
	if reason != nil {
		cfg["reason"] = *reason
	}
	return s.ExecuteVerb("hangup", cfg)
}

// Play adds the play verb.
// Exactly one of url or urls must be provided; providing both is an error.
// volume sets the playback volume (-40 to 40, optional).
// sayVoice, sayLanguage, sayGender configure text-to-speech (optional).
// autoAnswer controls whether to auto-answer the call (optional).
// Mirrors Python SWMLBuilder.play(url, urls, volume, say_voice, say_language, say_gender, auto_answer).
func (s *Service) Play(url *string, urls []string, volume *float64, sayVoice, sayLanguage, sayGender *string, autoAnswer *bool) error {
	if url == nil && len(urls) == 0 {
		return fmt.Errorf("Play: either url or urls must be provided")
	}
	if url != nil && len(urls) > 0 {
		return fmt.Errorf("Play: url and urls are mutually exclusive")
	}
	cfg := map[string]any{}
	if url != nil {
		cfg["url"] = *url
	} else {
		cfg["urls"] = urls
	}
	if volume != nil {
		cfg["volume"] = *volume
	}
	if sayVoice != nil {
		cfg["say_voice"] = *sayVoice
	}
	if sayLanguage != nil {
		cfg["say_language"] = *sayLanguage
	}
	if sayGender != nil {
		cfg["say_gender"] = *sayGender
	}
	if autoAnswer != nil {
		cfg["auto_answer"] = *autoAnswer
	}
	return s.ExecuteVerb("play", cfg)
}

// Say adds a play verb with a "say:" prefix for text-to-speech.
// voice, language, and gender configure the TTS voice (optional).
// volume sets the playback volume (-40 to 40, optional).
// Mirrors Python SWMLBuilder.say(text, voice, language, gender, volume).
func (s *Service) Say(text string, voice, language, gender *string, volume *float64) error {
	sayURL := "say:" + text
	return s.Play(&sayURL, nil, volume, voice, language, gender, nil)
}

// Record adds the record verb.
func (s *Service) Record(config map[string]any) error {
	return s.ExecuteVerb("record", filterNilValues(config))
}

// RecordCall adds the record_call verb.
func (s *Service) RecordCall(config map[string]any) error {
	return s.ExecuteVerb("record_call", filterNilValues(config))
}

// StopRecordCall adds the stop_record_call verb.
func (s *Service) StopRecordCall(config map[string]any) error {
	return s.ExecuteVerb("stop_record_call", filterNilValues(config))
}

// Sleep adds the sleep verb. Duration is in milliseconds.
func (s *Service) Sleep(duration int) error {
	return s.ExecuteVerb("sleep", duration)
}

// Connect adds the connect verb.
func (s *Service) Connect(config map[string]any) error {
	return s.ExecuteVerb("connect", filterNilValues(config))
}

// SendDigits adds the send_digits verb.
func (s *Service) SendDigits(config map[string]any) error {
	return s.ExecuteVerb("send_digits", filterNilValues(config))
}

// SendSMS adds the send_sms verb.
func (s *Service) SendSMS(config map[string]any) error {
	return s.ExecuteVerb("send_sms", filterNilValues(config))
}

// SendFax adds the send_fax verb.
func (s *Service) SendFax(config map[string]any) error {
	return s.ExecuteVerb("send_fax", filterNilValues(config))
}

// ReceiveFax adds the receive_fax verb.
func (s *Service) ReceiveFax(config map[string]any) error {
	return s.ExecuteVerb("receive_fax", filterNilValues(config))
}

// SIPRefer adds the sip_refer verb.
func (s *Service) SIPRefer(config map[string]any) error {
	return s.ExecuteVerb("sip_refer", filterNilValues(config))
}

// AI adds the ai verb. AgentBase overrides this with its own AI rendering.
// promptText and promptPOM are mutually exclusive; providing both is an error.
// promptText sets a plain-text prompt; promptPOM sets a structured POM prompt.
// postPrompt and postPromptURL configure post-prompt behavior (optional).
// swaig supplies SWAIG configuration (optional).
// extra is a map of additional AI parameters merged into the verb config (optional).
// Mirrors Python SWMLBuilder.ai(prompt_text, prompt_pom, post_prompt, post_prompt_url, swaig, **kwargs).
func (s *Service) AI(promptText *string, promptPOM []map[string]any, postPrompt, postPromptURL *string, swaig map[string]any, extra map[string]any) error {
	if promptText != nil && len(promptPOM) > 0 {
		return fmt.Errorf("AI: promptText and promptPOM are mutually exclusive")
	}
	cfg := map[string]any{}
	if promptText != nil {
		cfg["prompt"] = *promptText
	} else if len(promptPOM) > 0 {
		cfg["prompt"] = promptPOM
	}
	if postPrompt != nil {
		cfg["post_prompt"] = *postPrompt
	}
	if postPromptURL != nil {
		cfg["post_prompt_url"] = *postPromptURL
	}
	if swaig != nil {
		cfg["SWAIG"] = swaig
	}
	for k, v := range extra {
		cfg[k] = v
	}
	return s.ExecuteVerb("ai", cfg)
}

// AmazonBedrock adds the amazon_bedrock verb.
func (s *Service) AmazonBedrock(config map[string]any) error {
	return s.ExecuteVerb("amazon_bedrock", filterNilValues(config))
}

// Cond adds the cond verb (conditional logic).
func (s *Service) Cond(config map[string]any) error {
	return s.ExecuteVerb("cond", filterNilValues(config))
}

// Switch adds the switch verb.
func (s *Service) Switch(config map[string]any) error {
	return s.ExecuteVerb("switch", filterNilValues(config))
}

// Execute adds the execute verb (run another SWML section).
func (s *Service) Execute(config map[string]any) error {
	return s.ExecuteVerb("execute", filterNilValues(config))
}

// Return adds the return verb.
func (s *Service) Return(config map[string]any) error {
	return s.ExecuteVerb("return", filterNilValues(config))
}

// Goto adds the goto verb.
func (s *Service) Goto(config map[string]any) error {
	return s.ExecuteVerb("goto", filterNilValues(config))
}

// Label adds the label verb.
func (s *Service) Label(config map[string]any) error {
	return s.ExecuteVerb("label", filterNilValues(config))
}

// Set adds the set verb (set variables).
func (s *Service) Set(config map[string]any) error {
	return s.ExecuteVerb("set", filterNilValues(config))
}

// Unset adds the unset verb.
func (s *Service) Unset(config map[string]any) error {
	return s.ExecuteVerb("unset", filterNilValues(config))
}

// Transfer adds the transfer verb.
func (s *Service) Transfer(config map[string]any) error {
	return s.ExecuteVerb("transfer", filterNilValues(config))
}

// Tap adds the tap verb (media tapping).
func (s *Service) Tap(config map[string]any) error {
	return s.ExecuteVerb("tap", filterNilValues(config))
}

// StopTap adds the stop_tap verb.
func (s *Service) StopTap(config map[string]any) error {
	return s.ExecuteVerb("stop_tap", filterNilValues(config))
}

// Denoise adds the denoise verb.
func (s *Service) Denoise(config map[string]any) error {
	return s.ExecuteVerb("denoise", filterNilValues(config))
}

// StopDenoise adds the stop_denoise verb.
func (s *Service) StopDenoise(config map[string]any) error {
	return s.ExecuteVerb("stop_denoise", filterNilValues(config))
}

// JoinRoom adds the join_room verb.
func (s *Service) JoinRoom(config map[string]any) error {
	return s.ExecuteVerb("join_room", filterNilValues(config))
}

// JoinConference adds the join_conference verb.
func (s *Service) JoinConference(config map[string]any) error {
	return s.ExecuteVerb("join_conference", filterNilValues(config))
}

// Prompt adds the prompt verb.
func (s *Service) Prompt(config map[string]any) error {
	return s.ExecuteVerb("prompt", filterNilValues(config))
}

// EnterQueue adds the enter_queue verb.
func (s *Service) EnterQueue(config map[string]any) error {
	return s.ExecuteVerb("enter_queue", filterNilValues(config))
}

// Request adds the request verb (HTTP request).
func (s *Service) Request(config map[string]any) error {
	return s.ExecuteVerb("request", filterNilValues(config))
}

// Pay adds the pay verb.
func (s *Service) Pay(config map[string]any) error {
	return s.ExecuteVerb("pay", filterNilValues(config))
}

// DetectMachine adds the detect_machine verb.
func (s *Service) DetectMachine(config map[string]any) error {
	return s.ExecuteVerb("detect_machine", filterNilValues(config))
}

// LiveTranscribe adds the live_transcribe verb.
func (s *Service) LiveTranscribe(config map[string]any) error {
	return s.ExecuteVerb("live_transcribe", filterNilValues(config))
}

// LiveTranslate adds the live_translate verb.
func (s *Service) LiveTranslate(config map[string]any) error {
	return s.ExecuteVerb("live_translate", filterNilValues(config))
}

// UserEvent adds the user_event verb.
func (s *Service) UserEvent(config map[string]any) error {
	return s.ExecuteVerb("user_event", filterNilValues(config))
}

// --- HTTP server ---

// GetFullURL returns the full URL for this service including auth.
//
// Base URL resolution order:
//  1. SWML_PROXY_URL_BASE (explicit proxy override — always wins)
//  2. Platform-specific base derived from GetExecutionMode() when running
//     inside a serverless runtime (currently AWS Lambda)
//  3. Local http://host:port base (default server mode)
//
// In every branch the agent's Route is appended to the base. Callers that
// need to serve SWAIG / post_prompt endpoints then append further path
// segments onto the result. This invariant is load-bearing: a Lambda-hosted
// agent at route "/my-agent" must emit SWAIG URLs like
// "https://xxx.lambda-url.us-east-1.on.aws/my-agent/swaig" — NOT
// "https://xxx.lambda-url.us-east-1.on.aws/swaig". See buildWebhookURL in
// pkg/agent/agent.go for the defensive HasSuffix re-check that enforces the
// same property downstream.
func (s *Service) GetFullURL(includeAuth bool) string {
	if s.proxyURLBase != "" {
		base := strings.TrimRight(s.proxyURLBase, "/")
		if includeAuth {
			return insertAuth(base, s.basicAuthUser, s.basicAuthPassword) + s.Route
		}
		return base + s.Route
	}

	if base := platformBaseURL(GetExecutionMode()); base != "" {
		if includeAuth {
			return insertAuth(base, s.basicAuthUser, s.basicAuthPassword) + s.Route
		}
		return base + s.Route
	}

	// Choose scheme based on TLS configuration.
	scheme := "http"
	if s.TLSEnabled() {
		scheme = "https"
	}

	// Use domain when TLS + domain is set (mirrors Python's _get_base_url logic).
	host := s.Host
	if s.TLSEnabled() && s.Domain != "" {
		host = s.Domain
	} else if host == "0.0.0.0" {
		host = "localhost"
	}

	// Omit port for standard ports (443 for https, 80 for http).
	var base string
	if (scheme == "https" && s.Port == 443) || (scheme == "http" && s.Port == 80) {
		base = fmt.Sprintf("%s://%s", scheme, host)
	} else {
		base = fmt.Sprintf("%s://%s:%d", scheme, host, s.Port)
	}

	if includeAuth {
		return insertAuth(base, s.basicAuthUser, s.basicAuthPassword) + s.Route
	}
	return base + s.Route
}

// platformBaseURL returns a serverless-platform-specific base URL (scheme +
// host, no path) for the given execution mode, or the empty string if the
// mode has no platform override. Callers concatenate Route onto the result.
func platformBaseURL(mode ExecutionMode) string {
	switch mode {
	case ModeLambda:
		return lambdaBaseURL()
	default:
		return ""
	}
}

// RegisterRoutingCallback registers a callback for a specific path.
func (s *Service) RegisterRoutingCallback(path string, cb RoutingCallback) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.routingCallbacks[path] = cb
}

// OnRequest generates the SWML response for an incoming request.
// It checks routing callbacks first, then returns the default document.
//
// The return value is a pointer to allow subclasses (AgentBase) to signal
// "no override" by returning nil — matching Python's Optional[dict] return
// type for on_request. Callers should treat a nil return as "use the default
// document unchanged".
func (s *Service) OnRequest(requestData map[string]any, callbackPath string) map[string]any {
	s.mu.RLock()
	defer s.mu.RUnlock()

	// Check routing callbacks
	if callbackPath != "" {
		if cb, ok := s.routingCallbacks[callbackPath]; ok {
			result := cb(nil, requestData)
			if result != nil {
				return result
			}
		}
	}

	return s.document.ToMap()
}

// Render returns the SWML document as a JSON string.
func (s *Service) Render() (string, error) {
	return s.document.Render()
}

// RenderPretty returns the SWML document as an indented JSON string.
func (s *Service) RenderPretty() (string, error) {
	return s.document.RenderPretty()
}

// ExtractSIPUsername extracts a SIP username from a request body.
func ExtractSIPUsername(body map[string]any) string {
	// Look in call.to field for SIP URI
	callData, ok := body["call"].(map[string]any)
	if !ok {
		return ""
	}
	to, ok := callData["to"].(string)
	if !ok {
		return ""
	}
	// Parse SIP URI: sip:username@domain
	if strings.HasPrefix(to, "sip:") {
		to = to[4:]
	}
	if idx := strings.Index(to, "@"); idx > 0 {
		return to[:idx]
	}
	return to
}

// --- Helpers ---

// filterNilValues removes nil values from a map, matching Python's behavior
// of skipping None kwargs in verb methods.
func filterNilValues(m map[string]any) map[string]any {
	if m == nil {
		return map[string]any{}
	}
	result := make(map[string]any, len(m))
	for k, v := range m {
		if v != nil {
			result[k] = v
		}
	}
	return result
}

// insertAuth inserts basic auth credentials into a URL.
func insertAuth(baseURL, user, password string) string {
	// Insert user:pass@ after the scheme://
	if idx := strings.Index(baseURL, "://"); idx >= 0 {
		scheme := baseURL[:idx+3]
		rest := baseURL[idx+3:]
		return fmt.Sprintf("%s%s:%s@%s", scheme, user, password, rest)
	}
	return baseURL
}

// Serve starts the HTTP server. This is a blocking call.
// When TLS is configured via WithTLS (or SWML_SSL_CERT_PATH / SWML_SSL_KEY_PATH
// env vars), ListenAndServeTLS is called automatically.
// Mirrors Python's serve() ssl_cert / ssl_key / ssl_enabled parameter support.
func (s *Service) Serve() error {
	mux := s.buildMux()
	addr := fmt.Sprintf("%s:%d", s.Host, s.Port)

	s.mu.Lock()
	s.server = &http.Server{
		Addr:    addr,
		Handler: mux,
	}
	if s.TLSEnabled() {
		// Require TLS 1.2+ (mirrors Python's CERT_REQUIRED ssl_verify_mode default).
		s.server.TLSConfig = &tls.Config{
			MinVersion: tls.VersionTLS12,
		}
	}
	s.running = true
	s.mu.Unlock()

	scheme := "http"
	if s.TLSEnabled() {
		scheme = "https"
	}
	s.Logger.Info("serving on %s://%s%s", scheme, addr, s.Route)
	s.Logger.Info("auth user: %s", s.basicAuthUser)

	if s.TLSEnabled() {
		s.Logger.Info("TLS enabled: cert=%s key=%s", s.tlsCertFile, s.tlsKeyFile)
		return s.server.ListenAndServeTLS(s.tlsCertFile, s.tlsKeyFile)
	}
	return s.server.ListenAndServe()
}

// Stop gracefully stops the HTTP server.
func (s *Service) Stop() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.server != nil {
		s.running = false
		return s.server.Close()
	}
	return nil
}

// buildMux creates the HTTP handler with auth middleware and routes.
func (s *Service) buildMux() *http.ServeMux {
	mux := http.NewServeMux()

	// Health endpoints (no auth)
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "healthy"})
	})
	mux.HandleFunc("/ready", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "ready"})
	})

	// Main SWML endpoint (with auth)
	route := s.Route
	if route == "" {
		route = "/"
	}
	mux.HandleFunc(route, s.withSecurity(s.handleSWML))

	return mux
}

// maxRequestBody is the maximum allowed request body size (1MB).
const maxRequestBody = 1 << 20

// handleSWML serves the SWML document.
func (s *Service) handleSWML(w http.ResponseWriter, r *http.Request) {
	var body map[string]any
	if r.Method == http.MethodPost {
		r.Body = http.MaxBytesReader(w, r.Body, maxRequestBody)
		json.NewDecoder(r.Body).Decode(&body)
	}

	doc := s.OnRequest(body, r.URL.Path)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(doc)
}

// withSecurity wraps a handler with auth and security headers.
// withSecurity wraps a handler with security headers and multi-method auth.
//
// Auth check order (mirrors Python AuthHandler.flask_decorator / get_fastapi_dependency):
//  1. Bearer token — "Authorization: Bearer <token>" header (if configured).
//  2. API key — configured header name (if configured).
//  3. HTTP Basic Auth — always checked as the final fallback.
//
// A request is authenticated when ANY of the configured methods matches. The
// previous behaviour (Basic Auth only) is preserved for services that do not
// configure bearer or API key auth.
func (s *Service) withSecurity(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// Security headers
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("X-Frame-Options", "DENY")
		w.Header().Set("Cache-Control", "no-store")

		s.mu.RLock()
		bearerToken := s.bearerToken
		apiKey := s.apiKey
		apiKeyHeader := s.apiKeyHeader
		basicUser := s.basicAuthUser
		basicPass := s.basicAuthPassword
		s.mu.RUnlock()

		// 1. Try Bearer token (if configured)
		if bearerToken != "" {
			authHdr := r.Header.Get("Authorization")
			if strings.HasPrefix(authHdr, "Bearer ") {
				token := authHdr[len("Bearer "):]
				if subtle.ConstantTimeCompare([]byte(token), []byte(bearerToken)) == 1 {
					next(w, r)
					return
				}
			}
		}

		// 2. Try API key (if configured)
		if apiKey != "" {
			hdr := apiKeyHeader
			if hdr == "" {
				hdr = "X-API-Key"
			}
			if k := r.Header.Get(hdr); k != "" {
				if subtle.ConstantTimeCompare([]byte(k), []byte(apiKey)) == 1 {
					next(w, r)
					return
				}
			}
		}

		// 3. Basic auth fallback (timing-safe comparison)
		user, pass, ok := r.BasicAuth()
		userMatch := subtle.ConstantTimeCompare([]byte(user), []byte(basicUser)) == 1
		passMatch := subtle.ConstantTimeCompare([]byte(pass), []byte(basicPass)) == 1
		if ok && userMatch && passMatch {
			next(w, r)
			return
		}

		w.Header().Set("WWW-Authenticate", `Basic realm="SWML Service"`)
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
	}
}
