// Code generated by cmd/generate-swml-verbs; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/schema.json ($defs) — regenerate with:
//   go run ./cmd/generate-swml-verbs
//
// The typed SWML verb CONFIG surface: one struct per schema.json $defs entry
// (object -> struct; non-object -> defined-type alias) + the flattened <Verb>Config
// payload shapes the SWML builder verb methods accept. Open shape; extra keys tolerated.

package swml

type AI struct {
	// Ai Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Ai any `json:"ai,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type AiSidecar struct {
	// AiSidecar Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	AiSidecar any `json:"ai_sidecar,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type AmazonBedrock struct {
	// AmazonBedrock Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	AmazonBedrock any `json:"amazon_bedrock,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Answer struct {
	// Answer Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Answer any `json:"answer,omitempty" gen:"union<dict<string,any>,list<any>>"`
}

type BindDigit struct {
	// BindDigit Bind DTMF digit actions.
	BindDigit map[string]any `json:"bind_digit,omitempty" gen:"dict<string,any>"`
}

type CallDeviceStream struct {
	AuthorizationBearerToken any            `json:"authorization_bearer_token,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Codec                    any            `json:"codec,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	CustomParameters         map[string]any `json:"custom_parameters,omitempty" gen:"dict<string,any>"`
	Name                     any            `json:"name,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Realtime                 any            `json:"realtime,omitempty" gen:"union<bool,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	StatusUrl                any            `json:"status_url,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	StatusUrlMethod          any            `json:"status_url_method,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Url                      any            `json:"url,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

type CallPayParameters struct {
	Name  any `json:"name,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Value any `json:"value,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

type CallPayPrompts struct {
	Actions               any `json:"actions,omitempty" gen:"union<list<union<class:signalwire.core.swml_verbs_generated.CallPayPromptsActions,class:signalwire.core.swml_verbs_generated.SWMLVar>>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Attempt               any `json:"attempt,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	CardType              any `json:"card_type,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	ErrorType             any `json:"error_type,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	For                   any `json:"for,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Play                  any `json:"play,omitempty" gen:"union<list<union<class:signalwire.core.swml_verbs_generated.RingbackConfig,class:signalwire.core.swml_verbs_generated.SWMLVar>>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	RequireMatchingInputs any `json:"require_matching_inputs,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

type CallPayPromptsActions struct {
	Type   any `json:"type,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Phrase any `json:"phrase,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

type ClearDigitBindings struct {
	// ClearDigitBindings Clear all digit bindings.
	ClearDigitBindings map[string]any `json:"clear_digit_bindings,omitempty" gen:"dict<string,any>"`
}

type Cond struct {
	// Cond Body shape enforced by is_valid_cond_method, swml_schema.c:1271.
	Cond []map[string]any `json:"cond,omitempty" gen:"list<dict<string,any>>"`
}

type Connect struct {
	// Connect Dial a SIP URI or phone number.
	Connect any `json:"connect,omitempty" gen:"dict<string,any>"`
}

// ConnectDevice Body shape enforced by CHECK_swml_connect_device, swml_schema.c.
type ConnectDevice struct {
	AuthorizationBearerToken any                 `json:"authorization_bearer_token,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	CallStateEvents          any                 `json:"call_state_events,omitempty" gen:"union<list<string>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	CallStateUrl             any                 `json:"call_state_url,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Codec                    any                 `json:"codec,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Codecs                   any                 `json:"codecs,omitempty" gen:"union<string,list<dict<string,any>>>"`
	Confirm                  any                 `json:"confirm,omitempty" gen:"union<union<string,list<class:signalwire.core.swml_verbs_generated.SWMLMethod>,dict<string,any>>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	ConfirmTimeout           any                 `json:"confirm_timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	CustomParameters         any                 `json:"custom_parameters,omitempty" gen:"union<dict<string,string>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Encryption               any                 `json:"encryption,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	From                     any                 `json:"from,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	FromName                 any                 `json:"from_name,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Headers                  []*ConnectSipHeader `json:"headers,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectSipHeader>"`
	Name                     any                 `json:"name,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Password                 any                 `json:"password,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Realtime                 any                 `json:"realtime,omitempty" gen:"union<bool,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	SessionTimeout           any                 `json:"session_timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	StatusUrl                any                 `json:"status_url,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	StatusUrlMethod          any                 `json:"status_url_method,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Timeout                  any                 `json:"timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	To                       any                 `json:"to,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Username                 any                 `json:"username,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	WebrtcMedia              any                 `json:"webrtc_media,omitempty" gen:"union<bool,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

// ConnectSerialParallel Body shape enforced by CHECK_swml_connect_serial_parallel, swml_schema.c.
type ConnectSerialParallel []*ConnectDevice

type ConnectSipHeader struct {
	Name  string `json:"name,omitempty" gen:"string"`
	Value any    `json:"value,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

type Context struct {
	Consolidate   any                 `json:"consolidate,omitempty" gen:"union<bool,string>"`
	EnterFillers  map[string]any      `json:"enter_fillers,omitempty" gen:"dict<string,any>"`
	ExitFillers   map[string]any      `json:"exit_fillers,omitempty" gen:"dict<string,any>"`
	FullReset     any                 `json:"full_reset,omitempty" gen:"union<bool,string>"`
	History       string              `json:"history,omitempty" gen:"string"`
	InitialStep   string              `json:"initial_step,omitempty" gen:"string"`
	Isolated      any                 `json:"isolated,omitempty" gen:"union<bool,string>"`
	Pom           []*PromptPomSection `json:"pom,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.PromptPomSection>"`
	PostPrompt    map[string]any      `json:"post_prompt,omitempty" gen:"dict<string,any>"`
	Prompt        string              `json:"prompt,omitempty" gen:"string"`
	Reset         any                 `json:"reset,omitempty" gen:"union<optional<list<any>>,bool,float,dict<string,any>,string>"`
	Steps         []*Step             `json:"steps,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.Step>"`
	SystemPrompt  string              `json:"system_prompt,omitempty" gen:"string"`
	UserPrompt    string              `json:"user_prompt,omitempty" gen:"string"`
	ValidContexts []any               `json:"valid_contexts,omitempty" gen:"list<any>"`
	ValidSteps    []any               `json:"valid_steps,omitempty" gen:"list<any>"`
}

type DataMap struct {
	Contexts    any            `json:"contexts,omitempty" gen:"union<optional<list<any>>,bool,float,dict<string,any>,string>"`
	Expressions any            `json:"expressions,omitempty" gen:"union<list<class:signalwire.core.swml_verbs_generated.Expression>,class:signalwire.core.swml_verbs_generated.Expression>"`
	Output      *SwaigResponse `json:"output,omitempty" gen:"class:signalwire.core.swml_verbs_generated.SwaigResponse"`
	Webhooks    any            `json:"webhooks,omitempty" gen:"union<list<class:signalwire.core.swml_verbs_generated.Webhook>,class:signalwire.core.swml_verbs_generated.Webhook>"`
}

type Denoise struct {
	// Denoise Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Denoise any `json:"denoise,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type DetectMachine struct {
	// DetectMachine Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	DetectMachine any `json:"detect_machine,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Dial struct {
	// Dial Dial out to one or more endpoints (deprecated).
	Dial any `json:"dial,omitempty" gen:"dict<string,any>"`
}

type Echo struct {
	// Echo Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Echo any `json:"echo,omitempty" gen:"union<dict<string,any>,list<any>>"`
}

type EnterQueue struct {
	// EnterQueue Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	EnterQueue any `json:"enter_queue,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Eval struct {
	// Eval Evaluate expressions and assign to variables (deprecated).
	Eval map[string]any `json:"eval,omitempty" gen:"dict<string,any>"`
}

type Execute struct {
	// Execute Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Execute any `json:"execute,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type ExecuteRpc struct {
	// ExecuteRpc Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	ExecuteRpc any `json:"execute_rpc,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

// Expression Without one of `expr` / `string` and `output`, a Expression has no effect: it is accepted and ignored, not rejected.
type Expression struct {
	Pattern       string         `json:"pattern,omitempty" gen:"string"`
	Expr          string         `json:"expr,omitempty" gen:"string"`
	NomatchOutput *SwaigResponse `json:"nomatch-output,omitempty" gen:"class:signalwire.core.swml_verbs_generated.SwaigResponse"`
	Output        *SwaigResponse `json:"output,omitempty" gen:"class:signalwire.core.swml_verbs_generated.SwaigResponse"`
	String        string         `json:"string,omitempty" gen:"string"`
}

// Foreach Without `append`, `input_key` and `output_key`, a Foreach has no effect: it is accepted and ignored, not rejected.
type Foreach struct {
	Append    string `json:"append,omitempty" gen:"string"`
	InputKey  string `json:"input_key,omitempty" gen:"string"`
	Max       any    `json:"max,omitempty" gen:"union<float,string>"`
	OutputKey string `json:"output_key,omitempty" gen:"string"`
}

type Goto struct {
	// Goto Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Goto any `json:"goto,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type Hangup struct {
	// Hangup Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Hangup any `json:"hangup,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type If struct {
	// If Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	If any `json:"if,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type JoinConference struct {
	// JoinConference Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	JoinConference any `json:"join_conference,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type JoinRoom struct {
	// JoinRoom Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	JoinRoom any `json:"join_room,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

// JsonSchema A JSON Schema (draft 2020-12). The value is forwarded verbatim to the receiving model API, which owns this contract; the engine does not inspect it.
type JsonSchema struct {
	Title                 string              `json:"title,omitempty" gen:"string"`
	Description           string              `json:"description,omitempty" gen:"string"`
	Type                  any                 `json:"type,omitempty" gen:"union<string,list<string>>"`
	Const                 map[string]any      `json:"const,omitempty" gen:"dict<string,any>"`
	Enum                  []any               `json:"enum,omitempty" gen:"list<any>"`
	Format                string              `json:"format,omitempty" gen:"string"`
	Pattern               string              `json:"pattern,omitempty" gen:"string"`
	Minimum               float64             `json:"minimum,omitempty" gen:"float"`
	Maximum               float64             `json:"maximum,omitempty" gen:"float"`
	ExclusiveMinimum      float64             `json:"exclusiveMinimum,omitempty" gen:"float"`
	ExclusiveMaximum      float64             `json:"exclusiveMaximum,omitempty" gen:"float"`
	MinLength             int                 `json:"minLength,omitempty" gen:"int"`
	MaxLength             int                 `json:"maxLength,omitempty" gen:"int"`
	MinItems              int                 `json:"minItems,omitempty" gen:"int"`
	MaxItems              int                 `json:"maxItems,omitempty" gen:"int"`
	MinProperties         int                 `json:"minProperties,omitempty" gen:"int"`
	MaxProperties         int                 `json:"maxProperties,omitempty" gen:"int"`
	Default               map[string]any      `json:"default,omitempty" gen:"dict<string,any>"`
	Examples              []any               `json:"examples,omitempty" gen:"list<any>"`
	Deprecated            bool                `json:"deprecated,omitempty" gen:"bool"`
	Properties            map[string]any      `json:"properties,omitempty" gen:"dict<string,union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>>"`
	Required              []string            `json:"required,omitempty" gen:"list<string>"`
	PrefixItems           []any               `json:"prefixItems,omitempty" gen:"list<union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>>"`
	Items                 any                 `json:"items,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	PropertyNames         any                 `json:"propertyNames,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	AdditionalProperties  any                 `json:"additionalProperties,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	UnevaluatedProperties any                 `json:"unevaluatedProperties,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	OneOf                 []any               `json:"oneOf,omitempty" gen:"list<union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>>"`
	AnyOf                 []any               `json:"anyOf,omitempty" gen:"list<union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>>"`
	AllOf                 []any               `json:"allOf,omitempty" gen:"list<union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>>"`
	Not                   any                 `json:"not,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	Contains              any                 `json:"contains,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	DependentRequired     map[string][]string `json:"dependentRequired,omitempty" gen:"dict<string,list<string>>"`
	DependentSchemas      map[string]any      `json:"dependentSchemas,omitempty" gen:"dict<string,union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>>"`
	Else                  any                 `json:"else,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	If                    any                 `json:"if,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	MaxContains           int                 `json:"maxContains,omitempty" gen:"int"`
	MinContains           int                 `json:"minContains,omitempty" gen:"int"`
	MultipleOf            float64             `json:"multipleOf,omitempty" gen:"float"`
	PatternProperties     map[string]any      `json:"patternProperties,omitempty" gen:"dict<string,union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>>"`
	ReadOnly              bool                `json:"readOnly,omitempty" gen:"bool"`
	Then                  any                 `json:"then,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	UnevaluatedItems      any                 `json:"unevaluatedItems,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchema,bool>"`
	UniqueItems           bool                `json:"uniqueItems,omitempty" gen:"bool"`
	WriteOnly             bool                `json:"writeOnly,omitempty" gen:"bool"`
}

// JsonSchemaUnion A JSON Schema (draft 2020-12) that may also carry `example`, `nullable`, `propertyOrdering`: the value is forwarded verbatim to whichever model API the session resolves to, and those receivers do not accept one vocabulary, so a schema here must be able to express their UNION (vocabulary_union). The engine does not inspect it.
type JsonSchemaUnion struct {
	Title                 string              `json:"title,omitempty" gen:"string"`
	Description           string              `json:"description,omitempty" gen:"string"`
	Type                  any                 `json:"type,omitempty" gen:"union<string,list<string>>"`
	Const                 map[string]any      `json:"const,omitempty" gen:"dict<string,any>"`
	Enum                  []any               `json:"enum,omitempty" gen:"list<any>"`
	Format                string              `json:"format,omitempty" gen:"string"`
	Pattern               string              `json:"pattern,omitempty" gen:"string"`
	Minimum               float64             `json:"minimum,omitempty" gen:"float"`
	Maximum               float64             `json:"maximum,omitempty" gen:"float"`
	ExclusiveMinimum      float64             `json:"exclusiveMinimum,omitempty" gen:"float"`
	ExclusiveMaximum      float64             `json:"exclusiveMaximum,omitempty" gen:"float"`
	MinLength             int                 `json:"minLength,omitempty" gen:"int"`
	MaxLength             int                 `json:"maxLength,omitempty" gen:"int"`
	MinItems              int                 `json:"minItems,omitempty" gen:"int"`
	MaxItems              int                 `json:"maxItems,omitempty" gen:"int"`
	MinProperties         int                 `json:"minProperties,omitempty" gen:"int"`
	MaxProperties         int                 `json:"maxProperties,omitempty" gen:"int"`
	Default               map[string]any      `json:"default,omitempty" gen:"dict<string,any>"`
	Examples              []any               `json:"examples,omitempty" gen:"list<any>"`
	Deprecated            bool                `json:"deprecated,omitempty" gen:"bool"`
	Nullable              bool                `json:"nullable,omitempty" gen:"bool"`
	Properties            map[string]any      `json:"properties,omitempty" gen:"dict<string,union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>>"`
	Required              []string            `json:"required,omitempty" gen:"list<string>"`
	PrefixItems           []any               `json:"prefixItems,omitempty" gen:"list<union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>>"`
	Items                 any                 `json:"items,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	PropertyNames         any                 `json:"propertyNames,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	AdditionalProperties  any                 `json:"additionalProperties,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	UnevaluatedProperties any                 `json:"unevaluatedProperties,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	OneOf                 []any               `json:"oneOf,omitempty" gen:"list<union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>>"`
	AnyOf                 []any               `json:"anyOf,omitempty" gen:"list<union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>>"`
	AllOf                 []any               `json:"allOf,omitempty" gen:"list<union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>>"`
	Not                   any                 `json:"not,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	Contains              any                 `json:"contains,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	DependentRequired     map[string][]string `json:"dependentRequired,omitempty" gen:"dict<string,list<string>>"`
	DependentSchemas      map[string]any      `json:"dependentSchemas,omitempty" gen:"dict<string,union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>>"`
	Else                  any                 `json:"else,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	Example               map[string]any      `json:"example,omitempty" gen:"dict<string,any>"`
	If                    any                 `json:"if,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	MaxContains           int                 `json:"maxContains,omitempty" gen:"int"`
	MinContains           int                 `json:"minContains,omitempty" gen:"int"`
	MultipleOf            float64             `json:"multipleOf,omitempty" gen:"float"`
	PatternProperties     map[string]any      `json:"patternProperties,omitempty" gen:"dict<string,union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>>"`
	PropertyOrdering      []string            `json:"propertyOrdering,omitempty" gen:"list<string>"`
	ReadOnly              bool                `json:"readOnly,omitempty" gen:"bool"`
	Then                  any                 `json:"then,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	UnevaluatedItems      any                 `json:"unevaluatedItems,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.JsonSchemaUnion,bool>"`
	UniqueItems           bool                `json:"uniqueItems,omitempty" gen:"bool"`
	WriteOnly             bool                `json:"writeOnly,omitempty" gen:"bool"`
}

type Label struct {
	// Label Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Label any `json:"label,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type LiveTranscribe struct {
	// LiveTranscribe Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	LiveTranscribe any `json:"live_transcribe,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type LiveTranslate struct {
	// LiveTranslate Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	LiveTranslate any `json:"live_translate,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Pay struct {
	// Pay Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Pay any `json:"pay,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Play struct {
	// Play Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Play any `json:"play,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type Prompt struct {
	// Prompt Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Prompt any `json:"prompt,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

// PromptPomSection Without one of `body` / `bullets` / `subsections`, the object has no effect: it is accepted and ignored, not rejected.
type PromptPomSection struct {
	Title           string              `json:"title,omitempty" gen:"string"`
	Body            string              `json:"body,omitempty" gen:"string"`
	Bullets         []string            `json:"bullets,omitempty" gen:"list<string>"`
	Numbered        bool                `json:"numbered,omitempty" gen:"bool"`
	NumberedBullets bool                `json:"numberedBullets,omitempty" gen:"bool"`
	Subsections     []*PromptPomSection `json:"subsections,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.PromptPomSection>"`
}

type ReceiveFax struct {
	// ReceiveFax Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	ReceiveFax any `json:"receive_fax,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type Record struct {
	// Record Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Record any `json:"record,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type RecordCall struct {
	// RecordCall Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	RecordCall any `json:"record_call,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Request struct {
	// Request Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Request any `json:"request,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Return struct {
	// Return Body shape enforced by CHECK_swml_method_return, swml_schema.c:1495.
	Return any `json:"return,omitempty" gen:"union<optional<dict<string,any>>,list<any>,bool,float,string>"`
}

type Ring struct {
	// Ring Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Ring any `json:"ring,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

// RingbackConfig Declared as a named $defs entry so every generator emits a TYPED shape via $ref rather than collapsing an inline object to an untyped map.
type RingbackConfig struct {
	// Url URL to play.
	Url string `json:"url,omitempty" gen:"string"`
	// Urls Array of URLs to play.
	Urls []string `json:"urls,omitempty" gen:"list<string>"`
	// Volume Volume level for the audio file.
	Volume any `json:"volume,omitempty" gen:"union<float,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

type SIPRefer struct {
	// SipRefer Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	SipRefer any `json:"sip_refer,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type SWMLMethod any

// SWMLVar A SWML variable reference using ${varname} or %{varname} syntax for dynamic value substitution at runtime.
type SWMLVar string

type Section struct {
	Main []*SWMLMethod `json:"main,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.SWMLMethod>"`
}

type SendDigits struct {
	// SendDigits Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	SendDigits any `json:"send_digits,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type SendFax struct {
	// SendFax Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	SendFax any `json:"send_fax,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type SendSMS struct {
	// SendSms Send an outbound SMS or MMS message to a PSTN phone number.
	SendSms map[string]any `json:"send_sms,omitempty" gen:"dict<string,any>"`
}

type Set struct {
	// Set Set script variables to the specified values.
	Set map[string]any `json:"set,omitempty" gen:"dict<string,any>"`
}

type SetCapabilities struct {
	// SetCapabilities Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	SetCapabilities any `json:"set_capabilities,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type SetMeta struct {
	// SetMeta Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	SetMeta any `json:"set_meta,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Sleep struct {
	// Sleep Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Sleep any `json:"sleep,omitempty" gen:"union<dict<string,any>,list<any>>"`
}

type Step struct {
	End            any                 `json:"end,omitempty" gen:"union<bool,string>"`
	Functions      []any               `json:"functions,omitempty" gen:"list<any>"`
	GatherInfo     map[string]any      `json:"gather_info,omitempty" gen:"dict<string,any>"`
	History        string              `json:"history,omitempty" gen:"string"`
	Name           string              `json:"name,omitempty" gen:"string"`
	Pom            []*PromptPomSection `json:"pom,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.PromptPomSection>"`
	Reset          map[string]any      `json:"reset,omitempty" gen:"dict<string,any>"`
	SkipToNextStep any                 `json:"skip_to_next_step,omitempty" gen:"union<bool,string>"`
	SkipUserTurn   any                 `json:"skip_user_turn,omitempty" gen:"union<bool,string>"`
	StepCriteria   string              `json:"step_criteria,omitempty" gen:"string"`
	Text           string              `json:"text,omitempty" gen:"string"`
	ValidContexts  []string            `json:"valid_contexts,omitempty" gen:"list<string>"`
	ValidSteps     []string            `json:"valid_steps,omitempty" gen:"list<string>"`
}

type StopDenoise struct {
	// StopDenoise Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	StopDenoise any `json:"stop_denoise,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type StopRecordCall struct {
	// StopRecordCall Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	StopRecordCall any `json:"stop_record_call,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type StopStream struct {
	// StopStream Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	StopStream any `json:"stop_stream,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type StopTap struct {
	// StopTap Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	StopTap any `json:"stop_tap,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type Stream struct {
	// Stream Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Stream any `json:"stream,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type SwaigAction struct {
	SWML                      any              `json:"SWML,omitempty" gen:"union<string,dict<string,any>>"`
	AddDynamicHints           []any            `json:"add_dynamic_hints,omitempty" gen:"list<union<dict<string,any>,string>>"`
	BackToBackFunctions       any              `json:"back_to_back_functions,omitempty" gen:"union<bool,string>"`
	ChangeContext             string           `json:"change_context,omitempty" gen:"string"`
	ChangeStep                string           `json:"change_step,omitempty" gen:"string"`
	ChangeVoice               any              `json:"change_voice,omitempty" gen:"union<string,dict<string,any>>"`
	ClearDynamicHints         any              `json:"clear_dynamic_hints,omitempty" gen:"union<bool,string>"`
	ContextSwitch             any              `json:"context_switch,omitempty" gen:"union<string,dict<string,any>>"`
	EndOfSpeechTimeout        int              `json:"end_of_speech_timeout,omitempty" gen:"int"`
	ExtensiveData             any              `json:"extensive_data,omitempty" gen:"union<bool,string>"`
	FunctionsOnSpeakerTimeout any              `json:"functions_on_speaker_timeout,omitempty" gen:"union<bool,string>"`
	Hangup                    any              `json:"hangup,omitempty" gen:"union<bool,string>"`
	Hold                      any              `json:"hold,omitempty" gen:"union<int,string,dict<string,any>>"`
	PlaybackBg                any              `json:"playback_bg,omitempty" gen:"union<string,dict<string,any>>"`
	ReplaceInHistory          any              `json:"replace_in_history,omitempty" gen:"string"`
	Say                       string           `json:"say,omitempty" gen:"string"`
	SetGlobalData             map[string]any   `json:"set_global_data,omitempty" gen:"dict<string,any>"`
	SetMetaData               map[string]any   `json:"set_meta_data,omitempty" gen:"dict<string,any>"`
	Settings                  map[string]any   `json:"settings,omitempty" gen:"dict<string,any>"`
	SpeechEventTimeout        int              `json:"speech_event_timeout,omitempty" gen:"int"`
	Stop                      any              `json:"stop,omitempty" gen:"union<bool,string>"`
	StopPlaybackBg            any              `json:"stop_playback_bg,omitempty" gen:"optional<union<bool,string,int,dict<string,any>,list<any>>>"`
	ToggleFunctions           []map[string]any `json:"toggle_functions,omitempty" gen:"list<dict<string,any>>"`
	Transfer                  any              `json:"transfer,omitempty" gen:"union<string,dict<string,any>>"`
	UnsetGlobalData           any              `json:"unset_global_data,omitempty" gen:"union<string,list<string>>"`
	UnsetMetaData             any              `json:"unset_meta_data,omitempty" gen:"union<string,list<string>>"`
	UserEvent                 map[string]any   `json:"user_event,omitempty" gen:"dict<string,any>"`
	UserInput                 string           `json:"user_input,omitempty" gen:"string"`
	WaitForUser               any              `json:"wait_for_user,omitempty" gen:"union<bool,int,string>"`
}

type SwaigResponse struct {
	Action      any  `json:"action,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.SwaigAction,list<class:signalwire.core.swml_verbs_generated.SwaigAction>>"`
	PostProcess bool `json:"post_process,omitempty" gen:"bool"`
	Response    any  `json:"response,omitempty" gen:"union<string,dict<string,any>>"`
}

type Switch struct {
	// Switch Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Switch any `json:"switch,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Tap struct {
	// Tap Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Tap any `json:"tap,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type Transcribe struct {
	// Transcribe Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Transcribe any `json:"transcribe,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type TranscribeStop struct {
	// TranscribeStop Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	TranscribeStop any `json:"transcribe_stop,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

type Transfer struct {
	// Transfer Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	Transfer any `json:"transfer,omitempty" gen:"union<dict<string,any>,list<any>,float>"`
}

type Unset struct {
	// Unset Body shape enforced by CHECK_swml_method_unset, swml_schema.c.
	Unset any `json:"unset,omitempty" gen:"union<list<string>,string>"`
}

type UserEvent struct {
	// UserEvent Body shape enforced by check_method_type_and_unknown_params, swml_schema.c:911.
	UserEvent any `json:"user_event,omitempty" gen:"union<dict<string,any>,list<any>,float,string>"`
}

// Webhook Without one of `expressions` / `output` and `url`, a Webhook has no effect: it is accepted and ignored, not rejected.
type Webhook struct {
	ErrorKeys         any            `json:"error_keys,omitempty" gen:"union<list<any>,string>"`
	Expressions       any            `json:"expressions,omitempty" gen:"union<list<class:signalwire.core.swml_verbs_generated.Expression>,class:signalwire.core.swml_verbs_generated.Expression>"`
	Foreach           *Foreach       `json:"foreach,omitempty" gen:"class:signalwire.core.swml_verbs_generated.Foreach"`
	FormParam         string         `json:"form_param,omitempty" gen:"string"`
	Headers           map[string]any `json:"headers,omitempty" gen:"dict<string,any>"`
	InputArgsAsParams bool           `json:"input_args_as_params,omitempty" gen:"bool"`
	Method            string         `json:"method,omitempty" gen:"string"`
	Output            *SwaigResponse `json:"output,omitempty" gen:"class:signalwire.core.swml_verbs_generated.SwaigResponse"`
	Params            any            `json:"params,omitempty" gen:"union<optional<list<any>>,bool,float,dict<string,any>,string>"`
	RequireArgs       any            `json:"require_args,omitempty" gen:"union<list<any>,string>"`
	Url               string         `json:"url,omitempty" gen:"string"`
}

// BindDigitConfig Bind DTMF digit actions.
type BindDigitConfig struct {
	Digits      string         `json:"digits,omitempty" gen:"string"`
	MaxTriggers any            `json:"max_triggers,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Method      string         `json:"method,omitempty" gen:"string"`
	Params      map[string]any `json:"params,omitempty" gen:"dict<string,any>"`
	Realm       string         `json:"realm,omitempty" gen:"string"`
}

// ClearDigitBindingsConfig Clear all digit bindings.
type ClearDigitBindingsConfig struct {
	Realm string `json:"realm,omitempty" gen:"string"`
}

// ConnectConfig Dial a SIP URI or phone number.
type ConnectConfig struct {
	// AnswerOnBridge Delay answer until the B-leg answers.
	AnswerOnBridge           any `json:"answer_on_bridge,omitempty" gen:"union<union<bool,string>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	AuthorizationBearerToken any `json:"authorization_bearer_token,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// CallStateEvents An array of call state event names to be notified about.
	CallStateEvents any `json:"call_state_events,omitempty" gen:"union<list<string>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// CallStateUrl Webhook URL to send call status change notifications to. Authentication can also be set in the URL in the format of `username:password@url`.
	CallStateUrl any `json:"call_state_url,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Codec        any `json:"codec,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Codecs Comma-separated string of codecs to offer.
	Codecs any `json:"codecs,omitempty" gen:"union<union<string,list<dict<string,any>>>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Confirm Confirmation to execute when the call is connected. Can be either:
	Confirm any `json:"confirm,omitempty" gen:"union<union<string,list<class:signalwire.core.swml_verbs_generated.SWMLMethod>,dict<string,any>>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// ConfirmTimeout The amount of time, in seconds, to wait for the `confirm` URL to return a response
	ConfirmTimeout   any `json:"confirm_timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	CustomParameters any `json:"custom_parameters,omitempty" gen:"union<dict<string,string>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Encryption Encryption setting to use. **Possible values:** `mandatory`, `optional`, `forbidden`
	Encryption        any `json:"encryption,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	ExecuteAfterQueue any `json:"execute_after_queue,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// From The caller ID to use when dialing the number.
	From any `json:"from,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// FromName The caller ID name shown to the person you're calling, displayed alongside the `from` number
	FromName any `json:"from_name,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Headers Custom SIP headers to add to INVITE. It Has no effect on calls to phone numbers.
	Headers []*ConnectSipHeader `json:"headers,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectSipHeader>"`
	// MaxDuration Maximum duration, in seconds, allowed for the call.
	MaxDuration any `json:"max_duration,omitempty" gen:"union<float,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Name        any `json:"name,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Parallel Array of destination objects to dial simultaneously. All destinations ring at the same time — the first to answer is bridged and the remaining calls are cancelled.
	Parallel []*ConnectDevice `json:"parallel,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectDevice>"`
	// Password SIP password to use for authentication when dialing a SIP URI. Has no effect on calls to phone numbers.
	Password any `json:"password,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Realtime any `json:"realtime,omitempty" gen:"union<bool,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Result Action to take based on the result of the call. This will run once the peer leg of the call has ended.
	Result any `json:"result,omitempty" gen:"union<list<dict<string,any>>,dict<string,any>>"`
	// Ringback Ringback to play while the call is connecting: a URL, a list of URLs, or a play object (`url` / `urls` / `volume`). `false` turns the generated ringback off and passes the far end's early media through. If not specified, plays audio from the provider.
	Ringback any `json:"ringback,omitempty" gen:"union<bool,string,list<any>,class:signalwire.core.swml_verbs_generated.RingbackConfig>"`
	// Serial Array of destination objects to dial in order. Each destination is tried sequentially — if the current destination does not answer, the next one in the array is attempted.
	Serial []*ConnectDevice `json:"serial,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectDevice>"`
	// SerialParallel Two-dimensional array combining serial and parallel strategies.
	SerialParallel []*ConnectSerialParallel `json:"serial_parallel,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectSerialParallel>"`
	// SessionTimeout Time, in seconds, to set the SIP `Session-Expires` header in INVITE.
	SessionTimeout any `json:"session_timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// StatusUrl HTTP or HTTPS URL to deliver connect status events.
	StatusUrl       any `json:"status_url,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	StatusUrlMethod any `json:"status_url_method,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	StopAllOnReject any `json:"stop_all_on_reject,omitempty" gen:"union<union<list<dict<string,any>>,bool,string>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Timeout Time, in seconds, to wait for the call to be answered.
	Timeout any `json:"timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// To Destination to dial. Can be:
	To any `json:"to,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Username SIP username to use for authentication when dialing a SIP URI. Has no effect on calls to phone numbers.
	Username any `json:"username,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// WebrtcMedia If true, WebRTC media is offered to the SIP endpoint.
	WebrtcMedia any `json:"webrtc_media,omitempty" gen:"union<bool,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

// DialConfig Dial out to one or more endpoints (deprecated).
type DialConfig struct {
	AnswerOnBridge    any                      `json:"answer_on_bridge,omitempty" gen:"union<bool,string>"`
	CallStateEvents   any                      `json:"call_state_events,omitempty" gen:"union<list<string>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	CallStateUrl      any                      `json:"call_state_url,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Codecs            any                      `json:"codecs,omitempty" gen:"union<union<string,list<dict<string,any>>>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Confirm           any                      `json:"confirm,omitempty" gen:"union<union<string,list<class:signalwire.core.swml_verbs_generated.SWMLMethod>,dict<string,any>>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	ConfirmTimeout    any                      `json:"confirm_timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	DestSwml          any                      `json:"dest_swml,omitempty" gen:"union<string,dict<string,any>,list<dict<string,any>>>"`
	Encryption        any                      `json:"encryption,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	ExecuteAfterQueue any                      `json:"execute_after_queue,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	From              any                      `json:"from,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	FromName          any                      `json:"from_name,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Headers           []*ConnectSipHeader      `json:"headers,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectSipHeader>"`
	MaxDuration       any                      `json:"max_duration,omitempty" gen:"union<float,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Parallel          []*ConnectDevice         `json:"parallel,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectDevice>"`
	Password          any                      `json:"password,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Result            map[string]any           `json:"result,omitempty" gen:"dict<string,any>"`
	Ringback          any                      `json:"ringback,omitempty" gen:"union<class:signalwire.core.swml_verbs_generated.RingbackConfig,list<any>,string>"`
	Serial            []*ConnectDevice         `json:"serial,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectDevice>"`
	SerialParallel    []*ConnectSerialParallel `json:"serial_parallel,omitempty" gen:"list<class:signalwire.core.swml_verbs_generated.ConnectSerialParallel>"`
	SessionTimeout    any                      `json:"session_timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	StatusUrl         any                      `json:"status_url,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	StopAllOnReject   any                      `json:"stop_all_on_reject,omitempty" gen:"union<union<list<dict<string,any>>,bool,string>,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Timeout           any                      `json:"timeout,omitempty" gen:"union<int,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	To                any                      `json:"to,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	Username          any                      `json:"username,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	WebrtcMedia       any                      `json:"webrtc_media,omitempty" gen:"union<bool,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}

// SendSmsConfig Send an outbound SMS or MMS message to a PSTN phone number.
type SendSmsConfig struct {
	// Body Optional if `media` is present. The body of the SMS message.
	Body any `json:"body,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// FromNumber Phone number the SMS message will be sent from in E.164 format.
	FromNumber any `json:"from_number,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Media Required if `body` is not present. Array of media URLs to include in the message.
	Media []string `json:"media,omitempty" gen:"list<string>"`
	// Region Region of the world to originate the message from. Chosen based on account preferences or device location if not specified.
	Region any `json:"region,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// StatusCallback URL to receive delivery status callbacks for the outbound message (e.g., `queued`, `sent`, `delivered`, `failed`). Not set if not specified. The callback uses the [message status callback payload](/docs/apis/rest/messages/webhooks/message-status-callback).
	StatusCallback any `json:"status_callback,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
	// Tags Array of tags to associate with the message to facilitate log searches.
	Tags []string `json:"tags,omitempty" gen:"list<string>"`
	// ToNumber Phone number to send SMS message to in E.164 format.
	ToNumber any `json:"to_number,omitempty" gen:"union<string,class:signalwire.core.swml_verbs_generated.SWMLVar>"`
}
