// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "calling" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type CallAIMessageRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallAIMessageResetParams struct {
	FullReset    *bool   `json:"full_reset,omitempty"`
	UserPrompt   *string `json:"user_prompt,omitempty"`
	SystemPrompt *string `json:"system_prompt,omitempty"`
}

type CallCreate422Error struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type CallCreateParamsSWML struct {
	From         string     `json:"from,omitempty"`
	To           string     `json:"to,omitempty"`
	CallerId     *string    `json:"caller_id,omitempty"`
	FallbackUrl  *string    `json:"fallback_url,omitempty"`
	StatusUrl    *string    `json:"status_url,omitempty"`
	StatusEvents []string   `json:"status_events,omitempty"`
	UrlMethod    *string    `json:"url_method,omitempty"`
	Codecs       any        `json:"codecs,omitempty"`
	Swml         SWMLObject `json:"swml,omitempty"`
}

type CallCreateParamsURL struct {
	From         string   `json:"from,omitempty"`
	To           string   `json:"to,omitempty"`
	CallerId     *string  `json:"caller_id,omitempty"`
	FallbackUrl  *string  `json:"fallback_url,omitempty"`
	StatusUrl    *string  `json:"status_url,omitempty"`
	StatusEvents []string `json:"status_events,omitempty"`
	UrlMethod    *string  `json:"url_method,omitempty"`
	Url          string   `json:"url,omitempty"`
}

type CallCreateRequest struct {
	Command string `json:"command,omitempty"`
	Params  any    `json:"params,omitempty"`
}

type CallDirection string

const (
	CallDirectionInbound     CallDirection = "inbound"
	CallDirectionOutbound    CallDirection = "outbound"
	CallDirectionOutboundApi CallDirection = "outbound-api"
)

type CallHangupRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallHoldRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallLeg struct {
	Id            uuid            `json:"id,omitempty"`
	From          string          `json:"from,omitempty"`
	To            string          `json:"to,omitempty"`
	Direction     CallDirection   `json:"direction,omitempty"`
	Source        string          `json:"source,omitempty"`
	Url           any             `json:"url,omitempty"`
	Charge        float64         `json:"charge,omitempty"`
	CreatedAt     string          `json:"created_at,omitempty"`
	ChargeDetails []ChargeDetails `json:"charge_details,omitempty"`
	Status        any             `json:"status,omitempty"`
	Duration      any             `json:"duration,omitempty"`
	DurationMs    any             `json:"duration_ms,omitempty"`
	BillingMs     any             `json:"billing_ms,omitempty"`
	Type_         any             `json:"type,omitempty"`
	ParentId      any             `json:"parent_id,omitempty"`
}

type CallLiveTranscribeRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallLiveTranslateRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallRequest any

type CallDisconnectRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallPlayRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallPlayPauseRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallPlayResumeRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallPlayStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallPlayVolumeRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallRecordRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallRecordPauseRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallRecordResumeRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallRecordStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallCollectRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallCollectStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallCollectStartInputTimersRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallDetectRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallDetectStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallTapRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallTapStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallStreamRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallStreamStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallDenoiseRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallDenoiseStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallTranscribeRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallTranscribeStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallAIStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallSendFaxStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallReceiveFaxStopRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallReferRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallResponse any

type CallResponseStatus string

const (
	CallResponseStatusQueued    CallResponseStatus = "queued"
	CallResponseStatusInitiated CallResponseStatus = "initiated"
	CallResponseStatusCreated   CallResponseStatus = "created"
	CallResponseStatusRinging   CallResponseStatus = "ringing"
	CallResponseStatusAnswered  CallResponseStatus = "answered"
	CallResponseStatusEnding    CallResponseStatus = "ending"
	CallResponseStatusEnded     CallResponseStatus = "ended"
	CallResponseStatusFailed    CallResponseStatus = "failed"
	CallResponseStatusCanceled  CallResponseStatus = "canceled"
	CallResponseStatusCompleted CallResponseStatus = "completed"
)

type CallTransferRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallUnholdRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type CallUpdateCurrentCallRequest struct {
	Command string `json:"command,omitempty"`
	Params  any    `json:"params,omitempty"`
}

type CallUpdateParamsSWML struct {
	Id          uuid       `json:"id,omitempty"`
	FallbackUrl *string    `json:"fallback_url,omitempty"`
	Status      *string    `json:"status,omitempty"`
	StatusUrl   *string    `json:"status_url,omitempty"`
	Swml        SWMLObject `json:"swml,omitempty"`
}

type CallUpdateParamsURL struct {
	Id          uuid    `json:"id,omitempty"`
	FallbackUrl *string `json:"fallback_url,omitempty"`
	Status      *string `json:"status,omitempty"`
	StatusUrl   *string `json:"status_url,omitempty"`
	Url         string  `json:"url,omitempty"`
}

type CallUserEventRequest struct {
	Id      uuid           `json:"id,omitempty"`
	Command string         `json:"command,omitempty"`
	Params  map[string]any `json:"params,omitempty"`
}

type ChargeDetails struct {
	Description string  `json:"description,omitempty"`
	Charge      float64 `json:"charge,omitempty"`
}

type FabricDeviceLeg struct {
	Id            uuid            `json:"id,omitempty"`
	From          string          `json:"from,omitempty"`
	To            string          `json:"to,omitempty"`
	Direction     CallDirection   `json:"direction,omitempty"`
	Source        string          `json:"source,omitempty"`
	Url           any             `json:"url,omitempty"`
	Charge        float64         `json:"charge,omitempty"`
	CreatedAt     string          `json:"created_at,omitempty"`
	ChargeDetails []ChargeDetails `json:"charge_details,omitempty"`
	Status        any             `json:"status,omitempty"`
	Type_         string          `json:"type,omitempty"`
}

type HangupReason string

const (
	HangupReasonHangup   HangupReason = "hangup"
	HangupReasonCancel   HangupReason = "cancel"
	HangupReasonBusy     HangupReason = "busy"
	HangupReasonNoAnswer HangupReason = "noAnswer"
	HangupReasonDecline  HangupReason = "decline"
	HangupReasonError    HangupReason = "error"
)

type LiveTranscribeStartAction struct {
	Start map[string]any `json:"start,omitempty"`
}

type LiveTranscribeStopAction string

const (
	LiveTranscribeStopActionStop LiveTranscribeStopAction = "stop"
)

type LiveTranscribeSummarizeAction struct {
	Summarize map[string]any `json:"summarize,omitempty"`
}

type LiveTranslateInjectAction struct {
	Inject map[string]any `json:"inject,omitempty"`
}

type LiveTranslateStartAction struct {
	Start map[string]any `json:"start,omitempty"`
}

type LiveTranslateStopAction string

const (
	LiveTranslateStopActionStop LiveTranslateStopAction = "stop"
)

type LiveTranslateSummarizeAction struct {
	Summarize map[string]any `json:"summarize,omitempty"`
}
