// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "calling" namespace spec.

package namespaces

// CallingNamespace is generated from the command-dispatch x-sdk-resource "Calling" (calling spec).
type CallingNamespace struct {
	Resource
}

// NewCallingNamespace constructs a CallingNamespace bound to base path "/api/calling/calls".
func NewCallingNamespace(client HTTPClient) *CallingNamespace {
	return &CallingNamespace{Resource{HTTP: client, Base: "/api/calling/calls"}}
}

func (c *CallingNamespace) execute(command string, callID string, params map[string]any) (map[string]any, error) {
	body := map[string]any{"command": command, "params": params}
	if callID != "" {
		body["id"] = callID
	}
	return c.HTTP.Post(c.Base, body, nil)
}

// CallingNamespaceDialParams holds the named optional parameters for CallingNamespace.Dial.
type CallingNamespaceDialParams struct {
	From         any
	To           any
	Url          any
	Swml         any
	CallerId     any
	FallbackUrl  any
	StatusUrl    any
	StatusEvents any
	UrlMethod    any
	Codecs       any
	Extras       map[string]any
}

func (c *CallingNamespace) Dial(params CallingNamespaceDialParams) (map[string]any, error) {
	body := map[string]any{}
	if params.From != nil {
		body["from"] = params.From
	}
	if params.To != nil {
		body["to"] = params.To
	}
	if params.Url != nil {
		body["url"] = params.Url
	}
	if params.Swml != nil {
		body["swml"] = params.Swml
	}
	if params.CallerId != nil {
		body["caller_id"] = params.CallerId
	}
	if params.FallbackUrl != nil {
		body["fallback_url"] = params.FallbackUrl
	}
	if params.StatusUrl != nil {
		body["status_url"] = params.StatusUrl
	}
	if params.StatusEvents != nil {
		body["status_events"] = params.StatusEvents
	}
	if params.UrlMethod != nil {
		body["url_method"] = params.UrlMethod
	}
	if params.Codecs != nil {
		body["codecs"] = params.Codecs
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("dial", "", body)
}

// CallingNamespaceUpdateParams holds the named optional parameters for CallingNamespace.Update.
type CallingNamespaceUpdateParams struct {
	Id          any
	Url         any
	Swml        any
	FallbackUrl any
	Status      any
	StatusUrl   any
	Extras      map[string]any
}

func (c *CallingNamespace) Update(params CallingNamespaceUpdateParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Id != nil {
		body["id"] = params.Id
	}
	if params.Url != nil {
		body["url"] = params.Url
	}
	if params.Swml != nil {
		body["swml"] = params.Swml
	}
	if params.FallbackUrl != nil {
		body["fallback_url"] = params.FallbackUrl
	}
	if params.Status != nil {
		body["status"] = params.Status
	}
	if params.StatusUrl != nil {
		body["status_url"] = params.StatusUrl
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("update", "", body)
}

// CallingNamespaceEndParams holds the named optional parameters for CallingNamespace.End.
type CallingNamespaceEndParams struct {
	Reason any
	Extras map[string]any
}

func (c *CallingNamespace) End(callID string, params CallingNamespaceEndParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Reason != nil {
		body["reason"] = params.Reason
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.end", callID, body)
}

// CallingNamespaceAIHoldParams holds the named optional parameters for CallingNamespace.AIHold.
type CallingNamespaceAIHoldParams struct {
	Timeout any
	Prompt  any
	Extras  map[string]any
}

func (c *CallingNamespace) AIHold(callID string, params CallingNamespaceAIHoldParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Timeout != nil {
		body["timeout"] = params.Timeout
	}
	if params.Prompt != nil {
		body["prompt"] = params.Prompt
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.ai_hold", callID, body)
}

// CallingNamespaceAIUnholdParams holds the named optional parameters for CallingNamespace.AIUnhold.
type CallingNamespaceAIUnholdParams struct {
	Prompt any
	Extras map[string]any
}

func (c *CallingNamespace) AIUnhold(callID string, params CallingNamespaceAIUnholdParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Prompt != nil {
		body["prompt"] = params.Prompt
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.ai_unhold", callID, body)
}

// CallingNamespaceAIMessageParams holds the named optional parameters for CallingNamespace.AIMessage.
type CallingNamespaceAIMessageParams struct {
	Role        any
	MessageText any
	Reset       any
	GlobalData  any
	Extras      map[string]any
}

func (c *CallingNamespace) AIMessage(callID string, params CallingNamespaceAIMessageParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Role != nil {
		body["role"] = params.Role
	}
	if params.MessageText != nil {
		body["message_text"] = params.MessageText
	}
	if params.Reset != nil {
		body["reset"] = params.Reset
	}
	if params.GlobalData != nil {
		body["global_data"] = params.GlobalData
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.ai_message", callID, body)
}

// CallingNamespaceLiveTranscribeParams holds the named optional parameters for CallingNamespace.LiveTranscribe.
type CallingNamespaceLiveTranscribeParams struct {
	Action any
	Extras map[string]any
}

func (c *CallingNamespace) LiveTranscribe(callID string, params CallingNamespaceLiveTranscribeParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Action != nil {
		body["action"] = params.Action
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.live_transcribe", callID, body)
}

// CallingNamespaceLiveTranslateParams holds the named optional parameters for CallingNamespace.LiveTranslate.
type CallingNamespaceLiveTranslateParams struct {
	Action    any
	StatusUrl any
	Extras    map[string]any
}

func (c *CallingNamespace) LiveTranslate(callID string, params CallingNamespaceLiveTranslateParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Action != nil {
		body["action"] = params.Action
	}
	if params.StatusUrl != nil {
		body["status_url"] = params.StatusUrl
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.live_translate", callID, body)
}

// CallingNamespaceTransferParams holds the named optional parameters for CallingNamespace.Transfer.
type CallingNamespaceTransferParams struct {
	Dest   any
	Extras map[string]any
}

func (c *CallingNamespace) Transfer(callID string, params CallingNamespaceTransferParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Dest != nil {
		body["dest"] = params.Dest
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.transfer", callID, body)
}

// CallingNamespaceUserEventParams holds the named optional parameters for CallingNamespace.UserEvent.
type CallingNamespaceUserEventParams struct {
	Event  any
	Extras map[string]any
}

func (c *CallingNamespace) UserEvent(callID string, params CallingNamespaceUserEventParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Event != nil {
		body["event"] = params.Event
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.user_event", callID, body)
}

// CallingNamespaceDisconnectParams holds the named optional parameters for CallingNamespace.Disconnect.
type CallingNamespaceDisconnectParams struct {
	Extras map[string]any
}

func (c *CallingNamespace) Disconnect(callID string, params CallingNamespaceDisconnectParams) (map[string]any, error) {
	body := map[string]any{}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.disconnect", callID, body)
}

// CallingNamespacePlayParams holds the named optional parameters for CallingNamespace.Play.
type CallingNamespacePlayParams struct {
	Play      any
	ControlId any
	Volume    any
	Direction any
	Loop      any
	StatusUrl any
	Extras    map[string]any
}

func (c *CallingNamespace) Play(callID string, params CallingNamespacePlayParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Play != nil {
		body["play"] = params.Play
	}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	if params.Volume != nil {
		body["volume"] = params.Volume
	}
	if params.Direction != nil {
		body["direction"] = params.Direction
	}
	if params.Loop != nil {
		body["loop"] = params.Loop
	}
	if params.StatusUrl != nil {
		body["status_url"] = params.StatusUrl
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.play", callID, body)
}

// CallingNamespacePlayPauseParams holds the named optional parameters for CallingNamespace.PlayPause.
type CallingNamespacePlayPauseParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) PlayPause(callID string, params CallingNamespacePlayPauseParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.play.pause", callID, body)
}

// CallingNamespacePlayResumeParams holds the named optional parameters for CallingNamespace.PlayResume.
type CallingNamespacePlayResumeParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) PlayResume(callID string, params CallingNamespacePlayResumeParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.play.resume", callID, body)
}

// CallingNamespacePlayStopParams holds the named optional parameters for CallingNamespace.PlayStop.
type CallingNamespacePlayStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) PlayStop(callID string, params CallingNamespacePlayStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.play.stop", callID, body)
}

// CallingNamespacePlayVolumeParams holds the named optional parameters for CallingNamespace.PlayVolume.
type CallingNamespacePlayVolumeParams struct {
	ControlId any
	Volume    any
	Extras    map[string]any
}

func (c *CallingNamespace) PlayVolume(callID string, params CallingNamespacePlayVolumeParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	if params.Volume != nil {
		body["volume"] = params.Volume
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.play.volume", callID, body)
}

// CallingNamespaceRecordParams holds the named optional parameters for CallingNamespace.Record.
type CallingNamespaceRecordParams struct {
	ControlId any
	Audio     any
	StatusUrl any
	Extras    map[string]any
}

func (c *CallingNamespace) Record(callID string, params CallingNamespaceRecordParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	if params.Audio != nil {
		body["audio"] = params.Audio
	}
	if params.StatusUrl != nil {
		body["status_url"] = params.StatusUrl
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.record", callID, body)
}

// CallingNamespaceRecordPauseParams holds the named optional parameters for CallingNamespace.RecordPause.
type CallingNamespaceRecordPauseParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) RecordPause(callID string, params CallingNamespaceRecordPauseParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.record.pause", callID, body)
}

// CallingNamespaceRecordResumeParams holds the named optional parameters for CallingNamespace.RecordResume.
type CallingNamespaceRecordResumeParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) RecordResume(callID string, params CallingNamespaceRecordResumeParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.record.resume", callID, body)
}

// CallingNamespaceRecordStopParams holds the named optional parameters for CallingNamespace.RecordStop.
type CallingNamespaceRecordStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) RecordStop(callID string, params CallingNamespaceRecordStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.record.stop", callID, body)
}

// CallingNamespaceCollectParams holds the named optional parameters for CallingNamespace.Collect.
type CallingNamespaceCollectParams struct {
	ControlId      any
	InitialTimeout any
	Digits         any
	Speech         any
	Continuous     any
	PartialResults any
	Extras         map[string]any
}

func (c *CallingNamespace) Collect(callID string, params CallingNamespaceCollectParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	if params.InitialTimeout != nil {
		body["initial_timeout"] = params.InitialTimeout
	}
	if params.Digits != nil {
		body["digits"] = params.Digits
	}
	if params.Speech != nil {
		body["speech"] = params.Speech
	}
	if params.Continuous != nil {
		body["continuous"] = params.Continuous
	}
	if params.PartialResults != nil {
		body["partial_results"] = params.PartialResults
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.collect", callID, body)
}

// CallingNamespaceCollectStopParams holds the named optional parameters for CallingNamespace.CollectStop.
type CallingNamespaceCollectStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) CollectStop(callID string, params CallingNamespaceCollectStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.collect.stop", callID, body)
}

// CallingNamespaceCollectStartInputTimersParams holds the named optional parameters for CallingNamespace.CollectStartInputTimers.
type CallingNamespaceCollectStartInputTimersParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) CollectStartInputTimers(callID string, params CallingNamespaceCollectStartInputTimersParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.collect.start_input_timers", callID, body)
}

// CallingNamespaceDetectParams holds the named optional parameters for CallingNamespace.Detect.
type CallingNamespaceDetectParams struct {
	Detect    any
	ControlId any
	Timeout   any
	Extras    map[string]any
}

func (c *CallingNamespace) Detect(callID string, params CallingNamespaceDetectParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Detect != nil {
		body["detect"] = params.Detect
	}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	if params.Timeout != nil {
		body["timeout"] = params.Timeout
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.detect", callID, body)
}

// CallingNamespaceDetectStopParams holds the named optional parameters for CallingNamespace.DetectStop.
type CallingNamespaceDetectStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) DetectStop(callID string, params CallingNamespaceDetectStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.detect.stop", callID, body)
}

// CallingNamespaceTapParams holds the named optional parameters for CallingNamespace.Tap.
type CallingNamespaceTapParams struct {
	Tap       any
	Device    any
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) Tap(callID string, params CallingNamespaceTapParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Tap != nil {
		body["tap"] = params.Tap
	}
	if params.Device != nil {
		body["device"] = params.Device
	}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.tap", callID, body)
}

// CallingNamespaceTapStopParams holds the named optional parameters for CallingNamespace.TapStop.
type CallingNamespaceTapStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) TapStop(callID string, params CallingNamespaceTapStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.tap.stop", callID, body)
}

// CallingNamespaceStreamParams holds the named optional parameters for CallingNamespace.Stream.
type CallingNamespaceStreamParams struct {
	Url                      any
	ControlId                any
	Codec                    any
	Track                    any
	AuthorizationBearerToken any
	CustomParameters         any
	Extras                   map[string]any
}

func (c *CallingNamespace) Stream(callID string, params CallingNamespaceStreamParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Url != nil {
		body["url"] = params.Url
	}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	if params.Codec != nil {
		body["codec"] = params.Codec
	}
	if params.Track != nil {
		body["track"] = params.Track
	}
	if params.AuthorizationBearerToken != nil {
		body["authorization_bearer_token"] = params.AuthorizationBearerToken
	}
	if params.CustomParameters != nil {
		body["custom_parameters"] = params.CustomParameters
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.stream", callID, body)
}

// CallingNamespaceStreamStopParams holds the named optional parameters for CallingNamespace.StreamStop.
type CallingNamespaceStreamStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) StreamStop(callID string, params CallingNamespaceStreamStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.stream.stop", callID, body)
}

// CallingNamespaceDenoiseParams holds the named optional parameters for CallingNamespace.Denoise.
type CallingNamespaceDenoiseParams struct {
	Extras map[string]any
}

func (c *CallingNamespace) Denoise(callID string, params CallingNamespaceDenoiseParams) (map[string]any, error) {
	body := map[string]any{}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.denoise", callID, body)
}

// CallingNamespaceDenoiseStopParams holds the named optional parameters for CallingNamespace.DenoiseStop.
type CallingNamespaceDenoiseStopParams struct {
	Extras map[string]any
}

func (c *CallingNamespace) DenoiseStop(callID string, params CallingNamespaceDenoiseStopParams) (map[string]any, error) {
	body := map[string]any{}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.denoise.stop", callID, body)
}

// CallingNamespaceTranscribeParams holds the named optional parameters for CallingNamespace.Transcribe.
type CallingNamespaceTranscribeParams struct {
	ControlId any
	StatusUrl any
	Extras    map[string]any
}

func (c *CallingNamespace) Transcribe(callID string, params CallingNamespaceTranscribeParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	if params.StatusUrl != nil {
		body["status_url"] = params.StatusUrl
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.transcribe", callID, body)
}

// CallingNamespaceTranscribeStopParams holds the named optional parameters for CallingNamespace.TranscribeStop.
type CallingNamespaceTranscribeStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) TranscribeStop(callID string, params CallingNamespaceTranscribeStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.transcribe.stop", callID, body)
}

// CallingNamespaceAIStopParams holds the named optional parameters for CallingNamespace.AIStop.
type CallingNamespaceAIStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) AIStop(callID string, params CallingNamespaceAIStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.ai.stop", callID, body)
}

// CallingNamespaceSendFaxStopParams holds the named optional parameters for CallingNamespace.SendFaxStop.
type CallingNamespaceSendFaxStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) SendFaxStop(callID string, params CallingNamespaceSendFaxStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.send_fax.stop", callID, body)
}

// CallingNamespaceReceiveFaxStopParams holds the named optional parameters for CallingNamespace.ReceiveFaxStop.
type CallingNamespaceReceiveFaxStopParams struct {
	ControlId any
	Extras    map[string]any
}

func (c *CallingNamespace) ReceiveFaxStop(callID string, params CallingNamespaceReceiveFaxStopParams) (map[string]any, error) {
	body := map[string]any{}
	if params.ControlId != nil {
		body["control_id"] = params.ControlId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.receive_fax.stop", callID, body)
}

// CallingNamespaceReferParams holds the named optional parameters for CallingNamespace.Refer.
type CallingNamespaceReferParams struct {
	Device    any
	StatusUrl any
	Extras    map[string]any
}

func (c *CallingNamespace) Refer(callID string, params CallingNamespaceReferParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Device != nil {
		body["device"] = params.Device
	}
	if params.StatusUrl != nil {
		body["status_url"] = params.StatusUrl
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return c.execute("calling.refer", callID, body)
}
