// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "calling" namespace spec.

package namespaces

// CallingNamespace is generated from the command-dispatch x-sdk-resource "Calling" (calling spec).
type CallingNamespace struct {
	Resource
}

// NewCallingNamespace constructs a CallingNamespace bound to base path "/api/calling/calls".
func NewCallingNamespace(client HTTPClient) *CallingNamespace {
	return &CallingNamespace{Resource{HTTP: client, Base: "/api/calling/calls"}}
}

func (c *CallingNamespace) execute(command string, callID string, params map[string]any) (map[string]any, error) {
	body := map[string]any{"command": command, "params": params}
	if callID != "" {
		body["id"] = callID
	}
	return c.HTTP.Post(c.Base, body, nil)
}

func (c *CallingNamespace) Dial(params map[string]any) (map[string]any, error) {
	return c.execute("dial", "", params)
}

func (c *CallingNamespace) Update(params map[string]any) (map[string]any, error) {
	return c.execute("update", "", params)
}

func (c *CallingNamespace) End(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.end", callID, params)
}

func (c *CallingNamespace) AIHold(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.ai_hold", callID, params)
}

func (c *CallingNamespace) AIUnhold(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.ai_unhold", callID, params)
}

func (c *CallingNamespace) AIMessage(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.ai_message", callID, params)
}

func (c *CallingNamespace) LiveTranscribe(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.live_transcribe", callID, params)
}

func (c *CallingNamespace) LiveTranslate(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.live_translate", callID, params)
}

func (c *CallingNamespace) Transfer(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.transfer", callID, params)
}

func (c *CallingNamespace) UserEvent(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.user_event", callID, params)
}

func (c *CallingNamespace) Disconnect(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.disconnect", callID, params)
}

func (c *CallingNamespace) Play(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.play", callID, params)
}

func (c *CallingNamespace) PlayPause(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.play.pause", callID, params)
}

func (c *CallingNamespace) PlayResume(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.play.resume", callID, params)
}

func (c *CallingNamespace) PlayStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.play.stop", callID, params)
}

func (c *CallingNamespace) PlayVolume(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.play.volume", callID, params)
}

func (c *CallingNamespace) Record(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.record", callID, params)
}

func (c *CallingNamespace) RecordPause(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.record.pause", callID, params)
}

func (c *CallingNamespace) RecordResume(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.record.resume", callID, params)
}

func (c *CallingNamespace) RecordStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.record.stop", callID, params)
}

func (c *CallingNamespace) Collect(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.collect", callID, params)
}

func (c *CallingNamespace) CollectStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.collect.stop", callID, params)
}

func (c *CallingNamespace) CollectStartInputTimers(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.collect.start_input_timers", callID, params)
}

func (c *CallingNamespace) Detect(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.detect", callID, params)
}

func (c *CallingNamespace) DetectStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.detect.stop", callID, params)
}

func (c *CallingNamespace) Tap(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.tap", callID, params)
}

func (c *CallingNamespace) TapStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.tap.stop", callID, params)
}

func (c *CallingNamespace) Stream(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.stream", callID, params)
}

func (c *CallingNamespace) StreamStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.stream.stop", callID, params)
}

func (c *CallingNamespace) Denoise(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.denoise", callID, params)
}

func (c *CallingNamespace) DenoiseStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.denoise.stop", callID, params)
}

func (c *CallingNamespace) Transcribe(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.transcribe", callID, params)
}

func (c *CallingNamespace) TranscribeStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.transcribe.stop", callID, params)
}

func (c *CallingNamespace) AIStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.ai.stop", callID, params)
}

func (c *CallingNamespace) SendFaxStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.send_fax.stop", callID, params)
}

func (c *CallingNamespace) ReceiveFaxStop(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.receive_fax.stop", callID, params)
}

func (c *CallingNamespace) Refer(callID string, params map[string]any) (map[string]any, error) {
	return c.execute("calling.refer", callID, params)
}
