// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "calling" namespace spec.

package namespaces

import "context"

// CallingNamespace is a client for the "Calling" resource of the SignalWire calling API (command-dispatch endpoint).
type CallingNamespace struct {
	Resource
}

// NewCallingNamespace constructs a CallingNamespace bound to base path "/api/calling/calls".
func NewCallingNamespace(client HTTPClient) *CallingNamespace {
	return &CallingNamespace{Resource{HTTP: client, Base: "/api/calling/calls"}}
}

func (c *CallingNamespace) execute(ctx context.Context, command string, callID string, params map[string]any, opts ...*RequestOptions) (map[string]any, error) {
	body := map[string]any{"command": command, "params": params}
	if callID != "" {
		body["id"] = callID
	}
	return c.HTTP.Post(ctx, c.Base, body, nil, opts...)
}

// CallingNamespaceDialParams holds the named optional parameters for CallingNamespace.Dial.
type CallingNamespaceDialParams struct {
	From         string
	To           string
	CallerID     *string
	FallbackURL  *string
	StatusURL    *string
	StatusEvents []string
	URLMethod    *string
	URL          *string
	Codecs       any
	Swml         *SWMLObject
	Extras       map[string]any
}

func (c *CallingNamespace) Dial(ctx context.Context, params CallingNamespaceDialParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["from"] = params.From
	body["to"] = params.To
	if params.CallerID != nil {
		body["caller_id"] = params.CallerID
	}
	if params.FallbackURL != nil {
		body["fallback_url"] = params.FallbackURL
	}
	if params.StatusURL != nil {
		body["status_url"] = params.StatusURL
	}
	if params.StatusEvents != nil {
		body["status_events"] = params.StatusEvents
	}
	if params.URLMethod != nil {
		body["url_method"] = params.URLMethod
	}
	if params.URL != nil {
		body["url"] = params.URL
	}
	if params.Codecs != nil {
		body["codecs"] = params.Codecs
	}
	if params.Swml != nil {
		body["swml"] = params.Swml
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "dial", "", body, opts...))
}

// CallingNamespaceUpdateParams holds the named optional parameters for CallingNamespace.Update.
type CallingNamespaceUpdateParams struct {
	ID          Uuid
	FallbackURL *string
	Status      *string
	StatusURL   *string
	URL         *string
	Swml        *SWMLObject
	Extras      map[string]any
}

func (c *CallingNamespace) Update(ctx context.Context, params CallingNamespaceUpdateParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["id"] = params.ID
	if params.FallbackURL != nil {
		body["fallback_url"] = params.FallbackURL
	}
	if params.Status != nil {
		body["status"] = params.Status
	}
	if params.StatusURL != nil {
		body["status_url"] = params.StatusURL
	}
	if params.URL != nil {
		body["url"] = params.URL
	}
	if params.Swml != nil {
		body["swml"] = params.Swml
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "update", "", body, opts...))
}

// CallingNamespaceEndParams holds the named optional parameters for CallingNamespace.End.
type CallingNamespaceEndParams struct {
	Reason *HangupReason
	Extras map[string]any
}

func (c *CallingNamespace) End(ctx context.Context, callID string, params CallingNamespaceEndParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Reason != nil {
		body["reason"] = params.Reason
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.end", callID, body, opts...))
}

// CallingNamespaceAIHoldParams holds the named optional parameters for CallingNamespace.AIHold.
type CallingNamespaceAIHoldParams struct {
	Timeout *int
	Prompt  *string
	Extras  map[string]any
}

func (c *CallingNamespace) AIHold(ctx context.Context, callID string, params CallingNamespaceAIHoldParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Timeout != nil {
		body["timeout"] = params.Timeout
	}
	if params.Prompt != nil {
		body["prompt"] = params.Prompt
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.ai_hold", callID, body, opts...))
}

// CallingNamespaceAIUnholdParams holds the named optional parameters for CallingNamespace.AIUnhold.
type CallingNamespaceAIUnholdParams struct {
	Prompt *string
	Extras map[string]any
}

func (c *CallingNamespace) AIUnhold(ctx context.Context, callID string, params CallingNamespaceAIUnholdParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Prompt != nil {
		body["prompt"] = params.Prompt
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.ai_unhold", callID, body, opts...))
}

// CallingNamespaceAIMessageParams holds the named optional parameters for CallingNamespace.AIMessage.
type CallingNamespaceAIMessageParams struct {
	Role        *string
	MessageText *string
	Reset       *CallAIMessageResetParams
	GlobalData  map[string]any
	Extras      map[string]any
}

func (c *CallingNamespace) AIMessage(ctx context.Context, callID string, params CallingNamespaceAIMessageParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Role != nil {
		body["role"] = params.Role
	}
	if params.MessageText != nil {
		body["message_text"] = params.MessageText
	}
	if params.Reset != nil {
		body["reset"] = params.Reset
	}
	if params.GlobalData != nil {
		body["global_data"] = params.GlobalData
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.ai_message", callID, body, opts...))
}

// CallingNamespaceLiveTranscribeParams holds the named optional parameters for CallingNamespace.LiveTranscribe.
type CallingNamespaceLiveTranscribeParams struct {
	Action any
	Extras map[string]any
}

func (c *CallingNamespace) LiveTranscribe(ctx context.Context, callID string, params CallingNamespaceLiveTranscribeParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Action != nil {
		body["action"] = params.Action
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.live_transcribe", callID, body, opts...))
}

// CallingNamespaceLiveTranslateParams holds the named optional parameters for CallingNamespace.LiveTranslate.
type CallingNamespaceLiveTranslateParams struct {
	Action    any
	StatusURL *string
	Extras    map[string]any
}

func (c *CallingNamespace) LiveTranslate(ctx context.Context, callID string, params CallingNamespaceLiveTranslateParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Action != nil {
		body["action"] = params.Action
	}
	if params.StatusURL != nil {
		body["status_url"] = params.StatusURL
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.live_translate", callID, body, opts...))
}

// CallingNamespaceTransferParams holds the named optional parameters for CallingNamespace.Transfer.
type CallingNamespaceTransferParams struct {
	Dest   any
	Extras map[string]any
}

func (c *CallingNamespace) Transfer(ctx context.Context, callID string, params CallingNamespaceTransferParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Dest != nil {
		body["dest"] = params.Dest
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.transfer", callID, body, opts...))
}

// CallingNamespaceUserEventParams holds the named optional parameters for CallingNamespace.UserEvent.
type CallingNamespaceUserEventParams struct {
	Event  map[string]any
	Extras map[string]any
}

func (c *CallingNamespace) UserEvent(ctx context.Context, callID string, params CallingNamespaceUserEventParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Event != nil {
		body["event"] = params.Event
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.user_event", callID, body, opts...))
}

// CallingNamespaceDisconnectParams holds the named optional parameters for CallingNamespace.Disconnect.
type CallingNamespaceDisconnectParams struct {
	Extras map[string]any
}

func (c *CallingNamespace) Disconnect(ctx context.Context, callID string, params CallingNamespaceDisconnectParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.disconnect", callID, body, opts...))
}

// CallingNamespacePlayParams holds the named optional parameters for CallingNamespace.Play.
type CallingNamespacePlayParams struct {
	Play      []map[string]any
	ControlID *string
	Volume    *float64
	Direction *string
	Loop      *int
	StatusURL *string
	Extras    map[string]any
}

func (c *CallingNamespace) Play(ctx context.Context, callID string, params CallingNamespacePlayParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Play != nil {
		body["play"] = params.Play
	}
	if params.ControlID != nil {
		body["control_id"] = params.ControlID
	}
	if params.Volume != nil {
		body["volume"] = params.Volume
	}
	if params.Direction != nil {
		body["direction"] = params.Direction
	}
	if params.Loop != nil {
		body["loop"] = params.Loop
	}
	if params.StatusURL != nil {
		body["status_url"] = params.StatusURL
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.play", callID, body, opts...))
}

// CallingNamespacePlayPauseParams holds the named optional parameters for CallingNamespace.PlayPause.
type CallingNamespacePlayPauseParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) PlayPause(ctx context.Context, callID string, params CallingNamespacePlayPauseParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.play.pause", callID, body, opts...))
}

// CallingNamespacePlayResumeParams holds the named optional parameters for CallingNamespace.PlayResume.
type CallingNamespacePlayResumeParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) PlayResume(ctx context.Context, callID string, params CallingNamespacePlayResumeParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.play.resume", callID, body, opts...))
}

// CallingNamespacePlayStopParams holds the named optional parameters for CallingNamespace.PlayStop.
type CallingNamespacePlayStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) PlayStop(ctx context.Context, callID string, params CallingNamespacePlayStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.play.stop", callID, body, opts...))
}

// CallingNamespacePlayVolumeParams holds the named optional parameters for CallingNamespace.PlayVolume.
type CallingNamespacePlayVolumeParams struct {
	ControlID string
	Volume    float64
	Extras    map[string]any
}

func (c *CallingNamespace) PlayVolume(ctx context.Context, callID string, params CallingNamespacePlayVolumeParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	body["volume"] = params.Volume
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.play.volume", callID, body, opts...))
}

// CallingNamespaceRecordParams holds the named optional parameters for CallingNamespace.Record.
type CallingNamespaceRecordParams struct {
	ControlID *string
	Audio     map[string]any
	StatusURL *string
	Extras    map[string]any
}

func (c *CallingNamespace) Record(ctx context.Context, callID string, params CallingNamespaceRecordParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.ControlID != nil {
		body["control_id"] = params.ControlID
	}
	if params.Audio != nil {
		body["audio"] = params.Audio
	}
	if params.StatusURL != nil {
		body["status_url"] = params.StatusURL
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.record", callID, body, opts...))
}

// CallingNamespaceRecordPauseParams holds the named optional parameters for CallingNamespace.RecordPause.
type CallingNamespaceRecordPauseParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) RecordPause(ctx context.Context, callID string, params CallingNamespaceRecordPauseParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.record.pause", callID, body, opts...))
}

// CallingNamespaceRecordResumeParams holds the named optional parameters for CallingNamespace.RecordResume.
type CallingNamespaceRecordResumeParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) RecordResume(ctx context.Context, callID string, params CallingNamespaceRecordResumeParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.record.resume", callID, body, opts...))
}

// CallingNamespaceRecordStopParams holds the named optional parameters for CallingNamespace.RecordStop.
type CallingNamespaceRecordStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) RecordStop(ctx context.Context, callID string, params CallingNamespaceRecordStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.record.stop", callID, body, opts...))
}

// CallingNamespaceCollectParams holds the named optional parameters for CallingNamespace.Collect.
type CallingNamespaceCollectParams struct {
	ControlID      *string
	InitialTimeout *float64
	Digits         map[string]any
	Speech         map[string]any
	Continuous     *bool
	PartialResults *bool
	Extras         map[string]any
}

func (c *CallingNamespace) Collect(ctx context.Context, callID string, params CallingNamespaceCollectParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.ControlID != nil {
		body["control_id"] = params.ControlID
	}
	if params.InitialTimeout != nil {
		body["initial_timeout"] = params.InitialTimeout
	}
	if params.Digits != nil {
		body["digits"] = params.Digits
	}
	if params.Speech != nil {
		body["speech"] = params.Speech
	}
	if params.Continuous != nil {
		body["continuous"] = params.Continuous
	}
	if params.PartialResults != nil {
		body["partial_results"] = params.PartialResults
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.collect", callID, body, opts...))
}

// CallingNamespaceCollectStopParams holds the named optional parameters for CallingNamespace.CollectStop.
type CallingNamespaceCollectStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) CollectStop(ctx context.Context, callID string, params CallingNamespaceCollectStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.collect.stop", callID, body, opts...))
}

// CallingNamespaceCollectStartInputTimersParams holds the named optional parameters for CallingNamespace.CollectStartInputTimers.
type CallingNamespaceCollectStartInputTimersParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) CollectStartInputTimers(ctx context.Context, callID string, params CallingNamespaceCollectStartInputTimersParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.collect.start_input_timers", callID, body, opts...))
}

// CallingNamespaceDetectParams holds the named optional parameters for CallingNamespace.Detect.
type CallingNamespaceDetectParams struct {
	Detect    map[string]any
	ControlID *string
	Timeout   *float64
	Extras    map[string]any
}

func (c *CallingNamespace) Detect(ctx context.Context, callID string, params CallingNamespaceDetectParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Detect != nil {
		body["detect"] = params.Detect
	}
	if params.ControlID != nil {
		body["control_id"] = params.ControlID
	}
	if params.Timeout != nil {
		body["timeout"] = params.Timeout
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.detect", callID, body, opts...))
}

// CallingNamespaceDetectStopParams holds the named optional parameters for CallingNamespace.DetectStop.
type CallingNamespaceDetectStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) DetectStop(ctx context.Context, callID string, params CallingNamespaceDetectStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.detect.stop", callID, body, opts...))
}

// CallingNamespaceTapParams holds the named optional parameters for CallingNamespace.Tap.
type CallingNamespaceTapParams struct {
	Tap       map[string]any
	Device    map[string]any
	ControlID *string
	Extras    map[string]any
}

func (c *CallingNamespace) Tap(ctx context.Context, callID string, params CallingNamespaceTapParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Tap != nil {
		body["tap"] = params.Tap
	}
	if params.Device != nil {
		body["device"] = params.Device
	}
	if params.ControlID != nil {
		body["control_id"] = params.ControlID
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.tap", callID, body, opts...))
}

// CallingNamespaceTapStopParams holds the named optional parameters for CallingNamespace.TapStop.
type CallingNamespaceTapStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) TapStop(ctx context.Context, callID string, params CallingNamespaceTapStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.tap.stop", callID, body, opts...))
}

// CallingNamespaceStreamParams holds the named optional parameters for CallingNamespace.Stream.
type CallingNamespaceStreamParams struct {
	URL                      string
	ControlID                *string
	Codec                    *string
	Track                    *string
	AuthorizationBearerToken *string
	CustomParameters         map[string]any
	Extras                   map[string]any
}

func (c *CallingNamespace) Stream(ctx context.Context, callID string, params CallingNamespaceStreamParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["url"] = params.URL
	if params.ControlID != nil {
		body["control_id"] = params.ControlID
	}
	if params.Codec != nil {
		body["codec"] = params.Codec
	}
	if params.Track != nil {
		body["track"] = params.Track
	}
	if params.AuthorizationBearerToken != nil {
		body["authorization_bearer_token"] = params.AuthorizationBearerToken
	}
	if params.CustomParameters != nil {
		body["custom_parameters"] = params.CustomParameters
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.stream", callID, body, opts...))
}

// CallingNamespaceStreamStopParams holds the named optional parameters for CallingNamespace.StreamStop.
type CallingNamespaceStreamStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) StreamStop(ctx context.Context, callID string, params CallingNamespaceStreamStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.stream.stop", callID, body, opts...))
}

// CallingNamespaceDenoiseParams holds the named optional parameters for CallingNamespace.Denoise.
type CallingNamespaceDenoiseParams struct {
	Extras map[string]any
}

func (c *CallingNamespace) Denoise(ctx context.Context, callID string, params CallingNamespaceDenoiseParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.denoise", callID, body, opts...))
}

// CallingNamespaceDenoiseStopParams holds the named optional parameters for CallingNamespace.DenoiseStop.
type CallingNamespaceDenoiseStopParams struct {
	Extras map[string]any
}

func (c *CallingNamespace) DenoiseStop(ctx context.Context, callID string, params CallingNamespaceDenoiseStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.denoise.stop", callID, body, opts...))
}

// CallingNamespaceTranscribeParams holds the named optional parameters for CallingNamespace.Transcribe.
type CallingNamespaceTranscribeParams struct {
	ControlID *string
	StatusURL *string
	Extras    map[string]any
}

func (c *CallingNamespace) Transcribe(ctx context.Context, callID string, params CallingNamespaceTranscribeParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.ControlID != nil {
		body["control_id"] = params.ControlID
	}
	if params.StatusURL != nil {
		body["status_url"] = params.StatusURL
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.transcribe", callID, body, opts...))
}

// CallingNamespaceTranscribeStopParams holds the named optional parameters for CallingNamespace.TranscribeStop.
type CallingNamespaceTranscribeStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) TranscribeStop(ctx context.Context, callID string, params CallingNamespaceTranscribeStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.transcribe.stop", callID, body, opts...))
}

// CallingNamespaceAIStopParams holds the named optional parameters for CallingNamespace.AIStop.
type CallingNamespaceAIStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) AIStop(ctx context.Context, callID string, params CallingNamespaceAIStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.ai.stop", callID, body, opts...))
}

// CallingNamespaceSendFaxStopParams holds the named optional parameters for CallingNamespace.SendFaxStop.
type CallingNamespaceSendFaxStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) SendFaxStop(ctx context.Context, callID string, params CallingNamespaceSendFaxStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.send_fax.stop", callID, body, opts...))
}

// CallingNamespaceReceiveFaxStopParams holds the named optional parameters for CallingNamespace.ReceiveFaxStop.
type CallingNamespaceReceiveFaxStopParams struct {
	ControlID string
	Extras    map[string]any
}

func (c *CallingNamespace) ReceiveFaxStop(ctx context.Context, callID string, params CallingNamespaceReceiveFaxStopParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	body["control_id"] = params.ControlID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.receive_fax.stop", callID, body, opts...))
}

// CallingNamespaceReferParams holds the named optional parameters for CallingNamespace.Refer.
type CallingNamespaceReferParams struct {
	Device    map[string]any
	StatusURL *string
	Extras    map[string]any
}

func (c *CallingNamespace) Refer(ctx context.Context, callID string, params CallingNamespaceReferParams, opts ...*RequestOptions) (*CallResponse, error) {
	body := map[string]any{}
	if params.Device != nil {
		body["device"] = params.Device
	}
	if params.StatusURL != nil {
		body["status_url"] = params.StatusURL
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CallResponse](c.execute(ctx, "calling.refer", callID, body, opts...))
}
