// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "chat" namespace spec.

package namespaces

// ChatNamespace is generated from x-sdk-resource "Chat" in the chat spec.
type ChatNamespace struct {
	Resource
}

// NewChatNamespace constructs a ChatNamespace bound to base path "/api/chat/tokens".
func NewChatNamespace(client HTTPClient) *ChatNamespace {
	return &ChatNamespace{Resource{HTTP: client, Base: "/api/chat/tokens"}}
}

func (r *ChatNamespace) CreateToken(ttl any, channels any, memberId any, state any, extras map[string]any) (map[string]any, error) {
	body := map[string]any{}
	if ttl != nil {
		body["ttl"] = ttl
	}
	if channels != nil {
		body["channels"] = channels
	}
	if memberId != nil {
		body["member_id"] = memberId
	}
	if state != nil {
		body["state"] = state
	}
	mergeExtra(body, []map[string]any{extras})
	return r.HTTP.Post(r.Base, body, nil)
}
