// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "datasphere" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type Chunk struct {
	Text       string `json:"text,omitempty"`
	DocumentId docid  `json:"document_id,omitempty"`
}

type ChunkListResponse struct {
	Data  []ChunkResponse         `json:"data,omitempty"`
	Links ChunkPaginationResponse `json:"links,omitempty"`
}

type ChunkPaginationResponse struct {
	Self  string  `json:"self,omitempty"`
	First string  `json:"first,omitempty"`
	Next  *string `json:"next,omitempty"`
	Prev  *string `json:"prev,omitempty"`
}

type ChunkResponse struct {
	Id                   uuid        `json:"id,omitempty"`
	DatasphereDocumentId uuid        `json:"datasphere_document_id,omitempty"`
	ProjectId            uuid        `json:"project_id,omitempty"`
	Status               ChunkStatus `json:"status,omitempty"`
	Tags                 []string    `json:"tags,omitempty"`
	Content              string      `json:"content,omitempty"`
	CreatedAt            string      `json:"created_at,omitempty"`
	UpdatedAt            string      `json:"updated_at,omitempty"`
}

type ChunkStatus string

const (
	ChunkStatusSubmitted  ChunkStatus = "submitted"
	ChunkStatusInProgress ChunkStatus = "in_progress"
	ChunkStatusCompleted  ChunkStatus = "completed"
	ChunkStatusFailed     ChunkStatus = "failed"
)

type ChunkingStrategy string

const (
	ChunkingStrategySentence  ChunkingStrategy = "sentence"
	ChunkingStrategyParagraph ChunkingStrategy = "paragraph"
	ChunkingStrategyPage      ChunkingStrategy = "page"
	ChunkingStrategySliding   ChunkingStrategy = "sliding"
)

type CreateStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type Document struct {
	Id                   docid            `json:"id,omitempty"`
	Filename             string           `json:"filename,omitempty"`
	Status               DocumentStatus   `json:"status,omitempty"`
	Tags                 []string         `json:"tags,omitempty"`
	ChunkingStrategy     ChunkingStrategy `json:"chunking_strategy,omitempty"`
	MaxSentencesPerChunk any              `json:"max_sentences_per_chunk,omitempty"`
	SplitNewlines        any              `json:"split_newlines,omitempty"`
	OverlapSize          any              `json:"overlap_size,omitempty"`
	ChunkSize            any              `json:"chunk_size,omitempty"`
	NumberOfChunks       int              `json:"number_of_chunks,omitempty"`
	ChunksUri            string           `json:"chunks_uri,omitempty"`
	CreatedAt            string           `json:"created_at,omitempty"`
	UpdatedAt            string           `json:"updated_at,omitempty"`
}

type DocumentCreatePageRequest DocumentCreateRequestBase

type DocumentCreateParagraphRequest DocumentCreateRequestBase

type DocumentCreateRequest any

type DocumentCreateRequestBase struct {
	Url  string   `json:"url,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

type DocumentCreateSentenceRequest DocumentCreateRequestBase

type DocumentCreateSlidingRequest DocumentCreateRequestBase

type DocumentListResponse struct {
	Data  []Document         `json:"data,omitempty"`
	Links PaginationResponse `json:"links,omitempty"`
}

type DocumentSearchRequest struct {
	Tags        []string `json:"tags,omitempty"`
	DocumentId  *docid   `json:"document_id,omitempty"`
	QueryString string   `json:"query_string,omitempty"`
	Distance    *float64 `json:"distance,omitempty"`
	Count       *int     `json:"count,omitempty"`
	Language    *string  `json:"language,omitempty"`
	PosToExpand []string `json:"pos_to_expand,omitempty"`
	MaxSynonyms *int     `json:"max_synonyms,omitempty"`
}

type DocumentStatus string

const (
	DocumentStatusSubmitted  DocumentStatus = "submitted"
	DocumentStatusInProgress DocumentStatus = "in_progress"
	DocumentStatusCompleted  DocumentStatus = "completed"
	DocumentStatusFailed     DocumentStatus = "failed"
)

type DocumentUpdateRequest struct {
	Tags []string `json:"tags,omitempty"`
}

type ListStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type PaginationResponse struct {
	Self  string  `json:"self,omitempty"`
	First string  `json:"first,omitempty"`
	Next  *string `json:"next,omitempty"`
	Prev  *string `json:"prev,omitempty"`
}

type SearchResponse struct {
	Chunks []Chunk `json:"chunks,omitempty"`
}

type SearchStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type UpdateStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type docid string
