// Code generated by cmd/generate-rest-tests; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the "datasphere" namespace — regenerate:
//   go run ./cmd/generate-rest-tests
//
// Each route the SDK implements (captured from the real client by
// cmd/route-registry, joined to the spec operationId) gets a SUCCESS test (call
// it, assert method + matched_route on the mock journal) and an ERROR test (arm a
// 500, assert *rest.SignalWireRestError with StatusCode 500). The assertion
// oracle is the spec operationId — independent of the resource generator — so
// these catch SDK-vs-contract drift, not a generator self-snapshot.

package namespaces_test

import (
	"errors"
	"testing"

	"github.com/signalwire/signalwire-go/pkg/rest"
	"github.com/signalwire/signalwire-go/pkg/rest/internal/mocktest"
	"github.com/signalwire/signalwire-go/pkg/rest/namespaces"
)

func TestDatasphereGen_Documents_Create(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.Create(map[string]any{})
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "POST" {
		t.Errorf("method = %q want POST", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.create_document" {
		t.Errorf("matched_route = %v want datasphere.create_document", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_Create_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.create_document", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.Create(map[string]any{})
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestDatasphereGen_Documents_DeleteChunk(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.DeleteChunk("x-1", "x-1")
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "DELETE" {
		t.Errorf("method = %q want DELETE", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.delete_document_chunk" {
		t.Errorf("matched_route = %v want datasphere.delete_document_chunk", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_DeleteChunk_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.delete_document_chunk", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.DeleteChunk("x-1", "x-1")
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestDatasphereGen_Documents_Delete(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.Delete("x-1")
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "DELETE" {
		t.Errorf("method = %q want DELETE", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.delete_document" {
		t.Errorf("matched_route = %v want datasphere.delete_document", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_Delete_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.delete_document", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.Delete("x-1")
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestDatasphereGen_Documents_GetChunk(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.GetChunk("x-1", "x-1", nil)
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "GET" {
		t.Errorf("method = %q want GET", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.get_document_chunk" {
		t.Errorf("matched_route = %v want datasphere.get_document_chunk", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_GetChunk_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.get_document_chunk", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.GetChunk("x-1", "x-1", nil)
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestDatasphereGen_Documents_Get(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.Get("x-1")
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "GET" {
		t.Errorf("method = %q want GET", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.get_document" {
		t.Errorf("matched_route = %v want datasphere.get_document", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_Get_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.get_document", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.Get("x-1")
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestDatasphereGen_Documents_ListChunks(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.ListChunks("x-1", nil)
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "GET" {
		t.Errorf("method = %q want GET", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.list_document_chunks" {
		t.Errorf("matched_route = %v want datasphere.list_document_chunks", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_ListChunks_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.list_document_chunks", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.ListChunks("x-1", nil)
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestDatasphereGen_Documents_List(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.List(nil)
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "GET" {
		t.Errorf("method = %q want GET", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.list_documents" {
		t.Errorf("matched_route = %v want datasphere.list_documents", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_List_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.list_documents", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.List(nil)
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestDatasphereGen_Documents_Search(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.Search(namespaces.DatasphereDocumentsSearchParams{Extras: map[string]any{"query_string": "x-1"}})
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "POST" {
		t.Errorf("method = %q want POST", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.search_documents" {
		t.Errorf("matched_route = %v want datasphere.search_documents", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_Search_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.search_documents", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.Search(namespaces.DatasphereDocumentsSearchParams{Extras: map[string]any{"query_string": "x-1"}})
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestDatasphereGen_Documents_Update(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Datasphere.Documents.Update("x-1", map[string]any{"tags": "x-1"})
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "PATCH" {
		t.Errorf("method = %q want PATCH", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "datasphere.update_document" {
		t.Errorf("matched_route = %v want datasphere.update_document", j.MatchedRoute)
	}
}

func TestDatasphereGen_Documents_Update_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "datasphere.update_document", 500, map[string]any{"error": "x"})
	_, err := client.Datasphere.Documents.Update("x-1", map[string]any{"tags": "x-1"})
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}
