// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "datasphere" namespace spec.

package namespaces

// DatasphereDocuments is generated from x-sdk-resource "DatasphereDocuments" in the datasphere spec.
type DatasphereDocuments struct {
	*CrudResource
}

// NewDatasphereDocuments constructs a DatasphereDocuments bound to base path "/api/datasphere/documents".
func NewDatasphereDocuments(client HTTPClient) *DatasphereDocuments {
	return &DatasphereDocuments{NewCrudResource(client, "/api/datasphere/documents")}
}

// DatasphereDocumentsSearchParams holds the named optional parameters for DatasphereDocuments.Search.
type DatasphereDocumentsSearchParams struct {
	QueryString string
	Tags        []string
	DocumentId  *docid
	Distance    *float64
	Count       *int
	Language    *string
	PosToExpand []string
	MaxSynonyms *int
	Extras      map[string]any
}

func (r *DatasphereDocuments) Search(params DatasphereDocumentsSearchParams) (*SearchResponse, error) {
	body := map[string]any{}
	body["query_string"] = params.QueryString
	if params.Tags != nil {
		body["tags"] = params.Tags
	}
	if params.DocumentId != nil {
		body["document_id"] = params.DocumentId
	}
	if params.Distance != nil {
		body["distance"] = params.Distance
	}
	if params.Count != nil {
		body["count"] = params.Count
	}
	if params.Language != nil {
		body["language"] = params.Language
	}
	if params.PosToExpand != nil {
		body["pos_to_expand"] = params.PosToExpand
	}
	if params.MaxSynonyms != nil {
		body["max_synonyms"] = params.MaxSynonyms
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[SearchResponse](r.HTTP.Post(r.Path("search"), body, nil))
}

func (r *DatasphereDocuments) ListChunks(documentID string, params map[string]string) (*ChunkListResponse, error) {
	return decodeResult[ChunkListResponse](r.HTTP.Get(r.Path(documentID, "chunks"), params))
}

func (r *DatasphereDocuments) GetChunk(documentID string, chunkID string, params map[string]string) (*ChunkResponse, error) {
	return decodeResult[ChunkResponse](r.HTTP.Get(r.Path(documentID, "chunks", chunkID), params))
}

func (r *DatasphereDocuments) DeleteChunk(documentID string, chunkID string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(documentID, "chunks", chunkID))
}
