// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "fabric" namespace spec.

package namespaces

import "context"

// AliasAddresses is a client for the "AliasAddresses" resource of the SignalWire fabric API.
type AliasAddresses struct {
	*CrudResource
}

// NewAliasAddresses constructs a AliasAddresses bound to base path "/api/fabric/addresses/alias".
func NewAliasAddresses(client HTTPClient) *AliasAddresses {
	return &AliasAddresses{NewCrudResource(client, "/api/fabric/addresses/alias")}
}

// SIPAddresses is a client for the "SipAddresses" resource of the SignalWire fabric API.
type SIPAddresses struct {
	*CrudResource
}

// NewSIPAddresses constructs a SIPAddresses bound to base path "/api/fabric/addresses/sip".
func NewSIPAddresses(client HTTPClient) *SIPAddresses {
	return &SIPAddresses{NewCrudResource(client, "/api/fabric/addresses/sip")}
}

// PhoneNumberAddresses is a client for the "PhoneNumberAddresses" resource of the SignalWire fabric API.
type PhoneNumberAddresses struct {
	*CrudResource
}

// NewPhoneNumberAddresses constructs a PhoneNumberAddresses bound to base path "/api/fabric/addresses/phone".
func NewPhoneNumberAddresses(client HTTPClient) *PhoneNumberAddresses {
	return &PhoneNumberAddresses{NewCrudResource(client, "/api/fabric/addresses/phone")}
}

// FabricAddresses is a client for the "FabricAddresses" resource of the SignalWire fabric API.
type FabricAddresses struct {
	Resource
}

// NewFabricAddresses constructs a FabricAddresses bound to base path "/api/fabric/addresses".
func NewFabricAddresses(client HTTPClient) *FabricAddresses {
	return &FabricAddresses{Resource{HTTP: client, Base: "/api/fabric/addresses"}}
}

func (r *FabricAddresses) List(ctx context.Context, params map[string]string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Get(ctx, r.Base, params, opts...)
}

func (r *FabricAddresses) Get(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Get(ctx, r.Path(id), nil, opts...)
}

func (r *FabricAddresses) Paginate(ctx context.Context, params map[string]string, opts ...*RequestOptions) *Paginator {
	return NewPaginator(ctx, r.HTTP, r.Base, params, "data", opts...)
}

func (r *FabricAddresses) Delete(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Delete(ctx, r.Path(id), opts...)
}

// GenericResources is a client for the "GenericResources" resource of the SignalWire fabric API.
type GenericResources struct {
	Resource
}

// NewGenericResources constructs a GenericResources bound to base path "/api/fabric/resources".
func NewGenericResources(client HTTPClient) *GenericResources {
	return &GenericResources{Resource{HTTP: client, Base: "/api/fabric/resources"}}
}

func (r *GenericResources) List(ctx context.Context, params map[string]string, opts ...*RequestOptions) (*ResourceListResponse, error) {
	return decodeResult[ResourceListResponse](r.HTTP.Get(ctx, r.Base, params, opts...))
}

func (r *GenericResources) Get(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*ResourceResponse, error) {
	return decodeResult[ResourceResponse](r.HTTP.Get(ctx, r.Path(id), params, opts...))
}

func (r *GenericResources) Delete(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Delete(ctx, r.Path(id), opts...)
}

func (r *GenericResources) ListAddresses(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*ResourceAddressListResponse, error) {
	return decodeResult[ResourceAddressListResponse](r.HTTP.Get(ctx, r.Path(id, "addresses"), params, opts...))
}

// GenericResourcesAssignPhoneRouteParams holds the named optional parameters for GenericResources.AssignPhoneRoute.
type GenericResourcesAssignPhoneRouteParams struct {
	PhoneRouteID Uuid           `sw:"required"`
	Handler      UsedForType    `sw:"required"`
	Extras       map[string]any `sw:"optional"`
}

func (r *GenericResources) AssignPhoneRoute(ctx context.Context, id string, params GenericResourcesAssignPhoneRouteParams, opts ...*RequestOptions) (*PhoneRouteResponse, error) {
	body := map[string]any{}
	body["phone_route_id"] = params.PhoneRouteID
	body["handler"] = params.Handler
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[PhoneRouteResponse](r.HTTP.Post(ctx, r.Path(id, "phone_routes"), body, nil, opts...))
}

// GenericResourcesAssignDomainApplicationParams holds the named optional parameters for GenericResources.AssignDomainApplication.
type GenericResourcesAssignDomainApplicationParams struct {
	DomainApplicationID Uuid           `sw:"required"`
	Extras              map[string]any `sw:"optional"`
}

func (r *GenericResources) AssignDomainApplication(ctx context.Context, id string, params GenericResourcesAssignDomainApplicationParams, opts ...*RequestOptions) (*FabricDomainApplicationResponse, error) {
	body := map[string]any{}
	body["domain_application_id"] = params.DomainApplicationID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[FabricDomainApplicationResponse](r.HTTP.Post(ctx, r.Path(id, "domain_applications"), body, nil, opts...))
}

// GenericResourcesAssignSIPEndpointParams holds the named optional parameters for GenericResources.AssignSIPEndpoint.
type GenericResourcesAssignSIPEndpointParams struct {
	SIPEndpointID Uuid           `sw:"required"`
	Extras        map[string]any `sw:"optional"`
}

func (r *GenericResources) AssignSIPEndpoint(ctx context.Context, id string, params GenericResourcesAssignSIPEndpointParams, opts ...*RequestOptions) (*ResourceResponseSipEndpoint, error) {
	body := map[string]any{}
	body["sip_endpoint_id"] = params.SIPEndpointID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[ResourceResponseSipEndpoint](r.HTTP.Post(ctx, r.Path(id, "sip_endpoints"), body, nil, opts...))
}

// GenericResourcesAssignWhatsappNumberParams holds the named optional parameters for GenericResources.AssignWhatsappNumber.
type GenericResourcesAssignWhatsappNumberParams struct {
	WhatsappNumberID Uuid           `sw:"required"`
	Handler          UsedForType    `sw:"required"`
	Extras           map[string]any `sw:"optional"`
}

func (r *GenericResources) AssignWhatsappNumber(ctx context.Context, id string, params GenericResourcesAssignWhatsappNumberParams, opts ...*RequestOptions) (*WhatsappNumberAddressResponse, error) {
	body := map[string]any{}
	body["whatsapp_number_id"] = params.WhatsappNumberID
	body["handler"] = params.Handler
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[WhatsappNumberAddressResponse](r.HTTP.Post(ctx, r.Path(id, "whatsapp_numbers"), body, nil, opts...))
}

// AIAgents is a client for the "AiAgents" resource of the SignalWire fabric API.
type AIAgents struct {
	*CrudWithAddresses
}

// NewAIAgents constructs a AIAgents bound to base path "/api/fabric/resources/ai_agents".
func NewAIAgents(client HTTPClient) *AIAgents {
	return &AIAgents{NewCrudWithAddresses(client, "/api/fabric/resources/ai_agents")}
}

func (r *AIAgents) ListVoices(ctx context.Context, params map[string]string, opts ...*RequestOptions) ([]AIAgentVoice, error) {
	return decodeListResult[AIAgentVoice](r.HTTP.Get(ctx, r.Path("voices"), params, opts...))
}

func (r *AIAgents) ListConversationLogs(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*AIAgentConversationLogListResponse, error) {
	return decodeResult[AIAgentConversationLogListResponse](r.HTTP.Get(ctx, r.Path(id, "conversation_logs"), params, opts...))
}

// CallFlowsResource is a client for the "CallFlows" resource of the SignalWire fabric API.
type CallFlowsResource struct {
	*CrudWithAddresses
}

// NewCallFlowsResource constructs a CallFlowsResource bound to base path "/api/fabric/resources/call_flows".
func NewCallFlowsResource(client HTTPClient) *CallFlowsResource {
	return &CallFlowsResource{NewCrudWithAddressesPUT(client, "/api/fabric/resources/call_flows")}
}

func (r *CallFlowsResource) ListAddresses(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*CallFlowAddressListResponse, error) {
	return decodeResult[CallFlowAddressListResponse](r.HTTP.Get(ctx, r.Path(id, "addresses"), params, opts...))
}

func (r *CallFlowsResource) ListVersions(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*CallFlowVersionListResponse, error) {
	return decodeResult[CallFlowVersionListResponse](r.HTTP.Get(ctx, r.Path(id, "versions"), params, opts...))
}

func (r *CallFlowsResource) DeployVersion(ctx context.Context, id string, data map[string]any, opts ...*RequestOptions) (*CallFlowVersionDeployResponse, error) {
	return decodeResult[CallFlowVersionDeployResponse](r.HTTP.Post(ctx, r.Path(id, "versions"), data, nil, opts...))
}

// ConferenceRoomsResource is a client for the "ConferenceRooms" resource of the SignalWire fabric API.
type ConferenceRoomsResource struct {
	*CrudWithAddresses
}

// NewConferenceRoomsResource constructs a ConferenceRoomsResource bound to base path "/api/fabric/resources/conference_rooms".
func NewConferenceRoomsResource(client HTTPClient) *ConferenceRoomsResource {
	return &ConferenceRoomsResource{NewCrudWithAddressesPUT(client, "/api/fabric/resources/conference_rooms")}
}

func (r *ConferenceRoomsResource) ListAddresses(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*ConferenceRoomAddressListResponse, error) {
	return decodeResult[ConferenceRoomAddressListResponse](r.HTTP.Get(ctx, r.Path(id, "addresses"), params, opts...))
}

// CxmlApplicationsResource is a client for the "CxmlApplications" resource of the SignalWire fabric API.
type CxmlApplicationsResource struct {
	Resource
}

// NewCxmlApplicationsResource constructs a CxmlApplicationsResource bound to base path "/api/fabric/resources/cxml_applications".
func NewCxmlApplicationsResource(client HTTPClient) *CxmlApplicationsResource {
	return &CxmlApplicationsResource{Resource{HTTP: client, Base: "/api/fabric/resources/cxml_applications"}}
}

func (r *CxmlApplicationsResource) List(ctx context.Context, params map[string]string, opts ...*RequestOptions) (*CxmlApplicationListResponse, error) {
	return decodeResult[CxmlApplicationListResponse](r.HTTP.Get(ctx, r.Base, params, opts...))
}

func (r *CxmlApplicationsResource) Get(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*CxmlApplicationResponse, error) {
	return decodeResult[CxmlApplicationResponse](r.HTTP.Get(ctx, r.Path(id), params, opts...))
}

// CxmlApplicationsResourceUpdateParams holds the named optional parameters for CxmlApplicationsResource.Update.
type CxmlApplicationsResourceUpdateParams struct {
	Name                  *string        `sw:"optional"`
	CallRequestURL        *string        `sw:"optional"`
	CallRequestMethod     *string        `sw:"optional"`
	CallFallbackURL       *string        `sw:"optional"`
	CallFallbackMethod    *string        `sw:"optional"`
	CallStatusURL         *string        `sw:"optional"`
	CallStatusMethod      *string        `sw:"optional"`
	MessageRequestURL     *string        `sw:"optional"`
	MessageRequestMethod  *string        `sw:"optional"`
	MessageFallbackURL    *string        `sw:"optional"`
	MessageFallbackMethod *string        `sw:"optional"`
	MessageStatusURL      *string        `sw:"optional"`
	MessageStatusMethod   *string        `sw:"optional"`
	Extras                map[string]any `sw:"optional"`
}

func (r *CxmlApplicationsResource) Update(ctx context.Context, id string, params CxmlApplicationsResourceUpdateParams, opts ...*RequestOptions) (*CxmlApplicationResponse, error) {
	body := map[string]any{}
	if params.Name != nil {
		body["name"] = params.Name
	}
	if params.CallRequestURL != nil {
		body["call_request_url"] = params.CallRequestURL
	}
	if params.CallRequestMethod != nil {
		body["call_request_method"] = params.CallRequestMethod
	}
	if params.CallFallbackURL != nil {
		body["call_fallback_url"] = params.CallFallbackURL
	}
	if params.CallFallbackMethod != nil {
		body["call_fallback_method"] = params.CallFallbackMethod
	}
	if params.CallStatusURL != nil {
		body["call_status_url"] = params.CallStatusURL
	}
	if params.CallStatusMethod != nil {
		body["call_status_method"] = params.CallStatusMethod
	}
	if params.MessageRequestURL != nil {
		body["message_request_url"] = params.MessageRequestURL
	}
	if params.MessageRequestMethod != nil {
		body["message_request_method"] = params.MessageRequestMethod
	}
	if params.MessageFallbackURL != nil {
		body["message_fallback_url"] = params.MessageFallbackURL
	}
	if params.MessageFallbackMethod != nil {
		body["message_fallback_method"] = params.MessageFallbackMethod
	}
	if params.MessageStatusURL != nil {
		body["message_status_url"] = params.MessageStatusURL
	}
	if params.MessageStatusMethod != nil {
		body["message_status_method"] = params.MessageStatusMethod
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CxmlApplicationResponse](r.HTTP.Put(ctx, r.Path(id), body, opts...))
}

func (r *CxmlApplicationsResource) Delete(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Delete(ctx, r.Path(id), opts...)
}

func (r *CxmlApplicationsResource) ListAddresses(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*CxmlApplicationAddressListResponse, error) {
	return decodeResult[CxmlApplicationAddressListResponse](r.HTTP.Get(ctx, r.Path(id, "addresses"), params, opts...))
}

// CXMLScripts is a client for the "CxmlScripts" resource of the SignalWire fabric API.
type CXMLScripts struct {
	*CrudWithAddresses
}

// NewCXMLScripts constructs a CXMLScripts bound to base path "/api/fabric/resources/cxml_scripts".
func NewCXMLScripts(client HTTPClient) *CXMLScripts {
	return &CXMLScripts{NewCrudWithAddressesPUT(client, "/api/fabric/resources/cxml_scripts")}
}

// CXMLWebhooks is a client for the "CxmlWebhooks" resource of the SignalWire fabric API.
type CXMLWebhooks struct {
	*CrudWithAddresses
}

// NewCXMLWebhooks constructs a CXMLWebhooks bound to base path "/api/fabric/resources/cxml_webhooks".
func NewCXMLWebhooks(client HTTPClient) *CXMLWebhooks {
	return &CXMLWebhooks{NewCrudWithAddresses(client, "/api/fabric/resources/cxml_webhooks")}
}

// FreeSwitchConnectors is a client for the "FreeswitchConnectors" resource of the SignalWire fabric API.
type FreeSwitchConnectors struct {
	*CrudWithAddresses
}

// NewFreeSwitchConnectors constructs a FreeSwitchConnectors bound to base path "/api/fabric/resources/freeswitch_connectors".
func NewFreeSwitchConnectors(client HTTPClient) *FreeSwitchConnectors {
	return &FreeSwitchConnectors{NewCrudWithAddressesPUT(client, "/api/fabric/resources/freeswitch_connectors")}
}

// RelayApplications is a client for the "RelayApplications" resource of the SignalWire fabric API.
type RelayApplications struct {
	*CrudWithAddresses
}

// NewRelayApplications constructs a RelayApplications bound to base path "/api/fabric/resources/relay_applications".
func NewRelayApplications(client HTTPClient) *RelayApplications {
	return &RelayApplications{NewCrudWithAddressesPUT(client, "/api/fabric/resources/relay_applications")}
}

// SIPEndpoints is a client for the "SipEndpoints" resource of the SignalWire fabric API.
type SIPEndpoints struct {
	*CrudWithAddresses
}

// NewSIPEndpoints constructs a SIPEndpoints bound to base path "/api/fabric/resources/sip_endpoints".
func NewSIPEndpoints(client HTTPClient) *SIPEndpoints {
	return &SIPEndpoints{NewCrudWithAddressesPUT(client, "/api/fabric/resources/sip_endpoints")}
}

// SIPGateways is a client for the "SipGateways" resource of the SignalWire fabric API.
type SIPGateways struct {
	*CrudWithAddresses
}

// NewSIPGateways constructs a SIPGateways bound to base path "/api/fabric/resources/sip_gateways".
func NewSIPGateways(client HTTPClient) *SIPGateways {
	return &SIPGateways{NewCrudWithAddresses(client, "/api/fabric/resources/sip_gateways")}
}

// SubscribersResource is a client for the "Subscribers" resource of the SignalWire fabric API.
type SubscribersResource struct {
	*CrudWithAddresses
}

// NewSubscribersResource constructs a SubscribersResource bound to base path "/api/fabric/resources/subscribers".
func NewSubscribersResource(client HTTPClient) *SubscribersResource {
	return &SubscribersResource{NewCrudWithAddressesPUT(client, "/api/fabric/resources/subscribers")}
}

func (r *SubscribersResource) ListSIPEndpoints(ctx context.Context, subscriberID string, params map[string]string, opts ...*RequestOptions) (*SubscriberSipEndpointListResponse, error) {
	return decodeResult[SubscriberSipEndpointListResponse](r.HTTP.Get(ctx, r.Path(subscriberID, "sip_endpoints"), params, opts...))
}

// SubscribersResourceCreateSIPEndpointParams holds the named optional parameters for SubscribersResource.CreateSIPEndpoint.
type SubscribersResourceCreateSIPEndpointParams struct {
	Username   string         `sw:"required"`
	Password   string         `sw:"required"`
	CallerID   *string        `sw:"optional"`
	SendAs     *string        `sw:"optional"`
	Ciphers    []Ciphers      `sw:"optional"`
	Codecs     []Codecs       `sw:"optional"`
	Encryption *Encryption    `sw:"optional"`
	Extras     map[string]any `sw:"optional"`
}

func (r *SubscribersResource) CreateSIPEndpoint(ctx context.Context, subscriberID string, params SubscribersResourceCreateSIPEndpointParams, opts ...*RequestOptions) (*SubscriberSIPEndpoint, error) {
	body := map[string]any{}
	body["username"] = params.Username
	body["password"] = params.Password
	if params.CallerID != nil {
		body["caller_id"] = params.CallerID
	}
	if params.SendAs != nil {
		body["send_as"] = params.SendAs
	}
	if params.Ciphers != nil {
		body["ciphers"] = params.Ciphers
	}
	if params.Codecs != nil {
		body["codecs"] = params.Codecs
	}
	if params.Encryption != nil {
		body["encryption"] = params.Encryption
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[SubscriberSIPEndpoint](r.HTTP.Post(ctx, r.Path(subscriberID, "sip_endpoints"), body, nil, opts...))
}

func (r *SubscribersResource) GetSIPEndpoint(ctx context.Context, subscriberID string, id string, params map[string]string, opts ...*RequestOptions) (*SubscriberSIPEndpoint, error) {
	return decodeResult[SubscriberSIPEndpoint](r.HTTP.Get(ctx, r.Path(subscriberID, "sip_endpoints", id), params, opts...))
}

// SubscribersResourceUpdateSIPEndpointParams holds the named optional parameters for SubscribersResource.UpdateSIPEndpoint.
type SubscribersResourceUpdateSIPEndpointParams struct {
	Username   *string        `sw:"optional"`
	Password   *string        `sw:"optional"`
	CallerID   *string        `sw:"optional"`
	SendAs     *string        `sw:"optional"`
	Ciphers    []Ciphers      `sw:"optional"`
	Codecs     []Codecs       `sw:"optional"`
	Encryption *Encryption    `sw:"optional"`
	Extras     map[string]any `sw:"optional"`
}

func (r *SubscribersResource) UpdateSIPEndpoint(ctx context.Context, subscriberID string, id string, params SubscribersResourceUpdateSIPEndpointParams, opts ...*RequestOptions) (*SubscriberSIPEndpoint, error) {
	body := map[string]any{}
	if params.Username != nil {
		body["username"] = params.Username
	}
	if params.Password != nil {
		body["password"] = params.Password
	}
	if params.CallerID != nil {
		body["caller_id"] = params.CallerID
	}
	if params.SendAs != nil {
		body["send_as"] = params.SendAs
	}
	if params.Ciphers != nil {
		body["ciphers"] = params.Ciphers
	}
	if params.Codecs != nil {
		body["codecs"] = params.Codecs
	}
	if params.Encryption != nil {
		body["encryption"] = params.Encryption
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[SubscriberSIPEndpoint](r.HTTP.Patch(ctx, r.Path(subscriberID, "sip_endpoints", id), body, opts...))
}

func (r *SubscribersResource) DeleteSIPEndpoint(ctx context.Context, subscriberID string, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Delete(ctx, r.Path(subscriberID, "sip_endpoints", id), opts...)
}

// SWMLScripts is a client for the "SwmlScripts" resource of the SignalWire fabric API.
type SWMLScripts struct {
	*CrudWithAddresses
}

// NewSWMLScripts constructs a SWMLScripts bound to base path "/api/fabric/resources/swml_scripts".
func NewSWMLScripts(client HTTPClient) *SWMLScripts {
	return &SWMLScripts{NewCrudWithAddressesPUT(client, "/api/fabric/resources/swml_scripts")}
}

// SWMLWebhooks is a client for the "SwmlWebhooks" resource of the SignalWire fabric API.
type SWMLWebhooks struct {
	*CrudWithAddresses
}

// NewSWMLWebhooks constructs a SWMLWebhooks bound to base path "/api/fabric/resources/swml_webhooks".
func NewSWMLWebhooks(client HTTPClient) *SWMLWebhooks {
	return &SWMLWebhooks{NewCrudWithAddresses(client, "/api/fabric/resources/swml_webhooks")}
}

// FabricTokens is a client for the "FabricTokens" resource of the SignalWire fabric API.
type FabricTokens struct {
	Resource
}

// NewFabricTokens constructs a FabricTokens bound to base path "/api/fabric".
func NewFabricTokens(client HTTPClient) *FabricTokens {
	return &FabricTokens{Resource{HTTP: client, Base: "/api/fabric"}}
}

// FabricTokensCreateSubscriberTokenParams holds the named optional parameters for FabricTokens.CreateSubscriberToken.
type FabricTokensCreateSubscriberTokenParams struct {
	Reference     string         `sw:"required"`
	Ch            *string        `sw:"optional"`
	ExpireAt      *int           `sw:"optional"`
	ApplicationID *Uuid          `sw:"optional"`
	Password      *string        `sw:"optional"`
	FirstName     *string        `sw:"optional"`
	LastName      *string        `sw:"optional"`
	DisplayName   *string        `sw:"optional"`
	JobTitle      *string        `sw:"optional"`
	TimeZone      *string        `sw:"optional"`
	Country       *string        `sw:"optional"`
	Region        *string        `sw:"optional"`
	CompanyName   *string        `sw:"optional"`
	Scope         *string        `sw:"optional"`
	Fingerprint   *string        `sw:"optional"`
	Extras        map[string]any `sw:"optional"`
}

func (r *FabricTokens) CreateSubscriberToken(ctx context.Context, params FabricTokensCreateSubscriberTokenParams, opts ...*RequestOptions) (*SubscriberTokenResponse, error) {
	body := map[string]any{}
	body["reference"] = params.Reference
	if params.Ch != nil {
		body["ch"] = params.Ch
	}
	if params.ExpireAt != nil {
		body["expire_at"] = params.ExpireAt
	}
	if params.ApplicationID != nil {
		body["application_id"] = params.ApplicationID
	}
	if params.Password != nil {
		body["password"] = params.Password
	}
	if params.FirstName != nil {
		body["first_name"] = params.FirstName
	}
	if params.LastName != nil {
		body["last_name"] = params.LastName
	}
	if params.DisplayName != nil {
		body["display_name"] = params.DisplayName
	}
	if params.JobTitle != nil {
		body["job_title"] = params.JobTitle
	}
	if params.TimeZone != nil {
		body["time_zone"] = params.TimeZone
	}
	if params.Country != nil {
		body["country"] = params.Country
	}
	if params.Region != nil {
		body["region"] = params.Region
	}
	if params.CompanyName != nil {
		body["company_name"] = params.CompanyName
	}
	if params.Scope != nil {
		body["scope"] = params.Scope
	}
	if params.Fingerprint != nil {
		body["fingerprint"] = params.Fingerprint
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[SubscriberTokenResponse](r.HTTP.Post(ctx, "/api/fabric/subscribers/tokens", body, nil, opts...))
}

// FabricTokensRefreshSubscriberTokenParams holds the named optional parameters for FabricTokens.RefreshSubscriberToken.
type FabricTokensRefreshSubscriberTokenParams struct {
	RefreshToken Jwt            `sw:"required"`
	Extras       map[string]any `sw:"optional"`
}

func (r *FabricTokens) RefreshSubscriberToken(ctx context.Context, params FabricTokensRefreshSubscriberTokenParams, opts ...*RequestOptions) (*SubscriberRefreshTokenResponse, error) {
	body := map[string]any{}
	body["refresh_token"] = params.RefreshToken
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[SubscriberRefreshTokenResponse](r.HTTP.Post(ctx, "/api/fabric/subscribers/tokens/refresh", body, nil, opts...))
}

// FabricTokensCreateGuestTokenParams holds the named optional parameters for FabricTokens.CreateGuestToken.
type FabricTokensCreateGuestTokenParams struct {
	AllowedAddresses []Uuid         `sw:"optional"`
	ExpireAt         *int           `sw:"optional"`
	Ch               *string        `sw:"optional"`
	Region           *string        `sw:"optional"`
	Email            *string        `sw:"optional"`
	FirstName        *string        `sw:"optional"`
	LastName         *string        `sw:"optional"`
	DisplayName      *string        `sw:"optional"`
	JobTitle         *string        `sw:"optional"`
	TimeZone         *string        `sw:"optional"`
	Country          *string        `sw:"optional"`
	CompanyName      *string        `sw:"optional"`
	Extras           map[string]any `sw:"optional"`
}

func (r *FabricTokens) CreateGuestToken(ctx context.Context, params FabricTokensCreateGuestTokenParams, opts ...*RequestOptions) (*SubscriberGuestTokenCreateResponse, error) {
	body := map[string]any{}
	if params.AllowedAddresses != nil {
		body["allowed_addresses"] = params.AllowedAddresses
	}
	if params.ExpireAt != nil {
		body["expire_at"] = params.ExpireAt
	}
	if params.Ch != nil {
		body["ch"] = params.Ch
	}
	if params.Region != nil {
		body["region"] = params.Region
	}
	if params.Email != nil {
		body["email"] = params.Email
	}
	if params.FirstName != nil {
		body["first_name"] = params.FirstName
	}
	if params.LastName != nil {
		body["last_name"] = params.LastName
	}
	if params.DisplayName != nil {
		body["display_name"] = params.DisplayName
	}
	if params.JobTitle != nil {
		body["job_title"] = params.JobTitle
	}
	if params.TimeZone != nil {
		body["time_zone"] = params.TimeZone
	}
	if params.Country != nil {
		body["country"] = params.Country
	}
	if params.CompanyName != nil {
		body["company_name"] = params.CompanyName
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[SubscriberGuestTokenCreateResponse](r.HTTP.Post(ctx, "/api/fabric/guests/tokens", body, nil, opts...))
}

// FabricTokensCreateEmbedTokenParams holds the named optional parameters for FabricTokens.CreateEmbedToken.
type FabricTokensCreateEmbedTokenParams struct {
	Token  string         `sw:"required"`
	Extras map[string]any `sw:"optional"`
}

func (r *FabricTokens) CreateEmbedToken(ctx context.Context, params FabricTokensCreateEmbedTokenParams, opts ...*RequestOptions) (*EmbedsTokensResponse, error) {
	body := map[string]any{}
	body["token"] = params.Token
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[EmbedsTokensResponse](r.HTTP.Post(ctx, "/api/fabric/embeds/tokens", body, nil, opts...))
}
