// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "fax" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type FaxLog struct {
	Id            Uuid           `json:"id,omitempty"`
	From          any            `json:"from,omitempty"`
	To            any            `json:"to,omitempty"`
	Status        string         `json:"status,omitempty"`
	Direction     any            `json:"direction,omitempty"`
	Source        string         `json:"source,omitempty"`
	Type_         string         `json:"type,omitempty"`
	Url           string         `json:"url,omitempty"`
	RemoteStation any            `json:"remote_station,omitempty"`
	Charge        float64        `json:"charge,omitempty"`
	NumberOfPages any            `json:"number_of_pages,omitempty"`
	Quality       any            `json:"quality,omitempty"`
	ChargeDetails []ChargeDetail `json:"charge_details,omitempty"`
	CreatedAt     string         `json:"created_at,omitempty"`
	ErrorCode     any            `json:"error_code,omitempty"`
	ErrorMessage  any            `json:"error_message,omitempty"`
}

type FaxLogShowStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type FaxLogsListStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type LogResponse struct {
	Id            Uuid           `json:"id,omitempty"`
	From          any            `json:"from,omitempty"`
	To            any            `json:"to,omitempty"`
	Status        string         `json:"status,omitempty"`
	Direction     any            `json:"direction,omitempty"`
	Source        string         `json:"source,omitempty"`
	Type_         string         `json:"type,omitempty"`
	Url           string         `json:"url,omitempty"`
	RemoteStation any            `json:"remote_station,omitempty"`
	Charge        float64        `json:"charge,omitempty"`
	NumberOfPages any            `json:"number_of_pages,omitempty"`
	Quality       any            `json:"quality,omitempty"`
	ChargeDetails []ChargeDetail `json:"charge_details,omitempty"`
	CreatedAt     string         `json:"created_at,omitempty"`
	ErrorCode     any            `json:"error_code,omitempty"`
	ErrorMessage  any            `json:"error_message,omitempty"`
}
