// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "message" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type LogListResponse struct {
	Links LogPaginationResponse `json:"links,omitempty"`
	Data  []MessageLog          `json:"data,omitempty"`
}

type LogPaginationResponse struct {
	Self  string  `json:"self,omitempty"`
	First string  `json:"first,omitempty"`
	Next  *string `json:"next,omitempty"`
	Prev  *string `json:"prev,omitempty"`
}

type LogRetrieveResponse struct {
	Id               uuid           `json:"id,omitempty"`
	From             string         `json:"from,omitempty"`
	To               string         `json:"to,omitempty"`
	Status           string         `json:"status,omitempty"`
	Direction        string         `json:"direction,omitempty"`
	Kind             string         `json:"kind,omitempty"`
	Source           string         `json:"source,omitempty"`
	Type_            string         `json:"type,omitempty"`
	Url              any            `json:"url,omitempty"`
	NumberOfSegments int            `json:"number_of_segments,omitempty"`
	Charge           float64        `json:"charge,omitempty"`
	ChargeDetails    []ChargeDetail `json:"charge_details,omitempty"`
	CreatedAt        string         `json:"created_at,omitempty"`
}

type MessageLog struct {
	Id               uuid           `json:"id,omitempty"`
	From             string         `json:"from,omitempty"`
	To               string         `json:"to,omitempty"`
	Status           string         `json:"status,omitempty"`
	Direction        string         `json:"direction,omitempty"`
	Kind             string         `json:"kind,omitempty"`
	Source           string         `json:"source,omitempty"`
	Type_            string         `json:"type,omitempty"`
	Url              any            `json:"url,omitempty"`
	NumberOfSegments int            `json:"number_of_segments,omitempty"`
	Charge           float64        `json:"charge,omitempty"`
	ChargeDetails    []ChargeDetail `json:"charge_details,omitempty"`
	CreatedAt        string         `json:"created_at,omitempty"`
}

type MessageLogShowStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type MessageLogsListStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}
