// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "messages" namespace spec.

package namespaces

import "context"

// Messages is a client for the "Messages" resource of the SignalWire messages API.
type Messages struct {
	Resource
}

// NewMessages constructs a Messages bound to base path "/api/messaging/messages".
func NewMessages(client HTTPClient) *Messages {
	return &Messages{Resource{HTTP: client, Base: "/api/messaging/messages"}}
}

// MessagesCreateParams holds the named optional parameters for Messages.Create.
type MessagesCreateParams struct {
	To              string
	From            string
	Body            *string
	Media           []string
	SendAsMms       *bool
	StatusCallback  *string
	CustomVariables map[string]any
	Extras          map[string]any
}

func (r *Messages) Create(ctx context.Context, params MessagesCreateParams, opts ...*RequestOptions) (*Message, error) {
	body := map[string]any{}
	body["to"] = params.To
	body["from"] = params.From
	if params.Body != nil {
		body["body"] = params.Body
	}
	if params.Media != nil {
		body["media"] = params.Media
	}
	if params.SendAsMms != nil {
		body["send_as_mms"] = params.SendAsMms
	}
	if params.StatusCallback != nil {
		body["status_callback"] = params.StatusCallback
	}
	if params.CustomVariables != nil {
		body["custom_variables"] = params.CustomVariables
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[Message](r.HTTP.Post(ctx, r.Base, body, nil, opts...))
}

// MessagesUpdateParams holds the named optional parameters for Messages.Update.
type MessagesUpdateParams struct {
	Body   string
	Extras map[string]any
}

func (r *Messages) Update(ctx context.Context, id string, params MessagesUpdateParams, opts ...*RequestOptions) (*Message, error) {
	body := map[string]any{}
	body["body"] = params.Body
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[Message](r.HTTP.Patch(ctx, r.Path(id), body, opts...))
}
