// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "message" namespace spec.

package namespaces

// MessageLogs is a client for the "MessageLogs" resource of the SignalWire message API.
type MessageLogs struct {
	Resource
}

// NewMessageLogs constructs a MessageLogs bound to base path "/api/messaging/logs".
func NewMessageLogs(client HTTPClient) *MessageLogs {
	return &MessageLogs{Resource{HTTP: client, Base: "/api/messaging/logs"}}
}

func (r *MessageLogs) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *MessageLogs) Get(id string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), nil)
}

func (r *MessageLogs) Paginate(params map[string]string) *Paginator {
	return NewPaginator(r.HTTP, r.Base, params, "data")
}
