// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "messages" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type CreateMessageRequest struct {
	To              string         `json:"to,omitempty"`
	From            string         `json:"from,omitempty"`
	Body            *string        `json:"body,omitempty"`
	Media           []string       `json:"media,omitempty"`
	SendAsMms       *bool          `json:"send_as_mms,omitempty"`
	StatusCallback  *string        `json:"status_callback,omitempty"`
	CustomVariables map[string]any `json:"custom_variables,omitempty"`
}

type UpdateMessageRequest struct {
	Body string `json:"body,omitempty"`
}

type Message struct {
	ID                Uuid             `json:"id,omitempty"`
	From              string           `json:"from,omitempty"`
	To                string           `json:"to,omitempty"`
	Body              string           `json:"body,omitempty"`
	Status            MessageStatus    `json:"status,omitempty"`
	Direction         MessageDirection `json:"direction,omitempty"`
	Kind              MessageKind      `json:"kind,omitempty"`
	Media             []string         `json:"media,omitempty"`
	NumberOfSegments  int              `json:"number_of_segments,omitempty"`
	ErrorCode         any              `json:"error_code,omitempty"`
	ErrorMessage      any              `json:"error_message,omitempty"`
	CreatedAt         string           `json:"created_at,omitempty"`
	ProjectID         Uuid             `json:"project_id,omitempty"`
	StatusCallbackURL any              `json:"status_callback_url,omitempty"`
	MessageURI        string           `json:"message_uri,omitempty"`
}

type MessageStatus string

const (
	MessageStatusQueued      MessageStatus = "queued"
	MessageStatusInitiated   MessageStatus = "initiated"
	MessageStatusSent        MessageStatus = "sent"
	MessageStatusDelivered   MessageStatus = "delivered"
	MessageStatusUndelivered MessageStatus = "undelivered"
	MessageStatusFailed      MessageStatus = "failed"
	MessageStatusRead        MessageStatus = "read"
)

type MessageDirection string

const (
	MessageDirectionInbound  MessageDirection = "inbound"
	MessageDirectionOutbound MessageDirection = "outbound"
)

type MessageKind string

const (
	MessageKindSms MessageKind = "sms"
	MessageKindMms MessageKind = "mms"
)

type MessagesCreateStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type MessagesUpdateStatusCode422 struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}
