// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "project" namespace spec.

package namespaces

// ProjectTokens is generated from x-sdk-resource "ProjectTokens" in the project spec.
type ProjectTokens struct {
	Resource
}

// NewProjectTokens constructs a ProjectTokens bound to base path "/api/project/tokens".
func NewProjectTokens(client HTTPClient) *ProjectTokens {
	return &ProjectTokens{Resource{HTTP: client, Base: "/api/project/tokens"}}
}

func (r *ProjectTokens) Create(name any, permissions any, subprojectId any, extras map[string]any) (map[string]any, error) {
	body := map[string]any{}
	if name != nil {
		body["name"] = name
	}
	if permissions != nil {
		body["permissions"] = permissions
	}
	if subprojectId != nil {
		body["subproject_id"] = subprojectId
	}
	mergeExtra(body, []map[string]any{extras})
	return r.HTTP.Post(r.Base, body, nil)
}

func (r *ProjectTokens) Update(tokenID string, name any, permissions any, extras map[string]any) (map[string]any, error) {
	body := map[string]any{}
	if name != nil {
		body["name"] = name
	}
	if permissions != nil {
		body["permissions"] = permissions
	}
	mergeExtra(body, []map[string]any{extras})
	return r.HTTP.Patch(r.Path(tokenID), body)
}

func (r *ProjectTokens) Delete(tokenID string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(tokenID))
}
