// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "pubsub" namespace spec.

package namespaces

// PubSubNamespace is generated from x-sdk-resource "PubSub" in the pubsub spec.
type PubSubNamespace struct {
	Resource
}

// NewPubSubNamespace constructs a PubSubNamespace bound to base path "/api/pubsub/tokens".
func NewPubSubNamespace(client HTTPClient) *PubSubNamespace {
	return &PubSubNamespace{Resource{HTTP: client, Base: "/api/pubsub/tokens"}}
}

func (r *PubSubNamespace) CreateToken(data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Base, data, nil)
}
