// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "pubsub" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type NewPubSubToken struct {
	Ttl      int            `json:"ttl,omitempty"`
	Channels PubSubChannels `json:"channels,omitempty"`
	MemberId *string        `json:"member_id,omitempty"`
	State    *PubSubState   `json:"state,omitempty"`
}

type PubSubChannels map[string]any

type PubSubPermissionWithRead struct {
	Read  bool  `json:"read,omitempty"`
	Write *bool `json:"write,omitempty"`
}

type PubSubPermissionWithWrite struct {
	Read  *bool `json:"read,omitempty"`
	Write bool  `json:"write,omitempty"`
}

type PubSubState map[string]any

type PubSubToken struct {
	Token string `json:"token,omitempty"`
}

type PubSubToken422Error struct {
	Errors []Types_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}
