// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "relay-rest" namespace spec.

package namespaces

// AddressesNamespace is generated from x-sdk-resource "Addresses" in the relay-rest spec.
type AddressesNamespace struct {
	Resource
}

// NewAddressesNamespace constructs a AddressesNamespace bound to base path "/api/relay/rest/addresses".
func NewAddressesNamespace(client HTTPClient) *AddressesNamespace {
	return &AddressesNamespace{Resource{HTTP: client, Base: "/api/relay/rest/addresses"}}
}

func (r *AddressesNamespace) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *AddressesNamespace) Create(data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Base, data, nil)
}

func (r *AddressesNamespace) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *AddressesNamespace) Delete(id string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(id))
}

// ImportedNumbersNamespace is generated from x-sdk-resource "ImportedNumbers" in the relay-rest spec.
type ImportedNumbersNamespace struct {
	Resource
}

// NewImportedNumbersNamespace constructs a ImportedNumbersNamespace bound to base path "/api/relay/rest/imported_phone_numbers".
func NewImportedNumbersNamespace(client HTTPClient) *ImportedNumbersNamespace {
	return &ImportedNumbersNamespace{Resource{HTTP: client, Base: "/api/relay/rest/imported_phone_numbers"}}
}

func (r *ImportedNumbersNamespace) Create(data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Base, data, nil)
}

// LookupNamespace is generated from x-sdk-resource "Lookup" in the relay-rest spec.
type LookupNamespace struct {
	Resource
}

// NewLookupNamespace constructs a LookupNamespace bound to base path "/api/relay/rest/lookup".
func NewLookupNamespace(client HTTPClient) *LookupNamespace {
	return &LookupNamespace{Resource{HTTP: client, Base: "/api/relay/rest/lookup"}}
}

func (r *LookupNamespace) PhoneNumber(e164 string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path("phone_number", e164), params)
}

// MFANamespace is generated from x-sdk-resource "Mfa" in the relay-rest spec.
type MFANamespace struct {
	Resource
}

// NewMFANamespace constructs a MFANamespace bound to base path "/api/relay/rest/mfa".
func NewMFANamespace(client HTTPClient) *MFANamespace {
	return &MFANamespace{Resource{HTTP: client, Base: "/api/relay/rest/mfa"}}
}

func (r *MFANamespace) SMS(data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Path("sms"), data, nil)
}

func (r *MFANamespace) Call(data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Path("call"), data, nil)
}

func (r *MFANamespace) Verify(requestID string, data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Path(requestID, "verify"), data, nil)
}

// NumberGroupsNamespace is generated from x-sdk-resource "NumberGroups" in the relay-rest spec.
type NumberGroupsNamespace struct {
	*CrudResource
}

// NewNumberGroupsNamespace constructs a NumberGroupsNamespace bound to base path "/api/relay/rest/number_groups".
func NewNumberGroupsNamespace(client HTTPClient) *NumberGroupsNamespace {
	return &NumberGroupsNamespace{NewCrudResourcePUT(client, "/api/relay/rest/number_groups")}
}

func (r *NumberGroupsNamespace) ListMemberships(groupID string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(groupID, "number_group_memberships"), params)
}

func (r *NumberGroupsNamespace) AddMembership(groupID string, data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Path(groupID, "number_group_memberships"), data, nil)
}

func (r *NumberGroupsNamespace) GetMembership(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get("/api/relay/rest/number_group_memberships/"+id, params)
}

func (r *NumberGroupsNamespace) DeleteMembership(id string) (map[string]any, error) {
	return r.HTTP.Delete("/api/relay/rest/number_group_memberships/" + id)
}

// PhoneNumbersNamespace is generated from x-sdk-resource "PhoneNumbers" in the relay-rest spec.
type PhoneNumbersNamespace struct {
	*CrudResource
}

// NewPhoneNumbersNamespace constructs a PhoneNumbersNamespace bound to base path "/api/relay/rest/phone_numbers".
func NewPhoneNumbersNamespace(client HTTPClient) *PhoneNumbersNamespace {
	return &PhoneNumbersNamespace{NewCrudResourcePUT(client, "/api/relay/rest/phone_numbers")}
}

func (r *PhoneNumbersNamespace) Search(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path("search"), params)
}

func (r *PhoneNumbersNamespace) SetSwmlWebhook(sid string, url string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":          "relay_script",
		"call_relay_script_url": url,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetCxmlWebhook(sid string, url string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "laml_webhooks",
		"call_request_url": url,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetCxmlApplication(sid string, application_id string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":             "laml_application",
		"call_laml_application_id": application_id,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetAiAgent(sid string, agent_id string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "ai_agent",
		"call_ai_agent_id": agent_id,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetCallFlow(sid string, flow_id string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler": "call_flow",
		"call_flow_id": flow_id,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetRelayApplication(sid string, name string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":           "relay_application",
		"call_relay_application": name,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetRelayTopic(sid string, topic string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "relay_topic",
		"call_relay_topic": topic,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

// QueuesNamespace is generated from x-sdk-resource "Queues" in the relay-rest spec.
type QueuesNamespace struct {
	*CrudResource
}

// NewQueuesNamespace constructs a QueuesNamespace bound to base path "/api/relay/rest/queues".
func NewQueuesNamespace(client HTTPClient) *QueuesNamespace {
	return &QueuesNamespace{NewCrudResourcePUT(client, "/api/relay/rest/queues")}
}

func (r *QueuesNamespace) ListMembers(queueID string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(queueID, "members"), params)
}

func (r *QueuesNamespace) GetNextMember(queueID string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(queueID, "members", "next"), params)
}

func (r *QueuesNamespace) GetMember(queueID string, id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(queueID, "members", id), params)
}

// RecordingsNamespace is generated from x-sdk-resource "Recordings" in the relay-rest spec.
type RecordingsNamespace struct {
	Resource
}

// NewRecordingsNamespace constructs a RecordingsNamespace bound to base path "/api/relay/rest/recordings".
func NewRecordingsNamespace(client HTTPClient) *RecordingsNamespace {
	return &RecordingsNamespace{Resource{HTTP: client, Base: "/api/relay/rest/recordings"}}
}

func (r *RecordingsNamespace) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *RecordingsNamespace) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *RecordingsNamespace) Delete(id string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(id))
}

// RegistryBrands is generated from x-sdk-resource "RegistryBrands" in the relay-rest spec.
type RegistryBrands struct {
	Resource
}

// NewRegistryBrands constructs a RegistryBrands bound to base path "/api/relay/rest/registry/beta/brands".
func NewRegistryBrands(client HTTPClient) *RegistryBrands {
	return &RegistryBrands{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/brands"}}
}

func (r *RegistryBrands) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *RegistryBrands) Create(data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Base, data, nil)
}

func (r *RegistryBrands) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *RegistryBrands) ListCampaigns(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "campaigns"), params)
}

func (r *RegistryBrands) CreateCampaign(id string, data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Path(id, "campaigns"), data, nil)
}

// RegistryCampaigns is generated from x-sdk-resource "RegistryCampaigns" in the relay-rest spec.
type RegistryCampaigns struct {
	Resource
}

// NewRegistryCampaigns constructs a RegistryCampaigns bound to base path "/api/relay/rest/registry/beta/campaigns".
func NewRegistryCampaigns(client HTTPClient) *RegistryCampaigns {
	return &RegistryCampaigns{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/campaigns"}}
}

func (r *RegistryCampaigns) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *RegistryCampaigns) Update(id string, data map[string]any) (map[string]any, error) {
	return r.HTTP.Put(r.Path(id), data)
}

func (r *RegistryCampaigns) ListNumbers(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "numbers"), params)
}

func (r *RegistryCampaigns) ListOrders(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "orders"), params)
}

func (r *RegistryCampaigns) CreateOrder(id string, data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Path(id, "orders"), data, nil)
}

// RegistryNumbers is generated from x-sdk-resource "RegistryNumbers" in the relay-rest spec.
type RegistryNumbers struct {
	Resource
}

// NewRegistryNumbers constructs a RegistryNumbers bound to base path "/api/relay/rest/registry/beta/numbers".
func NewRegistryNumbers(client HTTPClient) *RegistryNumbers {
	return &RegistryNumbers{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/numbers"}}
}

func (r *RegistryNumbers) Delete(id string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(id))
}

// RegistryOrders is generated from x-sdk-resource "RegistryOrders" in the relay-rest spec.
type RegistryOrders struct {
	Resource
}

// NewRegistryOrders constructs a RegistryOrders bound to base path "/api/relay/rest/registry/beta/orders".
func NewRegistryOrders(client HTTPClient) *RegistryOrders {
	return &RegistryOrders{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/orders"}}
}

func (r *RegistryOrders) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

// ShortCodesNamespace is generated from x-sdk-resource "ShortCodes" in the relay-rest spec.
type ShortCodesNamespace struct {
	Resource
}

// NewShortCodesNamespace constructs a ShortCodesNamespace bound to base path "/api/relay/rest/short_codes".
func NewShortCodesNamespace(client HTTPClient) *ShortCodesNamespace {
	return &ShortCodesNamespace{Resource{HTTP: client, Base: "/api/relay/rest/short_codes"}}
}

func (r *ShortCodesNamespace) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *ShortCodesNamespace) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *ShortCodesNamespace) Update(id string, data map[string]any) (map[string]any, error) {
	return r.HTTP.Put(r.Path(id), data)
}

// SIPProfileNamespace is generated from x-sdk-resource "SipProfile" in the relay-rest spec.
type SIPProfileNamespace struct {
	Resource
}

// NewSIPProfileNamespace constructs a SIPProfileNamespace bound to base path "/api/relay/rest/sip_profile".
func NewSIPProfileNamespace(client HTTPClient) *SIPProfileNamespace {
	return &SIPProfileNamespace{Resource{HTTP: client, Base: "/api/relay/rest/sip_profile"}}
}

func (r *SIPProfileNamespace) Get(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *SIPProfileNamespace) Update(data map[string]any) (map[string]any, error) {
	return r.HTTP.Put(r.Base, data)
}

// VerifiedCallersNamespace is generated from x-sdk-resource "VerifiedCallers" in the relay-rest spec.
type VerifiedCallersNamespace struct {
	*CrudResource
}

// NewVerifiedCallersNamespace constructs a VerifiedCallersNamespace bound to base path "/api/relay/rest/verified_caller_ids".
func NewVerifiedCallersNamespace(client HTTPClient) *VerifiedCallersNamespace {
	return &VerifiedCallersNamespace{NewCrudResourcePUT(client, "/api/relay/rest/verified_caller_ids")}
}

func (r *VerifiedCallersNamespace) RedialVerification(id string) (map[string]any, error) {
	return r.HTTP.Post(r.Path(id, "verification"), nil, nil)
}

func (r *VerifiedCallersNamespace) SubmitVerification(id string, data map[string]any) (map[string]any, error) {
	return r.HTTP.Put(r.Path(id, "verification"), data)
}
