// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "relay-rest" namespace spec.

package namespaces

import "context"

// AddressesNamespace is a client for the "Addresses" resource of the SignalWire relay-rest API.
type AddressesNamespace struct {
	Resource
}

// NewAddressesNamespace constructs a AddressesNamespace bound to base path "/api/relay/rest/addresses".
func NewAddressesNamespace(client HTTPClient) *AddressesNamespace {
	return &AddressesNamespace{Resource{HTTP: client, Base: "/api/relay/rest/addresses"}}
}

func (r *AddressesNamespace) List(ctx context.Context, params map[string]string, opts ...*RequestOptions) (*AddressListResponse, error) {
	return decodeResult[AddressListResponse](r.HTTP.Get(ctx, r.Base, params, opts...))
}

// AddressesNamespaceCreateParams holds the named optional parameters for AddressesNamespace.Create.
type AddressesNamespaceCreateParams struct {
	Label         string
	Country       string
	FirstName     string
	LastName      string
	StreetNumber  string
	StreetName    string
	City          string
	State         string
	PostalCode    string
	AddressType   *AddressType
	AddressNumber *string
	Extras        map[string]any
}

func (r *AddressesNamespace) Create(ctx context.Context, params AddressesNamespaceCreateParams, opts ...*RequestOptions) (*AddressResponse, error) {
	body := map[string]any{}
	body["label"] = params.Label
	body["country"] = params.Country
	body["first_name"] = params.FirstName
	body["last_name"] = params.LastName
	body["street_number"] = params.StreetNumber
	body["street_name"] = params.StreetName
	body["city"] = params.City
	body["state"] = params.State
	body["postal_code"] = params.PostalCode
	if params.AddressType != nil {
		body["address_type"] = params.AddressType
	}
	if params.AddressNumber != nil {
		body["address_number"] = params.AddressNumber
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[AddressResponse](r.HTTP.Post(ctx, r.Base, body, nil, opts...))
}

func (r *AddressesNamespace) Get(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*AddressResponse, error) {
	return decodeResult[AddressResponse](r.HTTP.Get(ctx, r.Path(id), params, opts...))
}

func (r *AddressesNamespace) Delete(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Delete(ctx, r.Path(id), opts...)
}

// ImportedNumbersNamespace is a client for the "ImportedNumbers" resource of the SignalWire relay-rest API.
type ImportedNumbersNamespace struct {
	Resource
}

// NewImportedNumbersNamespace constructs a ImportedNumbersNamespace bound to base path "/api/relay/rest/imported_phone_numbers".
func NewImportedNumbersNamespace(client HTTPClient) *ImportedNumbersNamespace {
	return &ImportedNumbersNamespace{Resource{HTTP: client, Base: "/api/relay/rest/imported_phone_numbers"}}
}

// ImportedNumbersNamespaceCreateParams holds the named optional parameters for ImportedNumbersNamespace.Create.
type ImportedNumbersNamespaceCreateParams struct {
	Number       string
	NumberType   string
	Capabilities []string
	Extras       map[string]any
}

func (r *ImportedNumbersNamespace) Create(ctx context.Context, params ImportedNumbersNamespaceCreateParams, opts ...*RequestOptions) (*PhoneNumberResponse, error) {
	body := map[string]any{}
	body["number"] = params.Number
	body["number_type"] = params.NumberType
	if params.Capabilities != nil {
		body["capabilities"] = params.Capabilities
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[PhoneNumberResponse](r.HTTP.Post(ctx, r.Base, body, nil, opts...))
}

// LookupNamespace is a client for the "Lookup" resource of the SignalWire relay-rest API.
type LookupNamespace struct {
	Resource
}

// NewLookupNamespace constructs a LookupNamespace bound to base path "/api/relay/rest/lookup".
func NewLookupNamespace(client HTTPClient) *LookupNamespace {
	return &LookupNamespace{Resource{HTTP: client, Base: "/api/relay/rest/lookup"}}
}

func (r *LookupNamespace) PhoneNumber(ctx context.Context, e164 string, params map[string]string, opts ...*RequestOptions) (*PhoneNumberLookupResponse, error) {
	return decodeResult[PhoneNumberLookupResponse](r.HTTP.Get(ctx, r.Path("phone_number", e164), params, opts...))
}

// MFANamespace is a client for the "Mfa" resource of the SignalWire relay-rest API.
type MFANamespace struct {
	Resource
}

// NewMFANamespace constructs a MFANamespace bound to base path "/api/relay/rest/mfa".
func NewMFANamespace(client HTTPClient) *MFANamespace {
	return &MFANamespace{Resource{HTTP: client, Base: "/api/relay/rest/mfa"}}
}

// MFANamespaceSMSParams holds the named optional parameters for MFANamespace.SMS.
type MFANamespaceSMSParams struct {
	To          string
	From        *string
	Message     *string
	TokenLength *int
	ValidFor    *int
	MaxAttempts *int
	AllowAlphas *bool
	Extras      map[string]any
}

func (r *MFANamespace) SMS(ctx context.Context, params MFANamespaceSMSParams, opts ...*RequestOptions) (*MfaResponse, error) {
	body := map[string]any{}
	body["to"] = params.To
	if params.From != nil {
		body["from"] = params.From
	}
	if params.Message != nil {
		body["message"] = params.Message
	}
	if params.TokenLength != nil {
		body["token_length"] = params.TokenLength
	}
	if params.ValidFor != nil {
		body["valid_for"] = params.ValidFor
	}
	if params.MaxAttempts != nil {
		body["max_attempts"] = params.MaxAttempts
	}
	if params.AllowAlphas != nil {
		body["allow_alphas"] = params.AllowAlphas
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[MfaResponse](r.HTTP.Post(ctx, r.Path("sms"), body, nil, opts...))
}

// MFANamespaceCallParams holds the named optional parameters for MFANamespace.Call.
type MFANamespaceCallParams struct {
	To          string
	From        *string
	Message     *string
	TokenLength *int
	ValidFor    *int
	MaxAttempts *int
	AllowAlphas *bool
	Extras      map[string]any
}

func (r *MFANamespace) Call(ctx context.Context, params MFANamespaceCallParams, opts ...*RequestOptions) (*MfaResponse, error) {
	body := map[string]any{}
	body["to"] = params.To
	if params.From != nil {
		body["from"] = params.From
	}
	if params.Message != nil {
		body["message"] = params.Message
	}
	if params.TokenLength != nil {
		body["token_length"] = params.TokenLength
	}
	if params.ValidFor != nil {
		body["valid_for"] = params.ValidFor
	}
	if params.MaxAttempts != nil {
		body["max_attempts"] = params.MaxAttempts
	}
	if params.AllowAlphas != nil {
		body["allow_alphas"] = params.AllowAlphas
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[MfaResponse](r.HTTP.Post(ctx, r.Path("call"), body, nil, opts...))
}

// MFANamespaceVerifyParams holds the named optional parameters for MFANamespace.Verify.
type MFANamespaceVerifyParams struct {
	Token  string
	Extras map[string]any
}

func (r *MFANamespace) Verify(ctx context.Context, requestID string, params MFANamespaceVerifyParams, opts ...*RequestOptions) (*MfaVerifyResponse, error) {
	body := map[string]any{}
	body["token"] = params.Token
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[MfaVerifyResponse](r.HTTP.Post(ctx, r.Path(requestID, "verify"), body, nil, opts...))
}

// NumberGroupsNamespace is a client for the "NumberGroups" resource of the SignalWire relay-rest API.
type NumberGroupsNamespace struct {
	*CrudResource
}

// NewNumberGroupsNamespace constructs a NumberGroupsNamespace bound to base path "/api/relay/rest/number_groups".
func NewNumberGroupsNamespace(client HTTPClient) *NumberGroupsNamespace {
	return &NumberGroupsNamespace{NewCrudResourcePUT(client, "/api/relay/rest/number_groups")}
}

func (r *NumberGroupsNamespace) ListMemberships(ctx context.Context, groupID string, params map[string]string, opts ...*RequestOptions) (*NumberGroupMembershipListResponse, error) {
	return decodeResult[NumberGroupMembershipListResponse](r.HTTP.Get(ctx, r.Path(groupID, "number_group_memberships"), params, opts...))
}

// NumberGroupsNamespaceAddMembershipParams holds the named optional parameters for NumberGroupsNamespace.AddMembership.
type NumberGroupsNamespaceAddMembershipParams struct {
	PhoneNumberID Uuid
	Extras        map[string]any
}

func (r *NumberGroupsNamespace) AddMembership(ctx context.Context, groupID string, params NumberGroupsNamespaceAddMembershipParams, opts ...*RequestOptions) (*NumberGroupMembershipResponse, error) {
	body := map[string]any{}
	body["phone_number_id"] = params.PhoneNumberID
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[NumberGroupMembershipResponse](r.HTTP.Post(ctx, r.Path(groupID, "number_group_memberships"), body, nil, opts...))
}

func (r *NumberGroupsNamespace) GetMembership(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*NumberGroupMembershipResponse, error) {
	return decodeResult[NumberGroupMembershipResponse](r.HTTP.Get(ctx, "/api/relay/rest/number_group_memberships/"+id, params, opts...))
}

func (r *NumberGroupsNamespace) DeleteMembership(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Delete(ctx, "/api/relay/rest/number_group_memberships/"+id, opts...)
}

// PhoneNumbersNamespace is a client for the "PhoneNumbers" resource of the SignalWire relay-rest API.
type PhoneNumbersNamespace struct {
	*CrudResource
}

// NewPhoneNumbersNamespace constructs a PhoneNumbersNamespace bound to base path "/api/relay/rest/phone_numbers".
func NewPhoneNumbersNamespace(client HTTPClient) *PhoneNumbersNamespace {
	return &PhoneNumbersNamespace{NewCrudResourcePUT(client, "/api/relay/rest/phone_numbers")}
}

func (r *PhoneNumbersNamespace) Search(ctx context.Context, params map[string]string, opts ...*RequestOptions) (*AvailablePhoneNumbersResponse, error) {
	return decodeResult[AvailablePhoneNumbersResponse](r.HTTP.Get(ctx, r.Path("search"), params, opts...))
}

func (r *PhoneNumbersNamespace) SetSwmlWebhook(ctx context.Context, sid string, url string, requestOptions *RequestOptions, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":          "relay_script",
		"call_relay_script_url": url,
	}
	mergeExtra(body, extra)
	return r.Update(ctx, sid, body, requestOptions)
}

func (r *PhoneNumbersNamespace) SetCxmlWebhook(ctx context.Context, sid string, url string, fallback_url *string, status_callback_url *string, requestOptions *RequestOptions, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "laml_webhooks",
		"call_request_url": url,
	}
	if fallback_url != nil {
		body["call_fallback_url"] = *fallback_url
	}
	if status_callback_url != nil {
		body["call_status_callback_url"] = *status_callback_url
	}
	mergeExtra(body, extra)
	return r.Update(ctx, sid, body, requestOptions)
}

func (r *PhoneNumbersNamespace) SetCxmlApplication(ctx context.Context, sid string, application_id string, requestOptions *RequestOptions, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":             "laml_application",
		"call_laml_application_id": application_id,
	}
	mergeExtra(body, extra)
	return r.Update(ctx, sid, body, requestOptions)
}

func (r *PhoneNumbersNamespace) SetAiAgent(ctx context.Context, sid string, agent_id string, requestOptions *RequestOptions, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "ai_agent",
		"call_ai_agent_id": agent_id,
	}
	mergeExtra(body, extra)
	return r.Update(ctx, sid, body, requestOptions)
}

func (r *PhoneNumbersNamespace) SetCallFlow(ctx context.Context, sid string, flow_id string, version *string, requestOptions *RequestOptions, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler": "call_flow",
		"call_flow_id": flow_id,
	}
	if version != nil {
		body["call_flow_version"] = *version
	}
	mergeExtra(body, extra)
	return r.Update(ctx, sid, body, requestOptions)
}

func (r *PhoneNumbersNamespace) SetRelayApplication(ctx context.Context, sid string, name string, requestOptions *RequestOptions, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":           "relay_application",
		"call_relay_application": name,
	}
	mergeExtra(body, extra)
	return r.Update(ctx, sid, body, requestOptions)
}

func (r *PhoneNumbersNamespace) SetRelayTopic(ctx context.Context, sid string, topic string, status_callback_url *string, requestOptions *RequestOptions, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "relay_topic",
		"call_relay_topic": topic,
	}
	if status_callback_url != nil {
		body["call_relay_topic_status_callback_url"] = *status_callback_url
	}
	mergeExtra(body, extra)
	return r.Update(ctx, sid, body, requestOptions)
}

// QueuesNamespace is a client for the "Queues" resource of the SignalWire relay-rest API.
type QueuesNamespace struct {
	*CrudResource
}

// NewQueuesNamespace constructs a QueuesNamespace bound to base path "/api/relay/rest/queues".
func NewQueuesNamespace(client HTTPClient) *QueuesNamespace {
	return &QueuesNamespace{NewCrudResourcePUT(client, "/api/relay/rest/queues")}
}

func (r *QueuesNamespace) ListMembers(ctx context.Context, queueID string, params map[string]string, opts ...*RequestOptions) (*QueueMemberListResponse, error) {
	return decodeResult[QueueMemberListResponse](r.HTTP.Get(ctx, r.Path(queueID, "members"), params, opts...))
}

func (r *QueuesNamespace) GetNextMember(ctx context.Context, queueID string, params map[string]string, opts ...*RequestOptions) (*QueueMemberResponse, error) {
	return decodeResult[QueueMemberResponse](r.HTTP.Get(ctx, r.Path(queueID, "members", "next"), params, opts...))
}

func (r *QueuesNamespace) GetMember(ctx context.Context, queueID string, id string, params map[string]string, opts ...*RequestOptions) (*QueueMemberResponse, error) {
	return decodeResult[QueueMemberResponse](r.HTTP.Get(ctx, r.Path(queueID, "members", id), params, opts...))
}

// RecordingsNamespace is a client for the "Recordings" resource of the SignalWire relay-rest API.
type RecordingsNamespace struct {
	Resource
}

// NewRecordingsNamespace constructs a RecordingsNamespace bound to base path "/api/relay/rest/recordings".
func NewRecordingsNamespace(client HTTPClient) *RecordingsNamespace {
	return &RecordingsNamespace{Resource{HTTP: client, Base: "/api/relay/rest/recordings"}}
}

func (r *RecordingsNamespace) List(ctx context.Context, params map[string]string, opts ...*RequestOptions) (*RecordingListResponse, error) {
	return decodeResult[RecordingListResponse](r.HTTP.Get(ctx, r.Base, params, opts...))
}

func (r *RecordingsNamespace) Get(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Get(ctx, r.Path(id), params, opts...)
}

func (r *RecordingsNamespace) Delete(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Delete(ctx, r.Path(id), opts...)
}

// RegistryBrands is a client for the "RegistryBrands" resource of the SignalWire relay-rest API.
type RegistryBrands struct {
	Resource
}

// NewRegistryBrands constructs a RegistryBrands bound to base path "/api/relay/rest/registry/beta/brands".
func NewRegistryBrands(client HTTPClient) *RegistryBrands {
	return &RegistryBrands{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/brands"}}
}

func (r *RegistryBrands) List(ctx context.Context, params map[string]string, opts ...*RequestOptions) (*BrandListResponse, error) {
	return decodeResult[BrandListResponse](r.HTTP.Get(ctx, r.Base, params, opts...))
}

func (r *RegistryBrands) Create(ctx context.Context, data map[string]any, opts ...*RequestOptions) (*BrandResponse, error) {
	return decodeResult[BrandResponse](r.HTTP.Post(ctx, r.Base, data, nil, opts...))
}

func (r *RegistryBrands) Get(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*BrandResponse, error) {
	return decodeResult[BrandResponse](r.HTTP.Get(ctx, r.Path(id), params, opts...))
}

func (r *RegistryBrands) ListCampaigns(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*CampaignListResponse, error) {
	return decodeResult[CampaignListResponse](r.HTTP.Get(ctx, r.Path(id, "campaigns"), params, opts...))
}

func (r *RegistryBrands) CreateCampaign(ctx context.Context, id string, data map[string]any, opts ...*RequestOptions) (*CampaignResponse, error) {
	return decodeResult[CampaignResponse](r.HTTP.Post(ctx, r.Path(id, "campaigns"), data, nil, opts...))
}

// RegistryCampaigns is a client for the "RegistryCampaigns" resource of the SignalWire relay-rest API.
type RegistryCampaigns struct {
	Resource
}

// NewRegistryCampaigns constructs a RegistryCampaigns bound to base path "/api/relay/rest/registry/beta/campaigns".
func NewRegistryCampaigns(client HTTPClient) *RegistryCampaigns {
	return &RegistryCampaigns{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/campaigns"}}
}

func (r *RegistryCampaigns) Get(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*CampaignResponse, error) {
	return decodeResult[CampaignResponse](r.HTTP.Get(ctx, r.Path(id), params, opts...))
}

// RegistryCampaignsUpdateParams holds the named optional parameters for RegistryCampaigns.Update.
type RegistryCampaignsUpdateParams struct {
	Name   *string
	Extras map[string]any
}

func (r *RegistryCampaigns) Update(ctx context.Context, id string, params RegistryCampaignsUpdateParams, opts ...*RequestOptions) (*CampaignResponse, error) {
	body := map[string]any{}
	if params.Name != nil {
		body["name"] = params.Name
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[CampaignResponse](r.HTTP.Put(ctx, r.Path(id), body, opts...))
}

func (r *RegistryCampaigns) ListNumbers(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*AssignedNumberListResponse, error) {
	return decodeResult[AssignedNumberListResponse](r.HTTP.Get(ctx, r.Path(id, "numbers"), params, opts...))
}

func (r *RegistryCampaigns) ListOrders(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*OrderListResponse, error) {
	return decodeResult[OrderListResponse](r.HTTP.Get(ctx, r.Path(id, "orders"), params, opts...))
}

// RegistryCampaignsCreateOrderParams holds the named optional parameters for RegistryCampaigns.CreateOrder.
type RegistryCampaignsCreateOrderParams struct {
	PhoneNumbers      []string
	StatusCallbackURL *string
	Extras            map[string]any
}

func (r *RegistryCampaigns) CreateOrder(ctx context.Context, id string, params RegistryCampaignsCreateOrderParams, opts ...*RequestOptions) (*OrderResponse, error) {
	body := map[string]any{}
	if params.PhoneNumbers != nil {
		body["phone_numbers"] = params.PhoneNumbers
	}
	if params.StatusCallbackURL != nil {
		body["status_callback_url"] = params.StatusCallbackURL
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[OrderResponse](r.HTTP.Post(ctx, r.Path(id, "orders"), body, nil, opts...))
}

// RegistryNumbers is a client for the "RegistryNumbers" resource of the SignalWire relay-rest API.
type RegistryNumbers struct {
	Resource
}

// NewRegistryNumbers constructs a RegistryNumbers bound to base path "/api/relay/rest/registry/beta/numbers".
func NewRegistryNumbers(client HTTPClient) *RegistryNumbers {
	return &RegistryNumbers{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/numbers"}}
}

func (r *RegistryNumbers) Delete(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Delete(ctx, r.Path(id), opts...)
}

// RegistryOrders is a client for the "RegistryOrders" resource of the SignalWire relay-rest API.
type RegistryOrders struct {
	Resource
}

// NewRegistryOrders constructs a RegistryOrders bound to base path "/api/relay/rest/registry/beta/orders".
func NewRegistryOrders(client HTTPClient) *RegistryOrders {
	return &RegistryOrders{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/orders"}}
}

func (r *RegistryOrders) Get(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*OrderResponse, error) {
	return decodeResult[OrderResponse](r.HTTP.Get(ctx, r.Path(id), params, opts...))
}

// ShortCodesNamespace is a client for the "ShortCodes" resource of the SignalWire relay-rest API.
type ShortCodesNamespace struct {
	Resource
}

// NewShortCodesNamespace constructs a ShortCodesNamespace bound to base path "/api/relay/rest/short_codes".
func NewShortCodesNamespace(client HTTPClient) *ShortCodesNamespace {
	return &ShortCodesNamespace{Resource{HTTP: client, Base: "/api/relay/rest/short_codes"}}
}

func (r *ShortCodesNamespace) List(ctx context.Context, params map[string]string, opts ...*RequestOptions) (*ShortCodeListResponse, error) {
	return decodeResult[ShortCodeListResponse](r.HTTP.Get(ctx, r.Base, params, opts...))
}

func (r *ShortCodesNamespace) Get(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*ShortCodeResponse, error) {
	return decodeResult[ShortCodeResponse](r.HTTP.Get(ctx, r.Path(id), params, opts...))
}

// ShortCodesNamespaceUpdateParams holds the named optional parameters for ShortCodesNamespace.Update.
type ShortCodesNamespaceUpdateParams struct {
	Name                     string
	MessageHandler           ShortCodeMessageHandler
	MessageRequestURL        *string
	MessageRequestMethod     *HttpMethod
	MessageFallbackURL       *string
	MessageFallbackMethod    *HttpMethod
	MessageLamlApplicationID *Uuid
	MessageRelayContext      *string
	Extras                   map[string]any
}

func (r *ShortCodesNamespace) Update(ctx context.Context, id string, params ShortCodesNamespaceUpdateParams, opts ...*RequestOptions) (*ShortCodeResponse, error) {
	body := map[string]any{}
	body["name"] = params.Name
	body["message_handler"] = params.MessageHandler
	if params.MessageRequestURL != nil {
		body["message_request_url"] = params.MessageRequestURL
	}
	if params.MessageRequestMethod != nil {
		body["message_request_method"] = params.MessageRequestMethod
	}
	if params.MessageFallbackURL != nil {
		body["message_fallback_url"] = params.MessageFallbackURL
	}
	if params.MessageFallbackMethod != nil {
		body["message_fallback_method"] = params.MessageFallbackMethod
	}
	if params.MessageLamlApplicationID != nil {
		body["message_laml_application_id"] = params.MessageLamlApplicationID
	}
	if params.MessageRelayContext != nil {
		body["message_relay_context"] = params.MessageRelayContext
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[ShortCodeResponse](r.HTTP.Put(ctx, r.Path(id), body, opts...))
}

// SIPProfileNamespace is a client for the "SipProfile" resource of the SignalWire relay-rest API.
type SIPProfileNamespace struct {
	Resource
}

// NewSIPProfileNamespace constructs a SIPProfileNamespace bound to base path "/api/relay/rest/sip_profile".
func NewSIPProfileNamespace(client HTTPClient) *SIPProfileNamespace {
	return &SIPProfileNamespace{Resource{HTTP: client, Base: "/api/relay/rest/sip_profile"}}
}

func (r *SIPProfileNamespace) Get(ctx context.Context, params map[string]string, opts ...*RequestOptions) (*SipProfileResponse, error) {
	return decodeResult[SipProfileResponse](r.HTTP.Get(ctx, r.Base, params, opts...))
}

// SIPProfileNamespaceUpdateParams holds the named optional parameters for SIPProfileNamespace.Update.
type SIPProfileNamespaceUpdateParams struct {
	DomainIdentifier  *string
	DefaultCodecs     []string
	DefaultCiphers    []string
	DefaultEncryption *string
	DefaultSendAs     *string
	Extras            map[string]any
}

func (r *SIPProfileNamespace) Update(ctx context.Context, params SIPProfileNamespaceUpdateParams, opts ...*RequestOptions) (*SipProfileResponse, error) {
	body := map[string]any{}
	if params.DomainIdentifier != nil {
		body["domain_identifier"] = params.DomainIdentifier
	}
	if params.DefaultCodecs != nil {
		body["default_codecs"] = params.DefaultCodecs
	}
	if params.DefaultCiphers != nil {
		body["default_ciphers"] = params.DefaultCiphers
	}
	if params.DefaultEncryption != nil {
		body["default_encryption"] = params.DefaultEncryption
	}
	if params.DefaultSendAs != nil {
		body["default_send_as"] = params.DefaultSendAs
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[SipProfileResponse](r.HTTP.Put(ctx, r.Base, body, opts...))
}

// VerifiedCallersNamespace is a client for the "VerifiedCallers" resource of the SignalWire relay-rest API.
type VerifiedCallersNamespace struct {
	*CrudResource
}

// NewVerifiedCallersNamespace constructs a VerifiedCallersNamespace bound to base path "/api/relay/rest/verified_caller_ids".
func NewVerifiedCallersNamespace(client HTTPClient) *VerifiedCallersNamespace {
	return &VerifiedCallersNamespace{NewCrudResourcePUT(client, "/api/relay/rest/verified_caller_ids")}
}

func (r *VerifiedCallersNamespace) RedialVerification(ctx context.Context, id string, opts ...*RequestOptions) (*VerifiedCallerIDResponse, error) {
	return decodeResult[VerifiedCallerIDResponse](r.HTTP.Post(ctx, r.Path(id, "verification"), nil, nil, opts...))
}

// VerifiedCallersNamespaceSubmitVerificationParams holds the named optional parameters for VerifiedCallersNamespace.SubmitVerification.
type VerifiedCallersNamespaceSubmitVerificationParams struct {
	VerificationCode string
	Extras           map[string]any
}

func (r *VerifiedCallersNamespace) SubmitVerification(ctx context.Context, id string, params VerifiedCallersNamespaceSubmitVerificationParams, opts ...*RequestOptions) (*VerifiedCallerIDResponse, error) {
	body := map[string]any{}
	body["verification_code"] = params.VerificationCode
	mergeExtra(body, []map[string]any{params.Extras})
	return decodeResult[VerifiedCallerIDResponse](r.HTTP.Put(ctx, r.Path(id, "verification"), body, opts...))
}
