// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "relay-rest" namespace spec.

package namespaces

// AddressesNamespace is generated from x-sdk-resource "Addresses" in the relay-rest spec.
type AddressesNamespace struct {
	Resource
}

// NewAddressesNamespace constructs a AddressesNamespace bound to base path "/api/relay/rest/addresses".
func NewAddressesNamespace(client HTTPClient) *AddressesNamespace {
	return &AddressesNamespace{Resource{HTTP: client, Base: "/api/relay/rest/addresses"}}
}

func (r *AddressesNamespace) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

// AddressesNamespaceCreateParams holds the named optional parameters for AddressesNamespace.Create.
type AddressesNamespaceCreateParams struct {
	Label         any
	Country       any
	FirstName     any
	LastName      any
	StreetNumber  any
	StreetName    any
	City          any
	State         any
	PostalCode    any
	AddressType   any
	AddressNumber any
	Extras        map[string]any
}

func (r *AddressesNamespace) Create(params AddressesNamespaceCreateParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Label != nil {
		body["label"] = params.Label
	}
	if params.Country != nil {
		body["country"] = params.Country
	}
	if params.FirstName != nil {
		body["first_name"] = params.FirstName
	}
	if params.LastName != nil {
		body["last_name"] = params.LastName
	}
	if params.StreetNumber != nil {
		body["street_number"] = params.StreetNumber
	}
	if params.StreetName != nil {
		body["street_name"] = params.StreetName
	}
	if params.City != nil {
		body["city"] = params.City
	}
	if params.State != nil {
		body["state"] = params.State
	}
	if params.PostalCode != nil {
		body["postal_code"] = params.PostalCode
	}
	if params.AddressType != nil {
		body["address_type"] = params.AddressType
	}
	if params.AddressNumber != nil {
		body["address_number"] = params.AddressNumber
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Post(r.Base, body, nil)
}

func (r *AddressesNamespace) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *AddressesNamespace) Delete(id string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(id))
}

// ImportedNumbersNamespace is generated from x-sdk-resource "ImportedNumbers" in the relay-rest spec.
type ImportedNumbersNamespace struct {
	Resource
}

// NewImportedNumbersNamespace constructs a ImportedNumbersNamespace bound to base path "/api/relay/rest/imported_phone_numbers".
func NewImportedNumbersNamespace(client HTTPClient) *ImportedNumbersNamespace {
	return &ImportedNumbersNamespace{Resource{HTTP: client, Base: "/api/relay/rest/imported_phone_numbers"}}
}

// ImportedNumbersNamespaceCreateParams holds the named optional parameters for ImportedNumbersNamespace.Create.
type ImportedNumbersNamespaceCreateParams struct {
	Number       any
	NumberType   any
	Capabilities any
	Extras       map[string]any
}

func (r *ImportedNumbersNamespace) Create(params ImportedNumbersNamespaceCreateParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Number != nil {
		body["number"] = params.Number
	}
	if params.NumberType != nil {
		body["number_type"] = params.NumberType
	}
	if params.Capabilities != nil {
		body["capabilities"] = params.Capabilities
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Post(r.Base, body, nil)
}

// LookupNamespace is generated from x-sdk-resource "Lookup" in the relay-rest spec.
type LookupNamespace struct {
	Resource
}

// NewLookupNamespace constructs a LookupNamespace bound to base path "/api/relay/rest/lookup".
func NewLookupNamespace(client HTTPClient) *LookupNamespace {
	return &LookupNamespace{Resource{HTTP: client, Base: "/api/relay/rest/lookup"}}
}

func (r *LookupNamespace) PhoneNumber(e164 string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path("phone_number", e164), params)
}

// MFANamespace is generated from x-sdk-resource "Mfa" in the relay-rest spec.
type MFANamespace struct {
	Resource
}

// NewMFANamespace constructs a MFANamespace bound to base path "/api/relay/rest/mfa".
func NewMFANamespace(client HTTPClient) *MFANamespace {
	return &MFANamespace{Resource{HTTP: client, Base: "/api/relay/rest/mfa"}}
}

// MFANamespaceSMSParams holds the named optional parameters for MFANamespace.SMS.
type MFANamespaceSMSParams struct {
	To          any
	From        any
	Message     any
	TokenLength any
	ValidFor    any
	MaxAttempts any
	AllowAlphas any
	Extras      map[string]any
}

func (r *MFANamespace) SMS(params MFANamespaceSMSParams) (map[string]any, error) {
	body := map[string]any{}
	if params.To != nil {
		body["to"] = params.To
	}
	if params.From != nil {
		body["from"] = params.From
	}
	if params.Message != nil {
		body["message"] = params.Message
	}
	if params.TokenLength != nil {
		body["token_length"] = params.TokenLength
	}
	if params.ValidFor != nil {
		body["valid_for"] = params.ValidFor
	}
	if params.MaxAttempts != nil {
		body["max_attempts"] = params.MaxAttempts
	}
	if params.AllowAlphas != nil {
		body["allow_alphas"] = params.AllowAlphas
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Post(r.Path("sms"), body, nil)
}

// MFANamespaceCallParams holds the named optional parameters for MFANamespace.Call.
type MFANamespaceCallParams struct {
	To          any
	From        any
	Message     any
	TokenLength any
	ValidFor    any
	MaxAttempts any
	AllowAlphas any
	Extras      map[string]any
}

func (r *MFANamespace) Call(params MFANamespaceCallParams) (map[string]any, error) {
	body := map[string]any{}
	if params.To != nil {
		body["to"] = params.To
	}
	if params.From != nil {
		body["from"] = params.From
	}
	if params.Message != nil {
		body["message"] = params.Message
	}
	if params.TokenLength != nil {
		body["token_length"] = params.TokenLength
	}
	if params.ValidFor != nil {
		body["valid_for"] = params.ValidFor
	}
	if params.MaxAttempts != nil {
		body["max_attempts"] = params.MaxAttempts
	}
	if params.AllowAlphas != nil {
		body["allow_alphas"] = params.AllowAlphas
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Post(r.Path("call"), body, nil)
}

// MFANamespaceVerifyParams holds the named optional parameters for MFANamespace.Verify.
type MFANamespaceVerifyParams struct {
	Token  any
	Extras map[string]any
}

func (r *MFANamespace) Verify(requestID string, params MFANamespaceVerifyParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Token != nil {
		body["token"] = params.Token
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Post(r.Path(requestID, "verify"), body, nil)
}

// NumberGroupsNamespace is generated from x-sdk-resource "NumberGroups" in the relay-rest spec.
type NumberGroupsNamespace struct {
	*CrudResource
}

// NewNumberGroupsNamespace constructs a NumberGroupsNamespace bound to base path "/api/relay/rest/number_groups".
func NewNumberGroupsNamespace(client HTTPClient) *NumberGroupsNamespace {
	return &NumberGroupsNamespace{NewCrudResourcePUT(client, "/api/relay/rest/number_groups")}
}

func (r *NumberGroupsNamespace) ListMemberships(groupID string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(groupID, "number_group_memberships"), params)
}

// NumberGroupsNamespaceAddMembershipParams holds the named optional parameters for NumberGroupsNamespace.AddMembership.
type NumberGroupsNamespaceAddMembershipParams struct {
	PhoneNumberId any
	Extras        map[string]any
}

func (r *NumberGroupsNamespace) AddMembership(groupID string, params NumberGroupsNamespaceAddMembershipParams) (map[string]any, error) {
	body := map[string]any{}
	if params.PhoneNumberId != nil {
		body["phone_number_id"] = params.PhoneNumberId
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Post(r.Path(groupID, "number_group_memberships"), body, nil)
}

func (r *NumberGroupsNamespace) GetMembership(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get("/api/relay/rest/number_group_memberships/"+id, params)
}

func (r *NumberGroupsNamespace) DeleteMembership(id string) (map[string]any, error) {
	return r.HTTP.Delete("/api/relay/rest/number_group_memberships/" + id)
}

// PhoneNumbersNamespace is generated from x-sdk-resource "PhoneNumbers" in the relay-rest spec.
type PhoneNumbersNamespace struct {
	*CrudResource
}

// NewPhoneNumbersNamespace constructs a PhoneNumbersNamespace bound to base path "/api/relay/rest/phone_numbers".
func NewPhoneNumbersNamespace(client HTTPClient) *PhoneNumbersNamespace {
	return &PhoneNumbersNamespace{NewCrudResourcePUT(client, "/api/relay/rest/phone_numbers")}
}

func (r *PhoneNumbersNamespace) Search(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path("search"), params)
}

func (r *PhoneNumbersNamespace) SetSwmlWebhook(sid string, url string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":          "relay_script",
		"call_relay_script_url": url,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetCxmlWebhook(sid string, url string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "laml_webhooks",
		"call_request_url": url,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetCxmlApplication(sid string, application_id string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":             "laml_application",
		"call_laml_application_id": application_id,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetAiAgent(sid string, agent_id string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "ai_agent",
		"call_ai_agent_id": agent_id,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetCallFlow(sid string, flow_id string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler": "call_flow",
		"call_flow_id": flow_id,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetRelayApplication(sid string, name string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":           "relay_application",
		"call_relay_application": name,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

func (r *PhoneNumbersNamespace) SetRelayTopic(sid string, topic string, extra ...map[string]any) (map[string]any, error) {
	body := map[string]any{
		"call_handler":     "relay_topic",
		"call_relay_topic": topic,
	}
	mergeExtra(body, extra)
	return r.Update(sid, body)
}

// QueuesNamespace is generated from x-sdk-resource "Queues" in the relay-rest spec.
type QueuesNamespace struct {
	*CrudResource
}

// NewQueuesNamespace constructs a QueuesNamespace bound to base path "/api/relay/rest/queues".
func NewQueuesNamespace(client HTTPClient) *QueuesNamespace {
	return &QueuesNamespace{NewCrudResourcePUT(client, "/api/relay/rest/queues")}
}

func (r *QueuesNamespace) ListMembers(queueID string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(queueID, "members"), params)
}

func (r *QueuesNamespace) GetNextMember(queueID string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(queueID, "members", "next"), params)
}

func (r *QueuesNamespace) GetMember(queueID string, id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(queueID, "members", id), params)
}

// RecordingsNamespace is generated from x-sdk-resource "Recordings" in the relay-rest spec.
type RecordingsNamespace struct {
	Resource
}

// NewRecordingsNamespace constructs a RecordingsNamespace bound to base path "/api/relay/rest/recordings".
func NewRecordingsNamespace(client HTTPClient) *RecordingsNamespace {
	return &RecordingsNamespace{Resource{HTTP: client, Base: "/api/relay/rest/recordings"}}
}

func (r *RecordingsNamespace) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *RecordingsNamespace) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *RecordingsNamespace) Delete(id string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(id))
}

// RegistryBrands is generated from x-sdk-resource "RegistryBrands" in the relay-rest spec.
type RegistryBrands struct {
	Resource
}

// NewRegistryBrands constructs a RegistryBrands bound to base path "/api/relay/rest/registry/beta/brands".
func NewRegistryBrands(client HTTPClient) *RegistryBrands {
	return &RegistryBrands{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/brands"}}
}

func (r *RegistryBrands) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *RegistryBrands) Create(data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Base, data, nil)
}

func (r *RegistryBrands) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *RegistryBrands) ListCampaigns(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "campaigns"), params)
}

func (r *RegistryBrands) CreateCampaign(id string, data map[string]any) (map[string]any, error) {
	return r.HTTP.Post(r.Path(id, "campaigns"), data, nil)
}

// RegistryCampaigns is generated from x-sdk-resource "RegistryCampaigns" in the relay-rest spec.
type RegistryCampaigns struct {
	Resource
}

// NewRegistryCampaigns constructs a RegistryCampaigns bound to base path "/api/relay/rest/registry/beta/campaigns".
func NewRegistryCampaigns(client HTTPClient) *RegistryCampaigns {
	return &RegistryCampaigns{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/campaigns"}}
}

func (r *RegistryCampaigns) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

// RegistryCampaignsUpdateParams holds the named optional parameters for RegistryCampaigns.Update.
type RegistryCampaignsUpdateParams struct {
	Name   any
	Extras map[string]any
}

func (r *RegistryCampaigns) Update(id string, params RegistryCampaignsUpdateParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Name != nil {
		body["name"] = params.Name
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Put(r.Path(id), body)
}

func (r *RegistryCampaigns) ListNumbers(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "numbers"), params)
}

func (r *RegistryCampaigns) ListOrders(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "orders"), params)
}

// RegistryCampaignsCreateOrderParams holds the named optional parameters for RegistryCampaigns.CreateOrder.
type RegistryCampaignsCreateOrderParams struct {
	PhoneNumbers      any
	StatusCallbackUrl any
	Extras            map[string]any
}

func (r *RegistryCampaigns) CreateOrder(id string, params RegistryCampaignsCreateOrderParams) (map[string]any, error) {
	body := map[string]any{}
	if params.PhoneNumbers != nil {
		body["phone_numbers"] = params.PhoneNumbers
	}
	if params.StatusCallbackUrl != nil {
		body["status_callback_url"] = params.StatusCallbackUrl
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Post(r.Path(id, "orders"), body, nil)
}

// RegistryNumbers is generated from x-sdk-resource "RegistryNumbers" in the relay-rest spec.
type RegistryNumbers struct {
	Resource
}

// NewRegistryNumbers constructs a RegistryNumbers bound to base path "/api/relay/rest/registry/beta/numbers".
func NewRegistryNumbers(client HTTPClient) *RegistryNumbers {
	return &RegistryNumbers{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/numbers"}}
}

func (r *RegistryNumbers) Delete(id string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(id))
}

// RegistryOrders is generated from x-sdk-resource "RegistryOrders" in the relay-rest spec.
type RegistryOrders struct {
	Resource
}

// NewRegistryOrders constructs a RegistryOrders bound to base path "/api/relay/rest/registry/beta/orders".
func NewRegistryOrders(client HTTPClient) *RegistryOrders {
	return &RegistryOrders{Resource{HTTP: client, Base: "/api/relay/rest/registry/beta/orders"}}
}

func (r *RegistryOrders) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

// ShortCodesNamespace is generated from x-sdk-resource "ShortCodes" in the relay-rest spec.
type ShortCodesNamespace struct {
	Resource
}

// NewShortCodesNamespace constructs a ShortCodesNamespace bound to base path "/api/relay/rest/short_codes".
func NewShortCodesNamespace(client HTTPClient) *ShortCodesNamespace {
	return &ShortCodesNamespace{Resource{HTTP: client, Base: "/api/relay/rest/short_codes"}}
}

func (r *ShortCodesNamespace) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *ShortCodesNamespace) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

// ShortCodesNamespaceUpdateParams holds the named optional parameters for ShortCodesNamespace.Update.
type ShortCodesNamespaceUpdateParams struct {
	Name                     any
	MessageHandler           any
	MessageRequestUrl        any
	MessageRequestMethod     any
	MessageFallbackUrl       any
	MessageFallbackMethod    any
	MessageLamlApplicationId any
	MessageRelayContext      any
	Extras                   map[string]any
}

func (r *ShortCodesNamespace) Update(id string, params ShortCodesNamespaceUpdateParams) (map[string]any, error) {
	body := map[string]any{}
	if params.Name != nil {
		body["name"] = params.Name
	}
	if params.MessageHandler != nil {
		body["message_handler"] = params.MessageHandler
	}
	if params.MessageRequestUrl != nil {
		body["message_request_url"] = params.MessageRequestUrl
	}
	if params.MessageRequestMethod != nil {
		body["message_request_method"] = params.MessageRequestMethod
	}
	if params.MessageFallbackUrl != nil {
		body["message_fallback_url"] = params.MessageFallbackUrl
	}
	if params.MessageFallbackMethod != nil {
		body["message_fallback_method"] = params.MessageFallbackMethod
	}
	if params.MessageLamlApplicationId != nil {
		body["message_laml_application_id"] = params.MessageLamlApplicationId
	}
	if params.MessageRelayContext != nil {
		body["message_relay_context"] = params.MessageRelayContext
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Put(r.Path(id), body)
}

// SIPProfileNamespace is generated from x-sdk-resource "SipProfile" in the relay-rest spec.
type SIPProfileNamespace struct {
	Resource
}

// NewSIPProfileNamespace constructs a SIPProfileNamespace bound to base path "/api/relay/rest/sip_profile".
func NewSIPProfileNamespace(client HTTPClient) *SIPProfileNamespace {
	return &SIPProfileNamespace{Resource{HTTP: client, Base: "/api/relay/rest/sip_profile"}}
}

func (r *SIPProfileNamespace) Get(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

// SIPProfileNamespaceUpdateParams holds the named optional parameters for SIPProfileNamespace.Update.
type SIPProfileNamespaceUpdateParams struct {
	DomainIdentifier  any
	DefaultCodecs     any
	DefaultCiphers    any
	DefaultEncryption any
	DefaultSendAs     any
	Extras            map[string]any
}

func (r *SIPProfileNamespace) Update(params SIPProfileNamespaceUpdateParams) (map[string]any, error) {
	body := map[string]any{}
	if params.DomainIdentifier != nil {
		body["domain_identifier"] = params.DomainIdentifier
	}
	if params.DefaultCodecs != nil {
		body["default_codecs"] = params.DefaultCodecs
	}
	if params.DefaultCiphers != nil {
		body["default_ciphers"] = params.DefaultCiphers
	}
	if params.DefaultEncryption != nil {
		body["default_encryption"] = params.DefaultEncryption
	}
	if params.DefaultSendAs != nil {
		body["default_send_as"] = params.DefaultSendAs
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Put(r.Base, body)
}

// VerifiedCallersNamespace is generated from x-sdk-resource "VerifiedCallers" in the relay-rest spec.
type VerifiedCallersNamespace struct {
	*CrudResource
}

// NewVerifiedCallersNamespace constructs a VerifiedCallersNamespace bound to base path "/api/relay/rest/verified_caller_ids".
func NewVerifiedCallersNamespace(client HTTPClient) *VerifiedCallersNamespace {
	return &VerifiedCallersNamespace{NewCrudResourcePUT(client, "/api/relay/rest/verified_caller_ids")}
}

func (r *VerifiedCallersNamespace) RedialVerification(id string) (map[string]any, error) {
	return r.HTTP.Post(r.Path(id, "verification"), nil, nil)
}

// VerifiedCallersNamespaceSubmitVerificationParams holds the named optional parameters for VerifiedCallersNamespace.SubmitVerification.
type VerifiedCallersNamespaceSubmitVerificationParams struct {
	VerificationCode any
	Extras           map[string]any
}

func (r *VerifiedCallersNamespace) SubmitVerification(id string, params VerifiedCallersNamespaceSubmitVerificationParams) (map[string]any, error) {
	body := map[string]any{}
	if params.VerificationCode != nil {
		body["verification_code"] = params.VerificationCode
	}
	mergeExtra(body, []map[string]any{params.Extras})
	return r.HTTP.Put(r.Path(id, "verification"), body)
}
