// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "space" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type Space struct {
	Type      string `json:"type,omitempty"`
	ID        string `json:"id,omitempty"`
	Name      string `json:"name,omitempty"`
	Subdomain string `json:"subdomain,omitempty"`
	Verified  bool   `json:"verified,omitempty"`
	Trial     bool   `json:"trial,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}

type SpaceUpdate struct {
	Name *string `json:"name,omitempty"`
}

type GeographicPermission struct {
	Type               string   `json:"type,omitempty"`
	Countries          []string `json:"countries,omitempty"`
	SupportedCountries []string `json:"supported_countries,omitempty"`
}

type GeographicPermissionUpdate struct {
	Countries []string `json:"countries,omitempty"`
}

type BillingProfile struct {
	Type                  string `json:"type,omitempty"`
	AddressLine1          any    `json:"address_line1,omitempty"`
	AddressLine2          any    `json:"address_line2,omitempty"`
	AddressCity           any    `json:"address_city,omitempty"`
	AddressState          any    `json:"address_state,omitempty"`
	AddressZip            any    `json:"address_zip,omitempty"`
	AddressCountry        any    `json:"address_country,omitempty"`
	CompanyName           any    `json:"company_name,omitempty"`
	ContactName           any    `json:"contact_name,omitempty"`
	ContactEmail          any    `json:"contact_email,omitempty"`
	ContactPhone          any    `json:"contact_phone,omitempty"`
	TaxIDNumber           any    `json:"tax_id_number,omitempty"`
	MonthlyInvoices       bool   `json:"monthly_invoices,omitempty"`
	TaxIDNumberRequired   bool   `json:"tax_id_number_required,omitempty"`
	MonthlyInvoicesLocked bool   `json:"monthly_invoices_locked,omitempty"`
}

type BillingProfileUpdate struct {
	AddressLine1    string             `json:"address_line1,omitempty"`
	AddressLine2    *string            `json:"address_line2,omitempty"`
	AddressCity     string             `json:"address_city,omitempty"`
	AddressState    string             `json:"address_state,omitempty"`
	AddressZip      string             `json:"address_zip,omitempty"`
	AddressCountry  AddressCountryCode `json:"address_country,omitempty"`
	CompanyName     string             `json:"company_name,omitempty"`
	ContactName     string             `json:"contact_name,omitempty"`
	ContactEmail    []string           `json:"contact_email,omitempty"`
	ContactPhone    string             `json:"contact_phone,omitempty"`
	TaxIDNumber     *string            `json:"tax_id_number,omitempty"`
	MonthlyInvoices *bool              `json:"monthly_invoices,omitempty"`
}

type BillingStatementPeriod struct {
	Type    string   `json:"type,omitempty"`
	Month   string   `json:"month,omitempty"`
	URI     string   `json:"uri,omitempty"`
	Formats []string `json:"formats,omitempty"`
}

type BillingStatementPeriodList struct {
	Data []BillingStatementPeriod `json:"data,omitempty"`
}

type BillingStatement struct {
	Type        string                  `json:"type,omitempty"`
	Month       string                  `json:"month,omitempty"`
	Summary     BillingStatementSummary `json:"summary,omitempty"`
	UsageByKind []AmountByKind          `json:"usage_by_kind,omitempty"`
	Projects    []ProjectUsage          `json:"projects,omitempty"`
}

type BillingStatementSummary struct {
	UsageInMicrodollars       int            `json:"usage_in_microdollars,omitempty"`
	UsageInDollars            float64        `json:"usage_in_dollars,omitempty"`
	CarrierFeesInMicrodollars int            `json:"carrier_fees_in_microdollars,omitempty"`
	CarrierFeesInDollars      float64        `json:"carrier_fees_in_dollars,omitempty"`
	TaxesInMicrodollars       int            `json:"taxes_in_microdollars,omitempty"`
	TaxesInDollars            float64        `json:"taxes_in_dollars,omitempty"`
	Adjustments               []AmountByKind `json:"adjustments,omitempty"`
}

type AmountByKind struct {
	Kind                 string  `json:"kind,omitempty"`
	Description          string  `json:"description,omitempty"`
	AmountInMicrodollars int     `json:"amount_in_microdollars,omitempty"`
	AmountInDollars      float64 `json:"amount_in_dollars,omitempty"`
}

type ProjectUsage struct {
	ID                   string         `json:"id,omitempty"`
	Name                 any            `json:"name,omitempty"`
	AmountInMicrodollars int            `json:"amount_in_microdollars,omitempty"`
	AmountInDollars      float64        `json:"amount_in_dollars,omitempty"`
	UsageByKind          []AmountByKind `json:"usage_by_kind,omitempty"`
}

type Usage struct {
	Type                string         `json:"type,omitempty"`
	Month               string         `json:"month,omitempty"`
	TotalInMicrodollars int            `json:"total_in_microdollars,omitempty"`
	TotalInDollars      float64        `json:"total_in_dollars,omitempty"`
	UsageByKind         []AmountByKind `json:"usage_by_kind,omitempty"`
	Projects            []ProjectUsage `json:"projects,omitempty"`
}

type BalanceAdjustment struct {
	Type                 string  `json:"type,omitempty"`
	ID                   string  `json:"id,omitempty"`
	Kind                 string  `json:"kind,omitempty"`
	AmountInMicrodollars int     `json:"amount_in_microdollars,omitempty"`
	Amount               float64 `json:"amount,omitempty"`
	CreatedAt            string  `json:"created_at,omitempty"`
	PaymentMethodLast4   any     `json:"payment_method_last4,omitempty"`
}

type PaymentHistoryList struct {
	Links SpacePaginationLinks `json:"links,omitempty"`
	Data  []BalanceAdjustment  `json:"data,omitempty"`
}

type Member struct {
	Type         string `json:"type,omitempty"`
	ID           string `json:"id,omitempty"`
	Email        string `json:"email,omitempty"`
	Name         string `json:"name,omitempty"`
	Role         string `json:"role,omitempty"`
	JobTitle     any    `json:"job_title,omitempty"`
	Activated    bool   `json:"activated,omitempty"`
	LastLoggedIn any    `json:"last_logged_in,omitempty"`
	CreatedAt    string `json:"created_at,omitempty"`
	UpdatedAt    string `json:"updated_at,omitempty"`
}

type MemberList struct {
	Links SpacePaginationLinks `json:"links,omitempty"`
	Data  []Member             `json:"data,omitempty"`
}

type MemberCreate struct {
	Email string  `json:"email,omitempty"`
	Role  string  `json:"role,omitempty"`
	Name  *string `json:"name,omitempty"`
}

type MemberUpdate struct {
	Name     *string `json:"name,omitempty"`
	Role     *string `json:"role,omitempty"`
	JobTitle any     `json:"job_title,omitempty"`
}

type SpaceProject struct {
	Type      string `json:"type,omitempty"`
	ID        string `json:"id,omitempty"`
	Name      string `json:"name,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}

type MemberProject struct {
	Type        string         `json:"type,omitempty"`
	ID          string         `json:"id,omitempty"`
	Name        string         `json:"name,omitempty"`
	CreatedAt   string         `json:"created_at,omitempty"`
	UpdatedAt   string         `json:"updated_at,omitempty"`
	Subprojects []SpaceProject `json:"subprojects,omitempty"`
}

type MemberProjectList struct {
	Links SpacePaginationLinks `json:"links,omitempty"`
	Data  []MemberProject      `json:"data,omitempty"`
}

type Balance struct {
	Type                              string  `json:"type,omitempty"`
	BalanceInMicrodollars             int     `json:"balance_in_microdollars,omitempty"`
	CurrentBalance                    float64 `json:"current_balance,omitempty"`
	LowBalanceThresholdInMicrodollars int     `json:"low_balance_threshold_in_microdollars,omitempty"`
	LowBalanceThreshold               float64 `json:"low_balance_threshold,omitempty"`
	AutoTopupEnabled                  bool    `json:"auto_topup_enabled,omitempty"`
}

type TopUpCreate struct {
	AmountInMicrodollars int    `json:"amount_in_microdollars,omitempty"`
	PaymentMethodID      string `json:"payment_method_id,omitempty"`
}

type LowBalanceSetting struct {
	Type                      string  `json:"type,omitempty"`
	ThresholdInMicrodollars   int     `json:"threshold_in_microdollars,omitempty"`
	Threshold                 float64 `json:"threshold,omitempty"`
	SendEmail                 bool    `json:"send_email,omitempty"`
	SendWebhook               bool    `json:"send_webhook,omitempty"`
	WebhookURL                any     `json:"webhook_url,omitempty"`
	WebhookMethod             any     `json:"webhook_method,omitempty"`
	SendTopup                 bool    `json:"send_topup,omitempty"`
	TopupAmountInMicrodollars any     `json:"topup_amount_in_microdollars,omitempty"`
	TopupAmount               any     `json:"topup_amount,omitempty"`
	TopupPaymentMethodID      any     `json:"topup_payment_method_id,omitempty"`
}

type LowBalanceSettingUpdate struct {
	ThresholdInMicrodollars   *int    `json:"threshold_in_microdollars,omitempty"`
	SendEmail                 *bool   `json:"send_email,omitempty"`
	SendWebhook               *bool   `json:"send_webhook,omitempty"`
	WebhookURL                *string `json:"webhook_url,omitempty"`
	WebhookMethod             *string `json:"webhook_method,omitempty"`
	SendTopup                 *bool   `json:"send_topup,omitempty"`
	TopupAmountInMicrodollars *int    `json:"topup_amount_in_microdollars,omitempty"`
	TopupPaymentMethodID      *string `json:"topup_payment_method_id,omitempty"`
}

type PaymentMethod struct {
	Type            string `json:"type,omitempty"`
	ID              string `json:"id,omitempty"`
	Brand           any    `json:"brand,omitempty"`
	Last4           any    `json:"last4,omitempty"`
	ExpiresMonth    any    `json:"expires_month,omitempty"`
	ExpiresYear     any    `json:"expires_year,omitempty"`
	Country         any    `json:"country,omitempty"`
	AutoTopupSource bool   `json:"auto_topup_source,omitempty"`
}

type SpacePaginationLinks struct {
	Self  string  `json:"self,omitempty"`
	First string  `json:"first,omitempty"`
	Next  *string `json:"next,omitempty"`
	Prev  *string `json:"prev,omitempty"`
}

type SpaceStatusCode422 struct {
	Errors []SpaceTypes_StatusCodes_RestApiErrorItem `json:"errors,omitempty"`
}

type SpaceTypes_StatusCodes_RestApiErrorItem struct {
	Type      string `json:"type,omitempty"`
	Code      string `json:"code,omitempty"`
	Message   string `json:"message,omitempty"`
	Attribute any    `json:"attribute,omitempty"`
	URL       string `json:"url,omitempty"`
}

type SpaceUnverifiedError struct {
	Message string `json:"message,omitempty"`
}

type TopUpMessageError struct {
	Message string `json:"message,omitempty"`
}

type TopUpDeclinedError struct {
	Message     any    `json:"message,omitempty"`
	DeclineCode string `json:"decline_code,omitempty"`
}

type TopUpDepositFailedError struct {
	Message string `json:"message,omitempty"`
	Code    string `json:"code,omitempty"`
}
