// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "swml-webhooks" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type SwmlRequestData struct {
	Call   *SwmlRequestCall `json:"call,omitempty"`
	Vars   map[string]any   `json:"vars,omitempty"`
	Envs   map[string]any   `json:"envs,omitempty"`
	Params map[string]any   `json:"params,omitempty"`
}

type SwmlRequestCall any

type SwmlRequestCallParent struct {
	DeviceType *string `json:"device_type,omitempty"`
	CallID     string  `json:"call_id,omitempty"`
	NodeID     string  `json:"node_id,omitempty"`
}

type SwmlRequestCallPeer struct {
	CallID string `json:"call_id,omitempty"`
	NodeID string `json:"node_id,omitempty"`
}

type SwmlRequestCallPhone struct {
	ProjectID      *string                           `json:"project_id,omitempty"`
	SpaceID        *string                           `json:"space_id,omitempty"`
	CallID         string                            `json:"call_id,omitempty"`
	NodeID         string                            `json:"node_id,omitempty"`
	SegmentID      *string                           `json:"segment_id,omitempty"`
	Tag            *string                           `json:"tag,omitempty"`
	CallState      string                            `json:"call_state,omitempty"`
	Parent         *SwmlRequestCallParent            `json:"parent,omitempty"`
	Peer           *SwmlRequestCallPeer              `json:"peer,omitempty"`
	Direction      string                            `json:"direction,omitempty"`
	EndReason      *string                           `json:"end_reason,omitempty"`
	EndSource      *string                           `json:"end_source,omitempty"`
	DialWinner     *string                           `json:"dial_winner,omitempty"`
	AddressID      *string                           `json:"address_id,omitempty"`
	SubscriberID   *string                           `json:"subscriber_id,omitempty"`
	SubscriberName *string                           `json:"subscriber_name,omitempty"`
	Type           string                            `json:"type,omitempty"`
	From           string                            `json:"from,omitempty"`
	To             string                            `json:"to,omitempty"`
	FromNumber     string                            `json:"from_number,omitempty"`
	ToNumber       string                            `json:"to_number,omitempty"`
	Headers        []SwmlRequestCallPhoneHeadersItem `json:"headers,omitempty"`
}

type SwmlRequestCallPhoneHeadersItem struct {
	Name  string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}

type SwmlRequestCallSip struct {
	ProjectID      *string                         `json:"project_id,omitempty"`
	SpaceID        *string                         `json:"space_id,omitempty"`
	CallID         string                          `json:"call_id,omitempty"`
	NodeID         string                          `json:"node_id,omitempty"`
	SegmentID      *string                         `json:"segment_id,omitempty"`
	Tag            *string                         `json:"tag,omitempty"`
	CallState      string                          `json:"call_state,omitempty"`
	Parent         *SwmlRequestCallParent          `json:"parent,omitempty"`
	Peer           *SwmlRequestCallPeer            `json:"peer,omitempty"`
	Direction      string                          `json:"direction,omitempty"`
	EndReason      *string                         `json:"end_reason,omitempty"`
	EndSource      *string                         `json:"end_source,omitempty"`
	DialWinner     *string                         `json:"dial_winner,omitempty"`
	AddressID      *string                         `json:"address_id,omitempty"`
	SubscriberID   *string                         `json:"subscriber_id,omitempty"`
	SubscriberName *string                         `json:"subscriber_name,omitempty"`
	Type           string                          `json:"type,omitempty"`
	From           string                          `json:"from,omitempty"`
	To             string                          `json:"to,omitempty"`
	Headers        []SwmlRequestCallSipHeadersItem `json:"headers,omitempty"`
	SIPData        *SwmlRequestCallSipSipData      `json:"sip_data,omitempty"`
}

type SwmlRequestCallSipHeadersItem struct {
	Name  string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}

type SwmlRequestCallSipSipData struct {
	SIPReqUser           *string        `json:"sip_req_user,omitempty"`
	SIPReqURI            *string        `json:"sip_req_uri,omitempty"`
	SIPReqHost           *string        `json:"sip_req_host,omitempty"`
	SIPFromUser          *string        `json:"sip_from_user,omitempty"`
	SIPFromURI           *string        `json:"sip_from_uri,omitempty"`
	SIPFromHost          *string        `json:"sip_from_host,omitempty"`
	SIPToUser            *string        `json:"sip_to_user,omitempty"`
	SIPToURI             *string        `json:"sip_to_uri,omitempty"`
	SIPToHost            *string        `json:"sip_to_host,omitempty"`
	SIPContactUser       *string        `json:"sip_contact_user,omitempty"`
	SIPContactPort       *string        `json:"sip_contact_port,omitempty"`
	SIPContactURI        *string        `json:"sip_contact_uri,omitempty"`
	SIPContactHost       *string        `json:"sip_contact_host,omitempty"`
	SIPFromParams        map[string]any `json:"sip_from_params,omitempty"`
	SIPToParams          map[string]any `json:"sip_to_params,omitempty"`
	SIPContactParams     map[string]any `json:"sip_contact_params,omitempty"`
	SIPReqParams         map[string]any `json:"sip_req_params,omitempty"`
	SIPPAssertedIdentity *string        `json:"sip_p_asserted_identity,omitempty"`
}

type SwmlRequestCallWebrtc struct {
	ProjectID      *string                `json:"project_id,omitempty"`
	SpaceID        *string                `json:"space_id,omitempty"`
	CallID         string                 `json:"call_id,omitempty"`
	NodeID         string                 `json:"node_id,omitempty"`
	SegmentID      *string                `json:"segment_id,omitempty"`
	Tag            *string                `json:"tag,omitempty"`
	CallState      string                 `json:"call_state,omitempty"`
	Parent         *SwmlRequestCallParent `json:"parent,omitempty"`
	Peer           *SwmlRequestCallPeer   `json:"peer,omitempty"`
	Direction      string                 `json:"direction,omitempty"`
	EndReason      *string                `json:"end_reason,omitempty"`
	EndSource      *string                `json:"end_source,omitempty"`
	DialWinner     *string                `json:"dial_winner,omitempty"`
	AddressID      *string                `json:"address_id,omitempty"`
	SubscriberID   *string                `json:"subscriber_id,omitempty"`
	SubscriberName *string                `json:"subscriber_name,omitempty"`
	Type           string                 `json:"type,omitempty"`
	From           string                 `json:"from,omitempty"`
	To             string                 `json:"to,omitempty"`
}

type SwmlRequestCallOther struct {
	ProjectID      *string                `json:"project_id,omitempty"`
	SpaceID        *string                `json:"space_id,omitempty"`
	CallID         string                 `json:"call_id,omitempty"`
	NodeID         string                 `json:"node_id,omitempty"`
	SegmentID      *string                `json:"segment_id,omitempty"`
	Tag            *string                `json:"tag,omitempty"`
	CallState      string                 `json:"call_state,omitempty"`
	Parent         *SwmlRequestCallParent `json:"parent,omitempty"`
	Peer           *SwmlRequestCallPeer   `json:"peer,omitempty"`
	Direction      string                 `json:"direction,omitempty"`
	EndReason      *string                `json:"end_reason,omitempty"`
	EndSource      *string                `json:"end_source,omitempty"`
	DialWinner     *string                `json:"dial_winner,omitempty"`
	AddressID      *string                `json:"address_id,omitempty"`
	SubscriberID   *string                `json:"subscriber_id,omitempty"`
	SubscriberName *string                `json:"subscriber_name,omitempty"`
}
