// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST wire types for the "swml-webhooks" namespace spec — one Go type per
// components/schemas entry (structs for objects, defined-string types for enums,
// alias types for scalars/arrays/unions). Fields carry json wire-key tags so a
// typed struct marshals to the same snake body the loose map form produced.
//
// Types whose Go name was already declared by an earlier spec (shared SWML-schema
// types, shared error types) are omitted here — the whole REST types surface lives
// in ONE Go package, so each unique type name is declared once (see
// emittedTypeNames in cmd/generate-rest/types.go).

package namespaces

type SwaigRequestData struct {
	CallID         string         `json:"call_id,omitempty"`
	AiSessionID    string         `json:"ai_session_id,omitempty"`
	AppName        *string        `json:"app_name,omitempty"`
	ProjectID      string         `json:"project_id,omitempty"`
	SpaceID        string         `json:"space_id,omitempty"`
	Action         string         `json:"action,omitempty"`
	Function       string         `json:"function,omitempty"`
	Argument       SwaigArgument  `json:"argument,omitempty"`
	MetaData       map[string]any `json:"meta_data,omitempty"`
	ConversationID *string        `json:"conversation_id,omitempty"`
	ContentType    *string        `json:"content_type,omitempty"`
	Version        *string        `json:"version,omitempty"`
}

type SwaigArgument struct {
	Parsed      []map[string]any `json:"parsed,omitempty"`
	Raw         string           `json:"raw,omitempty"`
	Substituted string           `json:"substituted,omitempty"`
}

type PostPromptData struct {
	EventType    *string          `json:"event_type,omitempty"`
	EventChannel *string          `json:"event_channel,omitempty"`
	Timestamp    *float64         `json:"timestamp,omitempty"`
	ProjectID    *string          `json:"project_id,omitempty"`
	SpaceID      *string          `json:"space_id,omitempty"`
	Params       PostPromptParams `json:"params,omitempty"`
}

type PostPromptParams struct {
	CallID           string                       `json:"call_id,omitempty"`
	AiSessionID      string                       `json:"ai_session_id,omitempty"`
	Summary          *string                      `json:"summary,omitempty"`
	PostPromptResult any                          `json:"post_prompt_result,omitempty"`
	EndReason        *string                      `json:"end_reason,omitempty"`
	Conversation     []PostPromptConversationTurn `json:"conversation,omitempty"`
	FunctionCalls    []PostPromptFunctionCall     `json:"function_calls,omitempty"`
}

type PostPromptConversationTurn struct {
	Role    string `json:"role,omitempty"`
	Content string `json:"content,omitempty"`
}

type PostPromptFunctionCall struct {
	Function string         `json:"function,omitempty"`
	Params   map[string]any `json:"params,omitempty"`
	Result   map[string]any `json:"result,omitempty"`
}

type SwmlRequestData struct {
	Call   *SwmlRequestCall `json:"call,omitempty"`
	Vars   map[string]any   `json:"vars,omitempty"`
	Envs   map[string]any   `json:"envs,omitempty"`
	Params map[string]any   `json:"params,omitempty"`
}

type SwmlRequestCall struct {
	CallID     string           `json:"call_id,omitempty"`
	NodeID     *string          `json:"node_id,omitempty"`
	SegmentID  *string          `json:"segment_id,omitempty"`
	ProjectID  string           `json:"project_id,omitempty"`
	SpaceID    string           `json:"space_id,omitempty"`
	CallState  *string          `json:"call_state,omitempty"`
	Direction  *string          `json:"direction,omitempty"`
	Type       *string          `json:"type,omitempty"`
	From       *string          `json:"from,omitempty"`
	To         *string          `json:"to,omitempty"`
	FromNumber *string          `json:"from_number,omitempty"`
	ToNumber   *string          `json:"to_number,omitempty"`
	Headers    []map[string]any `json:"headers,omitempty"`
}

type SignalWireErrorBody struct {
	Code     int     `json:"code,omitempty"`
	Message  string  `json:"message,omitempty"`
	MoreInfo *string `json:"more_info,omitempty"`
	Status   *int    `json:"status,omitempty"`
}
