// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "video" namespace spec.

package namespaces

// VideoConferenceTokens is generated from x-sdk-resource "VideoConferenceTokens" in the video spec.
type VideoConferenceTokens struct {
	Resource
}

// NewVideoConferenceTokens constructs a VideoConferenceTokens bound to base path "/api/video/conference_tokens".
func NewVideoConferenceTokens(client HTTPClient) *VideoConferenceTokens {
	return &VideoConferenceTokens{Resource{HTTP: client, Base: "/api/video/conference_tokens"}}
}

func (r *VideoConferenceTokens) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *VideoConferenceTokens) Reset(id string) (map[string]any, error) {
	return r.HTTP.Post(r.Path(id, "reset"), nil, nil)
}

// VideoConferences is generated from x-sdk-resource "VideoConferences" in the video spec.
type VideoConferences struct {
	*CrudResource
}

// NewVideoConferences constructs a VideoConferences bound to base path "/api/video/conferences".
func NewVideoConferences(client HTTPClient) *VideoConferences {
	return &VideoConferences{NewCrudResourcePUT(client, "/api/video/conferences")}
}

func (r *VideoConferences) ListConferenceTokens(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "conference_tokens"), params)
}

func (r *VideoConferences) ListStreams(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "streams"), params)
}

func (r *VideoConferences) CreateStream(id string, url any, extras map[string]any) (map[string]any, error) {
	body := map[string]any{}
	if url != nil {
		body["url"] = url
	}
	mergeExtra(body, []map[string]any{extras})
	return r.HTTP.Post(r.Path(id, "streams"), body, nil)
}

// VideoRoomRecordings is generated from x-sdk-resource "VideoRoomRecordings" in the video spec.
type VideoRoomRecordings struct {
	Resource
}

// NewVideoRoomRecordings constructs a VideoRoomRecordings bound to base path "/api/video/room_recordings".
func NewVideoRoomRecordings(client HTTPClient) *VideoRoomRecordings {
	return &VideoRoomRecordings{Resource{HTTP: client, Base: "/api/video/room_recordings"}}
}

func (r *VideoRoomRecordings) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *VideoRoomRecordings) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *VideoRoomRecordings) Delete(id string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(id))
}

func (r *VideoRoomRecordings) ListEvents(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "events"), params)
}

// VideoRoomSessions is generated from x-sdk-resource "VideoRoomSessions" in the video spec.
type VideoRoomSessions struct {
	Resource
}

// NewVideoRoomSessions constructs a VideoRoomSessions bound to base path "/api/video/room_sessions".
func NewVideoRoomSessions(client HTTPClient) *VideoRoomSessions {
	return &VideoRoomSessions{Resource{HTTP: client, Base: "/api/video/room_sessions"}}
}

func (r *VideoRoomSessions) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *VideoRoomSessions) Get(id string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), nil)
}

func (r *VideoRoomSessions) ListEvents(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "events"), params)
}

func (r *VideoRoomSessions) ListMembers(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "members"), params)
}

func (r *VideoRoomSessions) ListRecordings(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "recordings"), params)
}

// VideoRoomTokens is generated from x-sdk-resource "VideoRoomTokens" in the video spec.
type VideoRoomTokens struct {
	Resource
}

// NewVideoRoomTokens constructs a VideoRoomTokens bound to base path "/api/video/room_tokens".
func NewVideoRoomTokens(client HTTPClient) *VideoRoomTokens {
	return &VideoRoomTokens{Resource{HTTP: client, Base: "/api/video/room_tokens"}}
}

func (r *VideoRoomTokens) Create(roomName any, userName any, permissions any, joinFrom any, joinUntil any, removeAt any, removeAfterSecondsElapsed any, joinAudioMuted any, joinVideoMuted any, autoCreateRoom any, enableRoomPreviews any, roomDisplayName any, endRoomSessionOnLeave any, joinAs any, mediaAllowed any, roomMeta any, meta any, syncAudioVideo any, extras map[string]any) (map[string]any, error) {
	body := map[string]any{}
	if roomName != nil {
		body["room_name"] = roomName
	}
	if userName != nil {
		body["user_name"] = userName
	}
	if permissions != nil {
		body["permissions"] = permissions
	}
	if joinFrom != nil {
		body["join_from"] = joinFrom
	}
	if joinUntil != nil {
		body["join_until"] = joinUntil
	}
	if removeAt != nil {
		body["remove_at"] = removeAt
	}
	if removeAfterSecondsElapsed != nil {
		body["remove_after_seconds_elapsed"] = removeAfterSecondsElapsed
	}
	if joinAudioMuted != nil {
		body["join_audio_muted"] = joinAudioMuted
	}
	if joinVideoMuted != nil {
		body["join_video_muted"] = joinVideoMuted
	}
	if autoCreateRoom != nil {
		body["auto_create_room"] = autoCreateRoom
	}
	if enableRoomPreviews != nil {
		body["enable_room_previews"] = enableRoomPreviews
	}
	if roomDisplayName != nil {
		body["room_display_name"] = roomDisplayName
	}
	if endRoomSessionOnLeave != nil {
		body["end_room_session_on_leave"] = endRoomSessionOnLeave
	}
	if joinAs != nil {
		body["join_as"] = joinAs
	}
	if mediaAllowed != nil {
		body["media_allowed"] = mediaAllowed
	}
	if roomMeta != nil {
		body["room_meta"] = roomMeta
	}
	if meta != nil {
		body["meta"] = meta
	}
	if syncAudioVideo != nil {
		body["sync_audio_video"] = syncAudioVideo
	}
	mergeExtra(body, []map[string]any{extras})
	return r.HTTP.Post(r.Base, body, nil)
}

// VideoRooms is generated from x-sdk-resource "VideoRooms" in the video spec.
type VideoRooms struct {
	*CrudResource
}

// NewVideoRooms constructs a VideoRooms bound to base path "/api/video/rooms".
func NewVideoRooms(client HTTPClient) *VideoRooms {
	return &VideoRooms{NewCrudResourcePUT(client, "/api/video/rooms")}
}

func (r *VideoRooms) ListStreams(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id, "streams"), params)
}

func (r *VideoRooms) CreateStream(id string, url any, extras map[string]any) (map[string]any, error) {
	body := map[string]any{}
	if url != nil {
		body["url"] = url
	}
	mergeExtra(body, []map[string]any{extras})
	return r.HTTP.Post(r.Path(id, "streams"), body, nil)
}

// VideoStreams is generated from x-sdk-resource "VideoStreams" in the video spec.
type VideoStreams struct {
	Resource
}

// NewVideoStreams constructs a VideoStreams bound to base path "/api/video/streams".
func NewVideoStreams(client HTTPClient) *VideoStreams {
	return &VideoStreams{Resource{HTTP: client, Base: "/api/video/streams"}}
}

func (r *VideoStreams) Get(id string, params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), params)
}

func (r *VideoStreams) Update(id string, url any, extras map[string]any) (map[string]any, error) {
	body := map[string]any{}
	if url != nil {
		body["url"] = url
	}
	mergeExtra(body, []map[string]any{extras})
	return r.HTTP.Put(r.Path(id), body)
}

func (r *VideoStreams) Delete(id string) (map[string]any, error) {
	return r.HTTP.Delete(r.Path(id))
}
