// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "voice" namespace spec.

package namespaces

// VoiceLogs is generated from x-sdk-resource "VoiceLogs" in the voice spec.
type VoiceLogs struct {
	Resource
}

// NewVoiceLogs constructs a VoiceLogs bound to base path "/api/voice/logs".
func NewVoiceLogs(client HTTPClient) *VoiceLogs {
	return &VoiceLogs{Resource{HTTP: client, Base: "/api/voice/logs"}}
}

func (r *VoiceLogs) List(params map[string]string) (map[string]any, error) {
	return r.HTTP.Get(r.Base, params)
}

func (r *VoiceLogs) Get(id string) (map[string]any, error) {
	return r.HTTP.Get(r.Path(id), nil)
}

func (r *VoiceLogs) ListEvents(id string, params map[string]string) (*LogEventsListResponse, error) {
	return decodeResult[LogEventsListResponse](r.HTTP.Get(r.Path(id, "events"), params))
}
