// Code generated by cmd/generate-rest-tests; DO NOT EDIT.
//
// AUTO-GENERATED full-mock REST wire tests for the "voice" namespace — regenerate:
//   go run ./cmd/generate-rest-tests
//
// Each route the SDK implements (captured from the real client by
// cmd/route-registry, joined to the spec operationId) gets a SUCCESS test (call
// it, assert method + matched_route on the mock journal) and an ERROR test (arm a
// 500, assert *rest.SignalWireRestError with StatusCode 500). The assertion
// oracle is the spec operationId — independent of the resource generator — so
// these catch SDK-vs-contract drift, not a generator self-snapshot.

package namespaces_test

import (
	"context"
	"errors"
	"testing"

	"github.com/signalwire/signalwire-go/pkg/rest"
	"github.com/signalwire/signalwire-go/pkg/rest/internal/mocktest"
)

func TestVoiceGen_Voice_Get(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Logs.Voice.Get(context.Background(), "x-1")
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "GET" {
		t.Errorf("method = %q want GET", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "voice.get_voice_log" {
		t.Errorf("matched_route = %v want voice.get_voice_log", j.MatchedRoute)
	}
}

func TestVoiceGen_Voice_Get_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "voice.get_voice_log", 500, map[string]any{"error": "x"})
	_, err := client.Logs.Voice.Get(context.Background(), "x-1")
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestVoiceGen_Voice_ListEvents(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Logs.Voice.ListEvents(context.Background(), "x-1", nil)
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "GET" {
		t.Errorf("method = %q want GET", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "voice.list_voice_log_events" {
		t.Errorf("matched_route = %v want voice.list_voice_log_events", j.MatchedRoute)
	}
}

func TestVoiceGen_Voice_ListEvents_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "voice.list_voice_log_events", 500, map[string]any{"error": "x"})
	_, err := client.Logs.Voice.ListEvents(context.Background(), "x-1", nil)
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}

func TestVoiceGen_Voice_List(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	_, err := client.Logs.Voice.List(context.Background(), nil)
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	j := mock.Last(t)
	if j.Method != "GET" {
		t.Errorf("method = %q want GET", j.Method)
	}
	if j.MatchedRoute == nil || *j.MatchedRoute != "voice.list_voice_logs" {
		t.Errorf("matched_route = %v want voice.list_voice_logs", j.MatchedRoute)
	}
}

func TestVoiceGen_Voice_List_Error(t *testing.T) {
	t.Parallel()
	client, mock := mocktest.New(t)
	if client == nil {
		return
	}
	mock.Reset(t)
	mock.PushScenario(t, "voice.list_voice_logs", 500, map[string]any{"error": "x"})
	_, err := client.Logs.Voice.List(context.Background(), nil)
	var restErr *rest.SignalWireRestError
	if !errors.As(err, &restErr) {
		t.Fatalf("want *SignalWireRestError, got %v", err)
	}
	if restErr.StatusCode != 500 {
		t.Errorf("status = %d want 500", restErr.StatusCode)
	}
}
