// Code generated by cmd/generate-rest; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/rest-apis/ (x-sdk-* markup) — regenerate with:
//   go run ./cmd/generate-rest
//
// Generated REST resources for the "voice" namespace spec.

package namespaces

import "context"

// VoiceLogs is a client for the "VoiceLogs" resource of the SignalWire voice API.
type VoiceLogs struct {
	Resource
}

// NewVoiceLogs constructs a VoiceLogs bound to base path "/api/voice/logs".
func NewVoiceLogs(client HTTPClient) *VoiceLogs {
	return &VoiceLogs{Resource{HTTP: client, Base: "/api/voice/logs"}}
}

func (r *VoiceLogs) List(ctx context.Context, params map[string]string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Get(ctx, r.Base, params, opts...)
}

func (r *VoiceLogs) Get(ctx context.Context, id string, opts ...*RequestOptions) (map[string]any, error) {
	return r.HTTP.Get(ctx, r.Path(id), nil, opts...)
}

func (r *VoiceLogs) Paginate(ctx context.Context, params map[string]string, opts ...*RequestOptions) *Paginator {
	return NewPaginator(ctx, r.HTTP, r.Base, params, "data", opts...)
}

func (r *VoiceLogs) ListEvents(ctx context.Context, id string, params map[string]string, opts ...*RequestOptions) (*LogEventsListResponse, error) {
	return decodeResult[LogEventsListResponse](r.HTTP.Get(ctx, r.Path(id, "events"), params, opts...))
}
