// Code generated by cmd/generate-payloads; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/swaig-specs/post-prompt.yaml — regenerate with:
//   go run ./cmd/generate-payloads
//
// The post-prompt callback payload — the call summary + enriched call log the
// agent's post-prompt / onSummary handler RECEIVES. Open shape; extra keys tolerated.

package swaig

// PostPrompt Built by ais_get_post_data (ai_utils.c) + openai_post_process (post_process.c). No `version` field. Open shape: conditional fields appear only when their precondition holds.
type PostPrompt struct {
	ContentType                    string                     `json:"content_type,omitempty" gen:"string"`
	ContentDisposition             string                     `json:"content_disposition,omitempty" gen:"string"`
	ConversationType               string                     `json:"conversation_type,omitempty" gen:"string"`
	Action                         string                     `json:"action,omitempty" gen:"string"`
	ProjectId                      string                     `json:"project_id,omitempty" gen:"string"`
	SpaceId                        string                     `json:"space_id,omitempty" gen:"string"`
	CallId                         string                     `json:"call_id,omitempty" gen:"string"`
	AppName                        string                     `json:"app_name,omitempty" gen:"string"`
	AiSessionId                    string                     `json:"ai_session_id,omitempty" gen:"string"`
	AiIdTag                        string                     `json:"ai_id_tag,omitempty" gen:"string"`
	ConversationId                 string                     `json:"conversation_id,omitempty" gen:"string"`
	CallEndedBy                    string                     `json:"call_ended_by,omitempty" gen:"string"`
	CallerIdName                   string                     `json:"caller_id_name,omitempty" gen:"string"`
	CallerIdNumber                 string                     `json:"caller_id_number,omitempty" gen:"string"`
	ConversationSummary            string                     `json:"conversation_summary,omitempty" gen:"string"`
	HardTimeout                    bool                       `json:"hard_timeout,omitempty" gen:"bool"`
	CallStartDate                  int                        `json:"call_start_date,omitempty" gen:"int"`
	CallAnswerDate                 int                        `json:"call_answer_date,omitempty" gen:"int"`
	CallEndDate                    int                        `json:"call_end_date,omitempty" gen:"int"`
	AiStartDate                    int                        `json:"ai_start_date,omitempty" gen:"int"`
	AiEndDate                      int                        `json:"ai_end_date,omitempty" gen:"int"`
	PostPromptData                 *PostPromptData            `json:"post_prompt_data,omitempty" gen:"class:signalwire.core.post_prompt_generated.PostPromptData"`
	GlobalData                     map[string]any             `json:"global_data,omitempty" gen:"dict<string,any>"`
	SWMLVars                       map[string]any             `json:"SWMLVars,omitempty" gen:"dict<string,any>"`
	SWMLCall                       map[string]any             `json:"SWMLCall,omitempty" gen:"dict<string,any>"`
	CallLog                        []*PostPromptCallLogEntry  `json:"call_log,omitempty" gen:"list<class:signalwire.core.post_prompt_generated.PostPromptCallLogEntry>"`
	RawCallLog                     []*PostPromptCallLogEntry  `json:"raw_call_log,omitempty" gen:"list<class:signalwire.core.post_prompt_generated.PostPromptCallLogEntry>"`
	CallTimeline                   []map[string]any           `json:"call_timeline,omitempty" gen:"list<dict<string,any>>"`
	PreviousContexts               [][]map[string]any         `json:"previous_contexts,omitempty" gen:"list<list<dict<string,any>>>"`
	Times                          []*PostPromptTimesEntry    `json:"times,omitempty" gen:"list<class:signalwire.core.post_prompt_generated.PostPromptTimesEntry>"`
	SwaigLog                       []*PostPromptSwaigLogEntry `json:"swaig_log,omitempty" gen:"list<class:signalwire.core.post_prompt_generated.PostPromptSwaigLogEntry>"`
	TotalMinutes                   float64                    `json:"total_minutes,omitempty" gen:"float"`
	TotalInputTokens               float64                    `json:"total_input_tokens,omitempty" gen:"float"`
	TotalOutputTokens              float64                    `json:"total_output_tokens,omitempty" gen:"float"`
	TotalWireInputTokens           float64                    `json:"total_wire_input_tokens,omitempty" gen:"float"`
	TotalWireInputTokensPerMinute  float64                    `json:"total_wire_input_tokens_per_minute,omitempty" gen:"float"`
	TotalWireOutputTokens          float64                    `json:"total_wire_output_tokens,omitempty" gen:"float"`
	TotalWireOutputTokensPerMinute float64                    `json:"total_wire_output_tokens_per_minute,omitempty" gen:"float"`
	TotalTtsChars                  float64                    `json:"total_tts_chars,omitempty" gen:"float"`
	TotalTtsCharsPerMin            float64                    `json:"total_tts_chars_per_min,omitempty" gen:"float"`
	TotalAsrMinutes                float64                    `json:"total_asr_minutes,omitempty" gen:"float"`
	TotalAsrCostFactor             float64                    `json:"total_asr_cost_factor,omitempty" gen:"float"`
}

type PostPromptData struct {
	Parsed      []map[string]any `json:"parsed,omitempty" gen:"list<dict<string,any>>"`
	Raw         string           `json:"raw,omitempty" gen:"string"`
	Substituted string           `json:"substituted,omitempty" gen:"string"`
}

// PostPromptCallLogEntry A conversation-log entry, discriminated by `role`. raw_call_log shares this shape (plus raw-only barge fields on assistant entries).
type PostPromptCallLogEntry any

type PostPromptUserEntry struct {
	Role                      string            `json:"role,omitempty" gen:"string"`
	Content                   string            `json:"content,omitempty" gen:"string"`
	Timestamp                 int               `json:"timestamp,omitempty" gen:"int"`
	Confidence                float64           `json:"confidence,omitempty" gen:"float"`
	ContentType               string            `json:"content_type,omitempty" gen:"string"`
	Speaker                   string            `json:"speaker,omitempty" gen:"string"`
	StartTimestamp            int               `json:"start_timestamp,omitempty" gen:"int"`
	EndTimestamp              int               `json:"end_timestamp,omitempty" gen:"int"`
	SpeakingToFinalEvent      float64           `json:"speaking_to_final_event,omitempty" gen:"float"`
	SpeakingToTurnDetection   float64           `json:"speaking_to_turn_detection,omitempty" gen:"float"`
	TurnDetectionToFinalEvent float64           `json:"turn_detection_to_final_event,omitempty" gen:"float"`
	BargeCount                int               `json:"barge_count,omitempty" gen:"int"`
	Merged                    bool              `json:"merged,omitempty" gen:"bool"`
	MergeCount                int               `json:"merge_count,omitempty" gen:"int"`
	Entity                    *PostPromptEntity `json:"entity,omitempty" gen:"class:signalwire.core.post_prompt_generated.PostPromptEntity"`
	Eot                       *PostPromptEot    `json:"eot,omitempty" gen:"class:signalwire.core.post_prompt_generated.PostPromptEot"`
	Timing                    *PostPromptTiming `json:"timing,omitempty" gen:"class:signalwire.core.post_prompt_generated.PostPromptTiming"`
}

type PostPromptAssistantEntry struct {
	Role               string              `json:"role,omitempty" gen:"string"`
	Content            string              `json:"content,omitempty" gen:"string"`
	Timestamp          int                 `json:"timestamp,omitempty" gen:"int"`
	ToolCalls          []map[string]any    `json:"tool_calls,omitempty" gen:"list<dict<string,any>>"`
	Latency            float64             `json:"latency,omitempty" gen:"float"`
	UtteranceLatency   float64             `json:"utterance_latency,omitempty" gen:"float"`
	AudioLatency       float64             `json:"audio_latency,omitempty" gen:"float"`
	AcousticLatency    any                 `json:"acoustic_latency,omitempty" gen:"optional<float>"`
	EosToPushLatency   any                 `json:"eos_to_push_latency,omitempty" gen:"optional<float>"`
	DgDecisionLatency  any                 `json:"dg_decision_latency,omitempty" gen:"optional<float>"`
	Poll               any                 `json:"poll,omitempty" gen:"optional<float>"`
	SpeechStartWallUs  int                 `json:"speech_start_wall_us,omitempty" gen:"int"`
	LastWordEndWallUs  int                 `json:"last_word_end_wall_us,omitempty" gen:"int"`
	TurnDecidedWallUs  int                 `json:"turn_decided_wall_us,omitempty" gen:"int"`
	StatusPushedWallUs int                 `json:"status_pushed_wall_us,omitempty" gen:"int"`
	StampsUs           *PostPromptStampsUs `json:"stamps_us,omitempty" gen:"class:signalwire.core.post_prompt_generated.PostPromptStampsUs"`
	Barged             bool                `json:"barged,omitempty" gen:"bool"`
	BargeElapsedMs     float64             `json:"barge_elapsed_ms,omitempty" gen:"float"`
	TextHeardApprox    string              `json:"text_heard_approx,omitempty" gen:"string"`
	TextSpokenTotal    string              `json:"text_spoken_total,omitempty" gen:"string"`
}

type PostPromptThinkingEntry struct {
	Role      string `json:"role,omitempty" gen:"string"`
	Content   string `json:"content,omitempty" gen:"string"`
	Timestamp int    `json:"timestamp,omitempty" gen:"int"`
	Lang      string `json:"lang,omitempty" gen:"string"`
	Tokens    int    `json:"tokens,omitempty" gen:"int"`
}

type PostPromptToolEntry struct {
	Role               string  `json:"role,omitempty" gen:"string"`
	ToolCallId         string  `json:"tool_call_id,omitempty" gen:"string"`
	Content            string  `json:"content,omitempty" gen:"string"`
	Timestamp          int     `json:"timestamp,omitempty" gen:"int"`
	FunctionName       string  `json:"function_name,omitempty" gen:"string"`
	Latency            float64 `json:"latency,omitempty" gen:"float"`
	UtteranceLatency   float64 `json:"utterance_latency,omitempty" gen:"float"`
	FunctionLatency    float64 `json:"function_latency,omitempty" gen:"float"`
	AudioLatency       float64 `json:"audio_latency,omitempty" gen:"float"`
	ExecutionLatency   float64 `json:"execution_latency,omitempty" gen:"float"`
	DeprecationWarning string  `json:"deprecation_warning,omitempty" gen:"string"`
	StartTimestamp     int     `json:"start_timestamp,omitempty" gen:"int"`
	EndTimestamp       int     `json:"end_timestamp,omitempty" gen:"int"`
	Distilled          bool    `json:"distilled,omitempty" gen:"bool"`
	OriginalResult     string  `json:"original_result,omitempty" gen:"string"`
}

type PostPromptSystemLogEntry struct {
	Role        string         `json:"role,omitempty" gen:"string"`
	Content     string         `json:"content,omitempty" gen:"string"`
	Timestamp   int            `json:"timestamp,omitempty" gen:"int"`
	Action      string         `json:"action,omitempty" gen:"string"`
	Lang        string         `json:"lang,omitempty" gen:"string"`
	Tokens      int            `json:"tokens,omitempty" gen:"int"`
	ContentType string         `json:"content_type,omitempty" gen:"string"`
	Metadata    map[string]any `json:"metadata,omitempty" gen:"dict<string,any>"`
	Context     string         `json:"context,omitempty" gen:"string"`
	Step        string         `json:"step,omitempty" gen:"string"`
	StepIndex   int            `json:"step_index,omitempty" gen:"int"`
}

type PostPromptSystemEntry struct {
	Role      string `json:"role,omitempty" gen:"string"`
	Content   string `json:"content,omitempty" gen:"string"`
	Timestamp int    `json:"timestamp,omitempty" gen:"int"`
}

type PostPromptSwaigLogEntry struct {
	CommandName         string         `json:"command_name,omitempty" gen:"string"`
	CommandArg          string         `json:"command_arg,omitempty" gen:"string"`
	EpochTime           int            `json:"epoch_time,omitempty" gen:"int"`
	Native              bool           `json:"native,omitempty" gen:"bool"`
	ActiveCount         any            `json:"active_count,omitempty" gen:"union<int,string>"`
	Url                 string         `json:"url,omitempty" gen:"string"`
	PostData            *SwaigRequest  `json:"post_data,omitempty" gen:"class:signalwire.core.swaig_request_generated.SwaigRequest"`
	PostResponse        map[string]any `json:"post_response,omitempty" gen:"dict<string,any>"`
	DelayedPostResponse map[string]any `json:"delayed_post_response,omitempty" gen:"dict<string,any>"`
	McpUrl              string         `json:"mcp_url,omitempty" gen:"string"`
	McpTool             string         `json:"mcp_tool,omitempty" gen:"string"`
	McpResponse         map[string]any `json:"mcp_response,omitempty" gen:"dict<string,any>"`
	McpError            string         `json:"mcp_error,omitempty" gen:"string"`
}

type PostPromptTimesEntry struct {
	Response          string  `json:"response,omitempty" gen:"string"`
	ResponseWordCount int     `json:"response_word_count,omitempty" gen:"int"`
	AnswerTime        float64 `json:"answer_time,omitempty" gen:"float"`
	TokenTime         float64 `json:"token_time,omitempty" gen:"float"`
	Tokens            int     `json:"tokens,omitempty" gen:"int"`
	AvgTps            float64 `json:"avg_tps,omitempty" gen:"float"`
	Tps               float64 `json:"tps,omitempty" gen:"float"`
}

type PostPromptEntity struct {
	Type  string `json:"type,omitempty" gen:"string"`
	Value string `json:"value,omitempty" gen:"string"`
	Valid bool   `json:"valid,omitempty" gen:"bool"`
}

type PostPromptEot struct {
	Basis      string  `json:"basis,omitempty" gen:"string"`
	Confidence float64 `json:"confidence,omitempty" gen:"float"`
}

type PostPromptTiming struct {
	HoldMs          float64 `json:"hold_ms,omitempty" gen:"float"`
	CommitLatencyMs float64 `json:"commit_latency_ms,omitempty" gen:"float"`
	Segments        int     `json:"segments,omitempty" gen:"int"`
	Walkbacks       int     `json:"walkbacks,omitempty" gen:"int"`
}

type PostPromptStampsUs struct {
	SpeechStart    int `json:"speech_start,omitempty" gen:"int"`
	LastWordEnd    int `json:"last_word_end,omitempty" gen:"int"`
	SuspectedEnd   int `json:"suspected_end,omitempty" gen:"int"`
	TurnDecided    int `json:"turn_decided,omitempty" gen:"int"`
	StatusPushed   int `json:"status_pushed,omitempty" gen:"int"`
	RequestDetect  int `json:"request_detect,omitempty" gen:"int"`
	FirstToken     int `json:"first_token,omitempty" gen:"int"`
	FirstUtterance int `json:"first_utterance,omitempty" gen:"int"`
	FirstAudio     int `json:"first_audio,omitempty" gen:"int"`
}
