// Code generated by cmd/generate-swaig-payloads; DO NOT EDIT.
//
// AUTO-GENERATED from porting-sdk/swaig-specs/swaig-response.yaml — regenerate with:
//   go run ./cmd/generate-swaig-payloads
//
// The typed SWAIG response-action CONFIG types (one <Verb>Action per object-
// shaped action value) plus the SwaigAction/SwaigResponse envelope. The
// ergonomic builder methods live on FunctionResult.

package swaig

type ChangeVoiceAction struct {
	Voice map[string]any `json:"voice,omitempty" gen:"dict<string,any>"`
}

type ContextSwitchAction struct {
	Consolidate  any            `json:"consolidate,omitempty" gen:"union<bool,string>"`
	FullReset    any            `json:"full_reset,omitempty" gen:"union<bool,string>"`
	SystemPom    map[string]any `json:"system_pom,omitempty" gen:"dict<string,any>"`
	SystemPrompt string         `json:"system_prompt,omitempty" gen:"string"`
	UserPom      map[string]any `json:"user_pom,omitempty" gen:"dict<string,any>"`
	UserPrompt   string         `json:"user_prompt,omitempty" gen:"string"`
}

type HoldAction struct {
	Step        string `json:"step,omitempty" gen:"string"`
	Timeout     any    `json:"timeout,omitempty" gen:"union<float,string>"`
	TimeoutStep string `json:"timeout_step,omitempty" gen:"string"`
}

type PlaybackBgAction struct {
	File string `json:"file,omitempty" gen:"string"`
	Wait any    `json:"wait,omitempty" gen:"union<bool,string>"`
}

type TransferAction struct {
	Dest      string `json:"dest,omitempty" gen:"string"`
	Summarize any    `json:"summarize,omitempty" gen:"union<bool,string>"`
}

// SwaigAction A response-action object. The keys below are the full vocabulary dispatched by actions.c::process_action; an action object sets one or more of them. Each key's source line is the engine dispatch site.
type SwaigAction struct {
	// SWML Execute a SWML document inline, or with sibling `transfer:true` transfer the call into it. Gated by `swaig_allow_swml`. **Transfer additionally requires `from_relay`** (`actions.c:142-145`); inline execution captures an optional `ai_response` SWML var back into the conversation
	SWML any `json:"SWML,omitempty" gen:"union<string,dict<string,any>>"`
	// AddDynamicHints Add ASR hints. Strings go to `dynamic_hints`; `{hint, ...}` objects go to `dynamic_hearing_hints` (and the `hint` value is also added to `dynamic_hints`). Restarts speech detection
	AddDynamicHints []any `json:"add_dynamic_hints,omitempty" gen:"list<union<dict<string,any>,string>>"`
	// BackToBackFunctions Allow consecutive function calls without a user turn. `true` = `1`, `"forever"` = `2`
	BackToBackFunctions any `json:"back_to_back_functions,omitempty" gen:"union<bool,string>"`
	// ChangeContext Switch to a named **context** (same machinery as the `change_context` function)
	ChangeContext string `json:"change_context,omitempty" gen:"string"`
	// ChangeStep Switch to a named **step** (or `"next"`)
	ChangeStep string `json:"change_step,omitempty" gen:"string"`
	// ChangeVoice Staged at `actions.c:490`, applied by `ai_threads.c` `apply_pending_voice_change`. The string (or the object's `voice`) is an `engine.voice:model` spec. Change the agent's voice mid-call by rebinding the **current language's** voice node (`cur_aish`) to an arbitrary `engine.voice:model` — works in both `~LN` (Mode A) and ASR-driven (Mode B) multilingual modes, since `cur_aish` is the current language's node in both. Cross-engine is intended (e.g. switch to a fish/groq voice for its sound/delivery tags). Staged on the session thread; the output thread closes+reopens the handle at the next batch boundary (never mid-utterance). Writes the node's **configured** identity, so the new voice **persists across later language re-selects of that node for the rest of the call**; a voice that will not open falls back to the fallback voice. Not persisted across calls (the voice list is rebuilt from SWML each session)
	ChangeVoice any `json:"change_voice,omitempty" gen:"union<string,class:signalwire.core.swaig_actions_generated.ChangeVoiceAction>"`
	// ClearDynamicHints Clear both dynamic hint lists and restart speech detection
	ClearDynamicHints any `json:"clear_dynamic_hints,omitempty" gen:"union<bool,string>"`
	// ContextSwitch Replace the system prompt / start a new conversation context. Object form: `{system_prompt, user_prompt, system_pom, user_pom, consolidate, full_reset}`. `system_pom`/`user_pom` render to prompt text; prompts are expanded against prompt vars + post_data, except when the action comes from a data_map function, whose output is already expanded; `consolidate:true` summarizes first
	ContextSwitch any `json:"context_switch,omitempty" gen:"union<string,class:signalwire.core.swaig_actions_generated.ContextSwitchAction>"`
	// EndOfSpeechTimeout Set end-of-speech detection timeout (must be >0)
	EndOfSpeechTimeout int `json:"end_of_speech_timeout,omitempty" gen:"int"`
	// ExtensiveData Enable extensive data in the function/conversation log
	ExtensiveData any `json:"extensive_data,omitempty" gen:"union<bool,string>"`
	// FunctionsOnSpeakerTimeout Set whether functions may fire on speaker timeout
	FunctionsOnSpeakerTimeout any `json:"functions_on_speaker_timeout,omitempty" gen:"union<bool,string>"`
	// Hangup Set `offhook = 0` (hang up). Note: a graceful "say goodbye" hangup is the **built-in `hangup` function**, not this action
	Hangup any `json:"hangup,omitempty" gen:"union<bool,string>"`
	// Hold Put the call on hold for N seconds. Accepts a number, a time string (`"5m"`, `"1:30"` via `parse_time`), or an object `{timeout, step, timeout_step}`. Default 300s; values <0 or >900 clamp to 300. `step` / `timeout_step` are optional destinations applied **when the hold ends** — see below
	Hold any `json:"hold,omitempty" gen:"union<int,string,class:signalwire.core.swaig_actions_generated.HoldAction>"`
	// PlaybackBg Play an audio file in the background. `{wait:true}` makes the agent wait for it. Replaces any currently-open background file
	PlaybackBg any `json:"playback_bg,omitempty" gen:"union<string,class:signalwire.core.swaig_actions_generated.PlaybackBgAction>"`
	// ReplaceInHistory Replace the function call's text in conversation history. A string is stored prefixed with `~LN(<language>)-; `; `true` stores an empty string
	ReplaceInHistory any `json:"replace_in_history,omitempty" gen:"string"`
	// Say Speak text immediately via TTS, then wait for speaking to finish. Also logs `tl_manual_say`
	Say string `json:"say,omitempty" gen:"string"`
	// SetGlobalData Merge keys into global data, then refresh prompt vars. Gated by `swaig_set_global_data`
	SetGlobalData map[string]any `json:"set_global_data,omitempty" gen:"dict<string,any>"`
	// SetMetaData Merge keys into the calling function's metadata store (keyed by its `meta_data_token`)
	SetMetaData map[string]any `json:"set_meta_data,omitempty" gen:"dict<string,any>"`
	// Settings Modify LLM settings at runtime (`parse_json_settings`). Gated by `swaig_allow_settings`
	Settings map[string]any `json:"settings,omitempty" gen:"dict<string,any>"`
	// SpeechEventTimeout Set speech event timeout (must be >0)
	SpeechEventTimeout int `json:"speech_event_timeout,omitempty" gen:"int"`
	// Stop Stop the AI agent immediately (interrupt + `running = 0`)
	Stop any `json:"stop,omitempty" gen:"union<bool,string>"`
	// StopPlaybackBg Stop/close the background audio file
	StopPlaybackBg any `json:"stop_playback_bg,omitempty" gen:"optional<union<bool,string,int,dict<string,any>,list<any>>>"`
	// ToggleFunctions Enable/disable functions. `active` via `check_active`: `-1` default/toggle, `0` off, `1+` use-count. **Only affects functions sharing the calling function's `meta_data_token`** (`actions.c:426-427`)
	ToggleFunctions []map[string]any `json:"toggle_functions,omitempty" gen:"list<dict<string,any>>"`
	// Transfer Transfer the call to `dest`. `summarize:true` sets `transfer_summary`. Sets `openai_transfer_check` var, interrupts, stops the loop. Ignored if already interrupted
	Transfer any `json:"transfer,omitempty" gen:"union<string,class:signalwire.core.swaig_actions_generated.TransferAction>"`
	// UnsetGlobalData Remove key(s) from global data, then refresh prompt vars. Gated by `swaig_set_global_data`
	UnsetGlobalData any `json:"unset_global_data,omitempty" gen:"union<string,list<string>>"`
	// UnsetMetaData Remove key(s) from the calling function's metadata store
	UnsetMetaData any `json:"unset_meta_data,omitempty" gen:"union<string,list<string>>"`
	// UserEvent Fire relay event `calling.user_event` with the object as payload
	UserEvent map[string]any `json:"user_event,omitempty" gen:"dict<string,any>"`
	// UserInput Push text onto the input queue as if the user spoke it
	UserInput string `json:"user_input,omitempty" gen:"string"`
	// WaitForUser `true` = `1`, a number sets a count, `"answer_first"` = `2` (require caller answer)
	WaitForUser any `json:"wait_for_user,omitempty" gen:"union<bool,int,string>"`
}

// SwaigResponse Parsed at actions.c:2685-2727.
type SwaigResponse struct {
	// Response Result fed back to the AI for its reply: a string, or an object splitting it into named parts. Which arm applies is decided by the value's JSON type.
	Response any `json:"response,omitempty" gen:"union<string,dict<string,any>>"`
	// Action One action object, or an array of them. Each object may carry several action keys; every recognized key is dispatched. See SwaigAction.
	Action any `json:"action,omitempty" gen:"union<class:signalwire.core.swaig_actions_generated.SwaigAction,list<class:signalwire.core.swaig_actions_generated.SwaigAction>>"`
	// PostProcess If true, defer response+actions until after the AI's next turn (delayed_response).
	PostProcess bool `json:"post_process,omitempty" gen:"bool"`
}
