package agent

import (
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
)

// ---------------------------------------------------------------------------
// Basic auth validation
// ---------------------------------------------------------------------------

func TestAuth_ExplicitCredentials(t *testing.T) {
	a := NewAgentBase(WithBasicAuth("testuser", "testpass"))
	user, pass := a.Service.GetBasicAuthCredentials()
	if user != "testuser" {
		t.Errorf("user = %q, want %q", user, "testuser")
	}
	if pass != "testpass" {
		t.Errorf("pass = %q, want %q", pass, "testpass")
	}
}

func TestAuth_AutoGeneratedCredentials(t *testing.T) {
	// Temporarily clear env vars to test auto-generation
	origUser := os.Getenv("SWML_BASIC_AUTH_USER")
	origPass := os.Getenv("SWML_BASIC_AUTH_PASSWORD")
	os.Unsetenv("SWML_BASIC_AUTH_USER")
	os.Unsetenv("SWML_BASIC_AUTH_PASSWORD")
	defer func() {
		if origUser != "" {
			os.Setenv("SWML_BASIC_AUTH_USER", origUser)
		}
		if origPass != "" {
			os.Setenv("SWML_BASIC_AUTH_PASSWORD", origPass)
		}
	}()

	a := NewAgentBase(WithName("MyAgent"))
	user, pass := a.Service.GetBasicAuthCredentials()
	// Default user is the agent name
	if user != "MyAgent" {
		t.Errorf("user = %q, want %q", user, "MyAgent")
	}
	// Password should be auto-generated (32 hex characters)
	if len(pass) != 32 {
		t.Errorf("auto password length = %d, want 32", len(pass))
	}
}

func TestAuth_RejectsNoAuth(t *testing.T) {
	a := NewAgentBase(WithBasicAuth("user", "pass"))
	mux := a.buildMux()

	req := httptest.NewRequest("GET", "/", nil)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusUnauthorized {
		t.Errorf("status = %d, want %d", w.Code, http.StatusUnauthorized)
	}
}

func TestAuth_RejectsWrongCredentials(t *testing.T) {
	a := NewAgentBase(WithBasicAuth("user", "pass"))
	mux := a.buildMux()

	req := httptest.NewRequest("GET", "/", nil)
	req.SetBasicAuth("wrong", "creds")
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusUnauthorized {
		t.Errorf("status = %d, want %d", w.Code, http.StatusUnauthorized)
	}
}

func TestAuth_AcceptsCorrectCredentials(t *testing.T) {
	a := NewAgentBase(WithBasicAuth("user", "pass"))
	mux := a.buildMux()

	req := httptest.NewRequest("GET", "/", nil)
	req.SetBasicAuth("user", "pass")
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}
}

func TestAuth_SecurityHeaders(t *testing.T) {
	a := NewAgentBase(WithBasicAuth("user", "pass"))
	mux := a.buildMux()

	req := httptest.NewRequest("GET", "/", nil)
	req.SetBasicAuth("user", "pass")
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Header().Get("X-Content-Type-Options") != "nosniff" {
		t.Error("expected X-Content-Type-Options=nosniff")
	}
	if w.Header().Get("X-Frame-Options") != "DENY" {
		t.Error("expected X-Frame-Options=DENY")
	}
	if w.Header().Get("Cache-Control") != "no-store" {
		t.Error("expected Cache-Control=no-store")
	}
}

func TestAuth_HealthEndpointNoAuth(t *testing.T) {
	a := NewAgentBase(WithBasicAuth("user", "pass"))
	mux := a.buildMux()

	req := httptest.NewRequest("GET", "/health", nil)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("health endpoint should not require auth, got status %d", w.Code)
	}
}

func TestAuth_ReadyEndpointNoAuth(t *testing.T) {
	a := NewAgentBase(WithBasicAuth("user", "pass"))
	mux := a.buildMux()

	req := httptest.NewRequest("GET", "/ready", nil)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("ready endpoint should not require auth, got status %d", w.Code)
	}
}

func TestAuth_WWWAuthenticateHeader(t *testing.T) {
	a := NewAgentBase(WithBasicAuth("user", "pass"))
	mux := a.buildMux()

	req := httptest.NewRequest("GET", "/", nil)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	wwwAuth := w.Header().Get("WWW-Authenticate")
	if wwwAuth == "" {
		t.Error("expected WWW-Authenticate header on 401")
	}
}
